---
title: "IRS data"
author: "Yuanhang(Leo) Yu"
date: "2023-05-26"
output:
  html_document:
    toc: yes
    df_print: paged
  # pdf_document:
    # number_sections: yes
  # html_notebook:
    # toc: yes
    # df_print: paged
    # number_sections: yes
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{pifont}
- \usepackage{mathpazo}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list = ls())  
```

```{r message=FALSE, warning=FALSE, cache=FALSE, include=FALSE, results='hide'}
# libraries
options( scipen=100, digits = 15, stringsAsFactors=FALSE ); # no scientific notation, up to 15 digits 

# vector of libraries to be used
libs <- c( 'dplyr', 'tidyr', 'haven', 'stringr', 'nleqslv', 'gdata', 'formattable', 'ggplot2', 'viridis', 'RColorBrewer', 'reshape2', 'foreign', 'readxl', 'writexl', 'rjson', 'read_excel', 'Matrix', 'geodist', 'readr', 'data.table', 'stringr', 'haven');
# Install libraries in case they are not installed
for( i in seq_along(libs)){ 
    if( !(libs[i] %in% installed.packages()) ) install.packages( libs[i] ) 
};
# Loading libraries
lapply( libs, require, character.only=TRUE );
```

## IRS

This document process IRS data.

```{r include=FALSE}

####### Old: this process the state-by-state IRS data, which is not used after ##########

# yr_list  <-  c("1999_2000", "2000_2001", "2001_2002", "2002_2003", "2003_2004", "2007_2008")
# yr_list  <-  c("1999_2000")
yr  <-  "1999_2000"
base <- c()
yr_c <- 1999

# for (yr in yr_list){
  
folder_path  <- paste("0-Raw_Data/IRS/state", yr, sep = "")
file_list  <- list.files(folder_path)
for (file_name in file_list){
    
    temp <- read_xls(paste(folder_path, file_name, sep = "/"), range = "A1:C4", col_names = c("state", "x", "y"))
    temp <-  temp[c(1,4),]
    temp  <- temp  %>% 
      mutate(state_new = paste(state, x, y))  %>% 
      select(state_new)  %>% 
      rename(state = state_new)
    temp$state  <- gsub(" NA*", "", temp$state)  

    temp$state[1]  <- sub(".* - ", "", temp$state[1])
    temp$state[2]  <- sub("^TO: \\d{2}-", "", temp$state[2])
    temp$state[2]  <- sub("^FROM: \\d{2}-", "", temp$state[2])
    temp$state  <- gsub(" ", "", temp$state)
    names(temp) <- ifelse(temp[1, 1] == "INFLOW", "state_dest", "state_ori")

    temp  <- temp[-1,]
    temp  <- temp[rep(1,52),]
    
    data <- read_xls(paste(folder_path, file_name, sep = "/"), range = "A9:F63", col_names = c("state_num", "state_code", "state", "returns", "exemption", "income"))
    
    data  <- data[-c(1:3), ]
    data  <- bind_cols(data, temp)
    if ("state_ori" %in% colnames(data)) {
      data$state[1] <- data$state_ori[1]
    } else if ("state_dest" %in% colnames(data)) {
      data$state[1] <- data$state_dest[1]
    }
    
    if("state_dest"  %in% colnames(data)){
      data  <- rename(data, state_ori = state)
    } else {
      data  <- rename(data, state_dest = state)
    }
    
    if(yr == "2007_2008"){
       data$year  <- 2007
    } else {
       data$year  <- yr_c
    }
    
    data  <- data  %>% 
      mutate(flag = file_name)
  
   base  <- bind_rows(base, data)
}

# } 

base  <- base  %>% 
  filter(state_dest != "Foreign" & state_ori != "Foreign")   %>% 
  mutate(across(c("state_dest", "state_ori"), ~tolower(.x) %>% str_to_title))  %>% 
  select(year, state_dest, state_ori, exemption, flag)

base$state_dest  <- gsub(" ", "", base$state_dest )  
base$state_ori  <- gsub(" ", "", base$state_ori)  

base <- base %>%
  mutate(state_dest = case_when(
    state_dest == "Newhampshire" ~ "NewHampshire", 
    state_dest == "Newjersey" ~ "NewJersey",
    state_dest == "Newmexico" ~ "NewMexico",
    state_dest == "Newyork" ~ "NewYork",
    state_dest == "Northcarolina" ~ "NorthCarolina",
    state_dest == "Northdakota" ~ "NorthDakota",
    state_dest == "Southcarolina" ~ "SouthCarolina",
    state_dest == "Southdakota" ~ "SouthDakota",
    state_dest == "Westvirginia" ~ "WestVirginia",
    state_dest == "Rhodeisland" ~ "RhodeIsland",
    TRUE ~ state_dest),
  state_ori = case_when(
    state_ori == "Newhampshire" ~ "NewHampshire", 
    state_ori == "Newjersey" ~ "NewJersey",
    state_ori == "Newmexico" ~ "NewMexico",
    state_ori == "Newyork" ~ "NewYork",
    state_ori == "Northcarolina" ~ "NorthCarolina",
    state_ori == "Northdakota" ~ "NorthDakota",
    state_ori == "Southcarolina" ~ "SouthCarolina",
    state_ori == "Southdakota" ~ "SouthDakota",
    state_ori == "Westvirginia" ~ "WestVirginia",
    state_ori == "Rhodeisland" ~ "RhodeIsland",
    TRUE ~ state_ori
  ))


base  <- base  %>% 
  distinct(year, state_dest, state_ori, exemption, .keep_all = TRUE)  %>% 
  select(-flag) 

state_name  <- c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "NewHampshire", "NewJersey", "NewMexico", "NewYork", "NorthCarolina", "NorthDakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "RhodeIsland", "SouthCarolina", "SouthDakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "WestVirginia", "Wisconsin", "Wyoming")

base  <- base  %>% 
  mutate(flag_name = ifelse(state_dest  %in% state_name & state_ori  %in% state_name, 1, 0 ))  %>% 
  filter(flag_name == 1)  %>% 
  select(-flag_name)

write.table(base, file = paste("1-Intermediate_Processed_Data//irs.csv", sep=""), sep = ",", row.names = FALSE) 

```

```{r include=FALSE}
 
######## This part cleans the county-by-county IRS data ########## 

irs_temp  <- read_dta("0-Raw_Data/IRS/1999to2000CountyMigration/1999to2000flow.dta")

state_name  <- c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "NewHampshire", "NewJersey", "NewMexico", "NewYork", "NorthCarolina", "NorthDakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "RhodeIsland", "SouthCarolina", "SouthDakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "WestVirginia", "Wisconsin", "Wyoming")

all_combo <- c()
for (state in state_name) {
temp <- data.frame(state_name) #list of regions
temp <- temp %>%
  dplyr::rename(state_ori = state_name) %>%
  mutate(state_dest = state)  #create destination state and sector
all_combo <- bind_rows(all_combo, temp) #add all together, therefore all combination 
}

irs  <- all_combo %>% 
  left_join(irs_temp, by = c('state_dest' = 'state_dest', 'state_ori' = 'state_ori'))  %>% 
  mutate(year = 1999)  %>% 
  mutate(exemption = ifelse(is.na(exemption), 0, exemption))

write.table(irs, file = paste("1-Intermediate_Processed_Data//irs.csv", sep=""), sep = ",", row.names = FALSE) 

```


$$
L^{nj,ik} =L_{IRS}^{n,i}\times\frac{L_{CPS}^{ij,ik}}{\sum_{q}\sum_{h}L_{CPS}^{ih,iq}}
$$

```{r}
#loading intermediate CPS
cps <- read.csv(paste("1-Intermediate_Processed_Data//cps_2.csv", sep=""), header = TRUE, sep = ",", dec = ".")

#loading intermediate ACS
irs <- read.csv(paste("1-Intermediate_Processed_Data//irs.csv", sep=""), header = TRUE, sep = ",", dec = ".")


#Mobility matrices

#disaggregating IRS data using CPS sector_ori info and computation of mobility share
#origin in rows and destination in columns
#row shares sum to 1

#adjusting x's to y's: cps migration pair share times total migration from irs
mobility <- cps %>%
  left_join(irs, by=c('year' = 'year', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori')) %>%
  group_by(year, state_dest, state_ori) %>% 
  mutate(tot_n_cps_accros_sec = sum(n_cps)) %>% #totol within destination state migration (sum over all sector movements)
  ungroup() %>%
  mutate(n_cps_adj = n_cps/tot_n_cps_accros_sec) %>% #migration share across sectors within state (based on destination state)
  mutate(n_cps_adj = ifelse(is.na(n_cps_adj) == TRUE, 0, n_cps_adj)) %>%
  mutate(n_cps_adj = n_cps_adj*exemption) %>% #use cps within-state across sector migration share times acs total migration across states
  select(-tot_n_cps_accros_sec, -n_cps, -exemption) 
#mobility  <- mobility  %>% arrange(state_ori, sector_ori, state_dest, sector_dest,desc(year))


#mu_1999 prime for L_1999
#the second part of this calculation is in the next step since there is an additional proportionality that has to be implemented in L_2000 so that it is consistent with WIOD
mu_1999_prime <- mobility %>%
  filter(year == 1999) %>%
  group_by(year, state_dest, sector_dest) %>% 
  mutate(tot_n = sum(n_cps_adj)) %>% # total inflows to destination state-sector
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n) %>%  #(inflow share of destination state-sector across original state-sector)rel: share of people from original state-sector pairs to the same destination state-sector
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel)

write.table(mu_1999_prime, file = paste("1-Intermediate_Processed_Data/mu_1999_prime_irs.csv", sep=""), sep = ",", row.names = FALSE)


#mu_1999 prime for L_1999
mu_1999_prime <- read.csv(paste("1-Intermediate_Processed_Data/mu_1999_prime_irs.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars=c("state"), variable.name="sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector)))
mu_1999_prime <- mu_1999_prime %>%
  left_join(L_2000, by=c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%
  select(-rel, -employ)
write.table(mu_1999_prime, file = paste("1-Intermediate_Processed_Data//mu_1999_prime_irs.csv", sep=""), sep = ",", row.names = FALSE)


#Computing L_1999 using mobility matrices and L_2000
mu_1999_prime <- read.csv(paste("1-Intermediate_Processed_Data/mu_1999_prime_irs.csv", sep=""), header = TRUE, sep = ",", dec = ".")

#mu_1999_prime  <- mu_1999_prime  %>% mutate(flag = is.na(level_employ))

L_1999 <- mu_1999_prime %>%
  group_by(state_ori, sector_ori) %>%
  mutate(employ = sum(level_employ)) %>%
  ungroup() %>%
  distinct(state_ori, sector_ori, .keep_all = TRUE) %>%
  dplyr::rename(state = state_ori, sector = sector_ori) %>%
  select(state, sector, employ) %>%
  arrange(state, sector)
temp_L_1999 <- L_1999
L_1999 <- spread(L_1999, sector, employ, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
write.table(L_1999, file = paste("1-Intermediate_Processed_Data/L_1999_irs.csv", sep=""), sep = ",", row.names = FALSE)
#Recalculating mu_1999 and checking flow 1999-2000
mu_1999 <- mu_1999_prime %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% 
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
mu_1999 <- mu_1999 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999 <- spread(mu_1999, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
#check sum(prob)==1
epsilon <- 0.01
check <- mu_1999 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999, path = paste("2-Final_Data//mu_1999_irs.xlsx", sep=""))

#check L_1999 and mu_1999 gives L_2000
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars=c("state"), variable.name="sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector))) %>%
  arrange(state, sector)
L_2000 <- as.matrix(L_2000$employ)
L_1999 <- as.matrix(temp_L_1999$employ)
mu_1999 <- mu_1999 %>% select(-year, -state_ori, -sector_ori)
mu_1999 <- as.matrix(mu_1999)
if(sum(L_2000 - (t(mu_1999)%*%L_1999)) > epsilon) 
  stop(paste("L_1999 and mu_1999 do NOT give L_2000"))



#Combining L states with L countries
# SEA_countries <- read.csv("1-Intermediate_Processed_Data/SEA_countries.csv", header = TRUE, sep = ",", dec = ".")
# 
# for (yr in 1999:2007) {
# L_countries <- SEA_countries %>%
#   filter(year == yr) %>%
#   arrange(country, sector) %>%
#   dplyr::rename(region = country) %>%
#   select(-year) %>%
#   mutate(sector = recode(as.character(sector), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
#   mutate(sector = paste("sector", sector, sep="_"))
# L_countries <- spread(L_countries, sector, employ, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
# 
#   
# L_states <- read.csv(paste("1-Intermediate_Processed_Data/L_", yr,".csv", sep=""), header = TRUE, sep = ",", dec = ".")
# L_states <- melt(L_states, id.vars=c("state"), variable.name="sector", value.name = "employ")
# L_states <- L_states %>% 
#   mutate(sector = as.numeric(gsub("X", "", sector))) %>%
#   arrange(state, sector) %>%
#   dplyr::rename(region = state) %>%
#   mutate(sector = recode(as.character(sector), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
#   mutate(sector = paste("sector", sector, sep="_"))
# L_states <- spread(L_states, sector, employ, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
# 
# L <- rbind(L_states, L_countries)
# 
# write_xlsx(L, path = paste("2-Final_Data/L_", yr,".xlsx", sep=""))
# 
# 
# }

```




$$
L^{nj,ik}=\frac{\sum_{q}L_{CPS}^{nj,nq}}{\sum_{q}\sum_{h}L_{CPS}^{nh,nq}}\times L_{IRS}^{n,i}\times\frac{\sum_{h}L_{CPS}^{ih,ik}}{\sum_{h}\sum_{q}L_{CPS}^{ih,iq}}
$$


```{r}
#loading intermediate CPS
cps <- read.csv(paste("1-Intermediate_Processed_Data//cps_2.csv", sep=""), header = TRUE, sep = ",", dec = ".")

temp_cps  <- cps %>% 
  filter(state_ori == state_dest & year == 1999)  %>% # keep only the within state migration combinations
  group_by(year, state_dest, state_ori)  %>% 
  mutate(n_cps_two_states_tot = sum(n_cps))  %>% 
  ungroup()  %>% 
  group_by(year, state_dest, state_ori, sector_ori)  %>% 
  mutate(n_cps_two_states_tot_inflow = sum(n_cps)) %>% # total flows migrate out of from the same original state
  ungroup() %>% 
  mutate(cps_share_migrate_out_from_same_ori = n_cps_two_states_tot_inflow/n_cps_two_states_tot) %>%  # denominator is the total migration flow within each state, the numerator is the total migration flow that starts from the same original sector (within state migration only); so the share means the share of migration out from certain original sector (within state) relative to total migration
  group_by(year, state_dest, state_ori, sector_dest)  %>% # total flows migrate to the same destination state
  mutate(n_cps_two_states_tot_outflow = sum(n_cps))  %>% 
  ungroup()   %>% 
  mutate(cps_share_migrate_in_same_dest = n_cps_two_states_tot_outflow/n_cps_two_states_tot)  

temp_cps_ori  <- temp_cps  %>% 
  select(year, sector_ori, state_dest, sector_dest, cps_share_migrate_out_from_same_ori)
temp_cps_dest  <- temp_cps  %>% 
  select(year, sector_ori, state_dest, sector_dest, cps_share_migrate_in_same_dest)

cps  <- cps %>% 
  filter(year == 1999)  %>% 
  left_join(temp_cps_ori, by = c("year" = "year", "sector_ori" = "sector_ori", "state_ori" = "state_dest", "sector_dest" = "sector_dest"))  %>% 
  left_join(temp_cps_dest, by = c("year" = "year", "sector_ori" = "sector_ori", "state_dest" = "state_dest", "sector_dest" = "sector_dest"))
  
#loading intermediate ACS
irs <- read.csv(paste("1-Intermediate_Processed_Data//irs.csv", sep=""), header = TRUE, sep = ",", dec = ".")


#Mobility matrices

#disaggregating ACS data using CPS sector_ori info and computation of mobility share
#origin in rows and destination in columns
#row shares sum to 1

#adjusting x's to y's: cps migration pair share times total migration from acs
mobility <- cps %>%
  left_join(irs, by=c('year' = 'year', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori')) %>%
  mutate(n_cps_adj = cps_share_migrate_in_same_dest * cps_share_migrate_out_from_same_ori * exemption)  
  
#mu_1999 prime for L_1999
#the second part of this calculation is in the next step since there is an additional proportionality that has to be implemented in L_2000 so that it is consistent with WIOD
mu_1999_prime <- mobility %>%
  group_by(year, state_dest, sector_dest) %>% 
  mutate(tot_n = sum(n_cps_adj)) %>% # total inflows to destination state-sector
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n) %>%  #(inflow share of destination state-sector across original state-sector)rel: share of people from original state-sector pairs to the same destination state-sector
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel)

write.table(mu_1999_prime, file = paste("1-Intermediate_Processed_Data/mu_1999_prime_irs_2.csv", sep=""), sep = ",", row.names = FALSE)


#mu_1999 prime for L_1999
mu_1999_prime <- read.csv(paste("1-Intermediate_Processed_Data/mu_1999_prime_irs_2.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars=c("state"), variable.name="sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector)))
mu_1999_prime <- mu_1999_prime %>%
  left_join(L_2000, by=c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) 
mu_1999_prime  <- mu_1999_prime  %>% 
  select(-rel, -employ)
write.table(mu_1999_prime, file = paste("1-Intermediate_Processed_Data//mu_1999_prime_irs_2.csv", sep=""), sep = ",", row.names = FALSE)


#Computing L_1999 using mobility matrices and L_2000
mu_1999_prime <- read.csv(paste("1-Intermediate_Processed_Data/mu_1999_prime_irs_2.csv", sep=""), header = TRUE, sep = ",", dec = ".")

L_1999 <- mu_1999_prime %>%
  group_by(state_ori, sector_ori) %>%
  mutate(employ = sum(level_employ)) %>%
  ungroup() %>%
  distinct(state_ori, sector_ori, .keep_all = TRUE) %>%
  dplyr::rename(state = state_ori, sector = sector_ori) %>%
  select(state, sector, employ) %>%
  arrange(state, sector)
temp_L_1999 <- L_1999
L_1999 <- spread(L_1999, sector, employ, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
write.table(L_1999, file = paste("1-Intermediate_Processed_Data/L_1999_irs_2.csv", sep=""), sep = ",", row.names = FALSE)
#Recalculating mu_1999 and checking flow 1999-2000
mu_1999 <- mu_1999_prime %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% 
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
mu_1999 <- mu_1999 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999 <- spread(mu_1999, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
#check sum(prob)==1
epsilon <- 0.01
check <- mu_1999 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999, path = paste("2-Final_Data//mu_1999_irs_2.xlsx", sep=""))

#check L_1999 and mu_1999 gives L_2000
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars=c("state"), variable.name="sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector))) %>%
  arrange(state, sector)
L_2000 <- as.matrix(L_2000$employ)
L_1999 <- as.matrix(temp_L_1999$employ)
mu_1999 <- mu_1999 %>% select(-year, -state_ori, -sector_ori)
mu_1999 <- as.matrix(mu_1999)
if(sum(L_2000 - (t(mu_1999)%*%L_1999)) > epsilon) 
  stop(paste("L_1999 and mu_1999 do NOT give L_2000"))



# 
# #Combining L states with L countries
# SEA_countries <- read.csv("1-Intermediate_Processed_Data/SEA_countries.csv", header = TRUE, sep = ",", dec = ".")
# 
# for (yr in 1999:2007) {
# L_countries <- SEA_countries %>%
#   filter(year == yr) %>%
#   arrange(country, sector) %>%
#   dplyr::rename(region = country) %>%
#   select(-year) %>%
#   mutate(sector = recode(as.character(sector), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
#   mutate(sector = paste("sector", sector, sep="_"))
# L_countries <- spread(L_countries, sector, employ, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
# 
#   
# L_states <- read.csv(paste("1-Intermediate_Processed_Data/L_", yr,".csv", sep=""), header = TRUE, sep = ",", dec = ".")
# L_states <- melt(L_states, id.vars=c("state"), variable.name="sector", value.name = "employ")
# L_states <- L_states %>% 
#   mutate(sector = as.numeric(gsub("X", "", sector))) %>%
#   arrange(state, sector) %>%
#   dplyr::rename(region = state) %>%
#   mutate(sector = recode(as.character(sector), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
#   mutate(sector = paste("sector", sector, sep="_"))
# L_states <- spread(L_states, sector, employ, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
# 
# L <- rbind(L_states, L_countries)
# 
# write_xlsx(L, path = paste("2-Final_Data/L_", yr,".xlsx", sep=""))
# }

```


$$
L^{nj,ik}=\frac{\sum_{q}L_{CPS}^{nj,nq}}{\sum_{q}\sum_{h}L_{CPS}^{nh,nq}}\times L_{IRS}^{n,i}\times\frac{L_{ACS}^{n?,ik}}{\sum_{q}L_{ACS}^{n?,iq}}
$$

```{r}
#loading intermediate CPS
cps <- read.csv(paste("1-Intermediate_Processed_Data//cps_2.csv", sep=""), header = TRUE, sep = ",", dec = ".")

temp_cps  <- cps %>% 
  filter(state_ori == state_dest & year == 1999)  %>% 
  group_by(year, state_dest, state_ori)  %>% 
  mutate(n_cps_two_states_tot = sum(n_cps))  %>% 
  ungroup()  %>% 
  group_by(year, state_dest, state_ori, sector_ori)  %>% 
  mutate(n_cps_two_states_tot_inflow = sum(n_cps)) %>% 
  ungroup() %>% 
  mutate(cps_share_migrate_out_from_same_ori = n_cps_two_states_tot_inflow/n_cps_two_states_tot) %>%  # denominator is the total migration flow within each state, the numerator is the total migration flow that starts from the same original sector (within state migration only); so the share means the share of migration out from certain original sector (within state) relative to total migration
  group_by(year, state_dest, state_ori, sector_dest)  %>% 
  mutate(n_cps_two_states_tot_outflow = sum(n_cps))  %>% 
  ungroup()   %>% 
  mutate(cps_share_migrate_in_same_dest = n_cps_two_states_tot_outflow/n_cps_two_states_tot)  

temp_cps_ori  <- temp_cps  %>% 
  select(year, sector_ori, state_dest, sector_dest, cps_share_migrate_out_from_same_ori)

cps  <- cps %>% 
  left_join(temp_cps_ori, by = c("year" = "year", "sector_ori" = "sector_ori", "state_ori" = "state_dest", "sector_dest" = "sector_dest"))  %>% 
  filter(year == 1999)


acs <- read.csv(paste("1-Intermediate_Processed_Data//acs.csv", sep=""), header = TRUE, sep = ",", dec = ".")


#Mobility matrices

#disaggregating ACS data using CPS sector_ori info and computation of mobility share
#origin in rows and destination in columns
#row shares sum to 1

acs <- acs %>%
  group_by(year, state_ori, state_dest) %>%
  mutate(n_acs_tot = sum(n_acs)) %>% #n_acs: for (state_ori, state_dest) pair, n_acs is the total migration summed over all destination sectors
  ungroup() %>%
  mutate(acs_share_migrate_in_same_dest = n_acs/n_acs_tot)  %>% 
  mutate(acs_share_migrate_in_same_dest = ifelse(is.na(acs_share_migrate_in_same_dest), 0, acs_share_migrate_in_same_dest)) 

#loading intermediate ACS
irs <- read.csv(paste("1-Intermediate_Processed_Data//irs.csv", sep=""), header = TRUE, sep = ",", dec = ".")


#Mobility matrices

#disaggregating ACS data using CPS sector_ori info and computation of mobility share
#origin in rows and destination in columns
#row shares sum to 1

#adjusting x's to y's: cps migration pair share times total migration from acs
mobility <- cps %>%
  left_join(irs, by=c('year' = 'year', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori')) %>%
  left_join(acs, by=c('year' = 'year', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori', 'sector_dest' = 'sector_dest'))  %>% 
  mutate(n_cps_adj = acs_share_migrate_in_same_dest * cps_share_migrate_out_from_same_ori * exemption)  
  
#mu_1999 prime for L_1999
#the second part of this calculation is in the next step since there is an additional proportionality that has to be implemented in L_2000 so that it is consistent with WIOD
mu_1999_prime <- mobility %>%
  group_by(year, state_dest, sector_dest) %>% 
  mutate(tot_n = sum(n_cps_adj)) %>% # total inflows to destination state-sector
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n) %>%  #(inflow share of destination state-sector across original state-sector)rel: share of people from original state-sector pairs to the same destination state-sector
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel)

write.table(mu_1999_prime, file = paste("1-Intermediate_Processed_Data/mu_1999_prime_irs_3.csv", sep=""), sep = ",", row.names = FALSE)


#mu_1999 prime for L_1999
mu_1999_prime <- read.csv(paste("1-Intermediate_Processed_Data/mu_1999_prime_irs_3.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars=c("state"), variable.name="sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector)))
mu_1999_prime <- mu_1999_prime %>%
  left_join(L_2000, by=c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%
  select(-rel, -employ)
write.table(mu_1999_prime, file = paste("1-Intermediate_Processed_Data//mu_1999_prime_irs_3.csv", sep=""), sep = ",", row.names = FALSE)


#Computing L_1999 using mobility matrices and L_2000
mu_1999_prime <- read.csv(paste("1-Intermediate_Processed_Data/mu_1999_prime_irs_3.csv", sep=""), header = TRUE, sep = ",", dec = ".")

L_1999 <- mu_1999_prime %>%
  group_by(state_ori, sector_ori) %>%
  mutate(employ = sum(level_employ)) %>%
  ungroup() %>%
  distinct(state_ori, sector_ori, .keep_all = TRUE) %>%
  dplyr::rename(state = state_ori, sector = sector_ori) %>%
  select(state, sector, employ) %>%
  arrange(state, sector)
temp_L_1999 <- L_1999
L_1999 <- spread(L_1999, sector, employ, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
write.table(L_1999, file = paste("1-Intermediate_Processed_Data/L_1999_irs_3.csv", sep=""), sep = ",", row.names = FALSE)
#Recalculating mu_1999 and checking flow 1999-2000
mu_1999 <- mu_1999_prime %>% 
  dplyr::rename(n_cps_adj_ = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj_)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj_/tot_n_cps_accros_dest) %>% 
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
mu_1999 <- mu_1999 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999 <- spread(mu_1999, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
#check sum(prob)==1
epsilon <- 0.01
check <- mu_1999 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999, path = paste("2-Final_Data//mu_1999_irs_3.xlsx", sep=""))

#check L_1999 and mu_1999 gives L_2000
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars=c("state"), variable.name="sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector))) %>%
  arrange(state, sector)
L_2000 <- as.matrix(L_2000$employ)
L_1999 <- as.matrix(temp_L_1999$employ)
mu_1999 <- mu_1999 %>% select(-year, -state_ori, -sector_ori)
mu_1999 <- as.matrix(mu_1999)
if(sum(L_2000 - (t(mu_1999)%*%L_1999)) > epsilon) 
  stop(paste("L_1999 and mu_1999 do NOT give L_2000"))

```

## New: June 11th 
Within the State
$$
L^{n j, n k}=L_{I R S}^{n, n} \times \frac{L_{C P S}^{n j, n k}}{\sum_q \sum_h L_{C P S}^{n h, n q}} \quad \forall n \in U S A, \forall j, k
$$
Between States
$$
L^{n j, i k}=\frac{L_{A C S}^{n \#, i k}}{\sum_q L_{A C S}^{n \#, i q}} \times L_{I R S}^{n, i} \times \frac{L_{C P S}^{i j, i k}}{\sum_h L_{C P S}^{i h, i k}} \quad (n \neq i)
$$
```{r}
#loading intermediate CPS
cps <- read.csv(paste("1-Intermediate_Processed_Data//cps_2.csv", sep=""), header = TRUE, sep = ",", dec = ".")

#within states proportionality
temp_within  <- cps %>% 
  filter(state_ori == state_dest & year == 1999)  %>% 
  group_by(year, state_dest, state_ori)  %>% 
  mutate(n_cps_two_states_tot = sum(n_cps))  %>% 
  ungroup()  %>% 
  mutate(cps_share_wti = n_cps/n_cps_two_states_tot) %>% 
  select(year, state_ori, state_dest, sector_ori, sector_dest, cps_share_wti)

#between states proportionality
temp_between_cps  <- cps  %>% 
  filter(state_ori == state_dest & year == 1999)  %>% 
  group_by(year, state_dest, state_ori, sector_dest)  %>% 
  mutate(n_cps_same_sector_dest = sum(n_cps))  %>% 
  ungroup()  %>% 
  mutate(cps_share_btw = n_cps/n_cps_same_sector_dest)  %>% 
  select(year, state_ori, state_dest, sector_ori, sector_dest, cps_share_btw)

acs <- read.csv(paste("1-Intermediate_Processed_Data//acs.csv", sep=""), header = TRUE, sep = ",", dec = ".")

temp_between_acs  <-  acs  %>% 
  filter(year == 1999)  %>% 
  group_by(year, state_dest, state_ori)  %>% 
  mutate(n_acs_two_tot = sum(n_acs))  %>% 
  ungroup()  %>% 
  mutate(acs_share = n_acs/n_acs_two_tot)  %>% 
  mutate(acs_share = ifelse(is.na(acs_share), 0, acs_share))  %>% 
  select(year, state_ori, state_dest, sector_dest, acs_share)

mobility  <- cps  %>% 
  left_join(irs, by=c('year' = 'year', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori')) %>%
  left_join(temp_within, by = c('year' = 'year', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori', 'sector_dest' = 'sector_dest', 'sector_ori' = 'sector_ori'))  %>% 
  left_join(temp_between_acs, by = c('year' = 'year', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori', 'sector_dest' = 'sector_dest'))  %>% 
  left_join(temp_between_cps, by = c('year' = 'year', 'state_dest' = 'state_dest', 'sector_dest' = 'sector_dest', 'sector_ori' = 'sector_ori'))  %>% 
  rename(state_ori = state_ori.x)  %>% 
  mutate(n_cps_adj = exemption * acs_share * cps_share_btw)  %>% 
  mutate(n_cps_adj = ifelse(state_ori == state_dest, exemption*cps_share_wti, n_cps_adj))  %>% 
  select(-state_ori.y)

#mu_1999 prime for L_1999
#the second part of this calculation is in the next step since there is an additional proportionality that has to be implemented in L_2000 so that it is consistent with WIOD
mu_1999_prime <- mobility %>%
  group_by(year, state_dest, sector_dest) %>% 
  mutate(tot_n = sum(n_cps_adj)) %>% # total inflows to destination state-sector
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n) %>%  #(inflow share of destination state-sector across original state-sector)rel: share of people from original state-sector pairs to the same destination state-sector
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel)

write.table(mu_1999_prime, file = paste("1-Intermediate_Processed_Data/mu_1999_prime_irs_4.csv", sep=""), sep = ",", row.names = FALSE)


#mu_1999 prime for L_1999
mu_1999_prime <- read.csv(paste("1-Intermediate_Processed_Data/mu_1999_prime_irs_4.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars=c("state"), variable.name="sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector)))
mu_1999_prime <- mu_1999_prime %>%
  left_join(L_2000, by=c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%
  select(-rel, -employ)
write.table(mu_1999_prime, file = paste("1-Intermediate_Processed_Data//mu_1999_prime_irs_4.csv", sep=""), sep = ",", row.names = FALSE)


#Computing L_1999 using mobility matrices and L_2000
mu_1999_prime <- read.csv(paste("1-Intermediate_Processed_Data/mu_1999_prime_irs_4.csv", sep=""), header = TRUE, sep = ",", dec = ".")

L_1999 <- mu_1999_prime %>%
  group_by(state_ori, sector_ori) %>%
  mutate(employ = sum(level_employ)) %>%
  ungroup() %>%
  distinct(state_ori, sector_ori, .keep_all = TRUE) %>%
  dplyr::rename(state = state_ori, sector = sector_ori) %>%
  select(state, sector, employ) %>%
  arrange(state, sector)
temp_L_1999 <- L_1999
L_1999 <- spread(L_1999, sector, employ, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
write.table(L_1999, file = paste("1-Intermediate_Processed_Data/L_1999_irs_4.csv", sep=""), sep = ",", row.names = FALSE)
#Recalculating mu_1999 and checking flow 1999-2000
mu_1999 <- mu_1999_prime %>% 
  dplyr::rename(n_cps_adj_ = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj_)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj_/tot_n_cps_accros_dest) %>% 
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
mu_1999 <- mu_1999 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999 <- spread(mu_1999, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
#check sum(prob)==1
epsilon <- 0.01
check <- mu_1999 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999, path = paste("2-Final_Data//mu_1999_irs_4.xlsx", sep=""))

#check L_1999 and mu_1999 gives L_2000
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars=c("state"), variable.name="sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector))) %>%
  arrange(state, sector)
L_2000 <- as.matrix(L_2000$employ)
L_1999 <- as.matrix(temp_L_1999$employ)
mu_1999 <- mu_1999 %>% select(-year, -state_ori, -sector_ori)
mu_1999 <- as.matrix(mu_1999)
if(sum(L_2000 - (t(mu_1999)%*%L_1999)) > epsilon) 
  stop(paste("L_1999 and mu_1999 do NOT give L_2000"))




```


