---
title: "Quarterly migration matrix statistics"
author: "Yuanhang(Leo) Yu"
date: "2023-08-15"
output:
  html_document:
    toc: yes
    df_print: paged
  # pdf_document:
    # number_sections: yes
  # html_notebook:
    # toc: yes
    # df_print: paged
    # number_sections: yes
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{pifont}
- \usepackage{mathpazo}
---
```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list = ls())  
```

```{r message=FALSE, warning=FALSE, cache=FALSE, include=FALSE, results='hide'}
# Define function
`%notin%` <- Negate(`%in%`)
# libraries
options( scipen=100, digits = 15, stringsAsFactors=FALSE ); # no scientific notation, up to 15 digits 
# vector of libraries to be used
libs <- c( 'dplyr', 'tidyr', 'haven', 'stringr', 'nleqslv', 'gdata', 'formattable', 'ggplot2', 'viridis', 'RColorBrewer', 'reshape2', 'foreign', 'readxl', 'writexl', 'rjson', 'read_excel', 'Matrix', 'geodist', 'readr', 'data.table', 'stringr', 'haven');
# Install libraries in case they are not installed
for( i in seq_along(libs)){ 
    if( !(libs[i] %in% installed.packages()) ) install.packages( libs[i] ) 
};
# Loading libraries
lapply( libs, require, character.only=TRUE );
```

```{r additional data}
# region: US states and other countries
regions <- read.csv("0-Raw_Data/regions.csv")  
c_names <- regions %>% filter(status == "country")
c_names <- c_names$region

s_names <- regions %>% filter(status == "state") 
s_names <- s_names$region

# sector reclassification table (NAICS to final)
sectors_naics_final <- read.csv(paste("0-Raw_Data/sectors.csv", sep=""), header = TRUE, sep = ",", dec = ".")
sectors_naics_final <- sectors_naics_final %>% 
  select(final_sector, naics) %>%
  mutate(naics = as.character(naics)) %>%
  distinct(final_sector, naics)     #create the mapping table from NAICS to final at sector level

# sectors (CENSUS 1990 to final)
sectors_census1990_final <- read.csv(paste("0-Raw_Data/sectors_census_1990.csv", sep=""), header = TRUE, sep = ",", dec = ".")
sectors_census1990_final <- sectors_census1990_final %>%
  filter(is.na(final_sector) == FALSE) %>%
  mutate(census_1990 = as.character(census_1990)) %>%
  select(census_1990, final_sector)

# sectors (CENSUS 2003 to naics)
sectors_census2003_naics <- read.csv(paste("0-Raw_Data/sectors_census_2003.csv", sep=""), header = TRUE, sep = ",", dec = ".")
sectors_census2003_naics <- sectors_census2003_naics %>%
  mutate(naics = as.character(naics)) %>%
  distinct(census_2003, .keep_all = TRUE)

# sectors (CENSUS 2003 to final)
sectors_census2003_final <- sectors_census2003_naics %>%
  left_join(sectors_naics_final, by=c('naics'='naics')) %>% #NAICS to final sector
  filter(is.na(final_sector) == FALSE) %>%
  mutate(census_2003 = as.character(census_2003)) %>%
  select(census_2003, final_sector)

# state codes
states_fips <- read_excel("0-Raw_Data/Fips/states_fips_num.xlsx", range = "A1:D53")
states_fips_mod_ACS <- states_fips %>% 
  select(st_num, st_name) %>%
  mutate(st_num = ifelse(st_num > 8, st_num + 1, st_num)) %>%
  distinct(st_name, .keep_all = TRUE) %>%
  dplyr::rename(st_name1 = st_name)  #state code that is consistent with used in ACS
states_fips <- states_fips %>% select(st_fips, st_num, st_name)

```

### Compare quarterly migration matrix to CDP
```{r transition probablity at state level}
migration_1999_0  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_case0_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")
migration_1999_1  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_case1_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")
migration_1999_2  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_case2_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# Probability stay-in same state
suffixes <- c("0", "1", "2")     # Define a vector of suffixes for the data frames
prob_same_state_list <- list()   # Create an empty list to store the results
columns_to_suffix <- c("stay_in_state_share")

for (suffix in suffixes) {       # Loop over the suffixes and process the data frames
  current_df <- get(paste0("migration_1999_", suffix))
  
  current_same_state <- current_df %>%
    group_by(year, quarter, state_ori)  %>% 
    mutate(l_1999 = sum(level_employ))  %>% 
    mutate(num = sum(level_employ[state_ori == state_dest]))  %>% 
    ungroup()  %>% 
    mutate(stay_in_state_share = num/l_1999)  %>% 
    select(state_ori, quarter, stay_in_state_share)  %>% 
    distinct(state_ori, quarter, stay_in_state_share, .keep_all = TRUE)

  colnames(current_same_state)[colnames(current_same_state) %in% columns_to_suffix] <-
    paste0(colnames(current_same_state)[colnames(current_same_state) %in% columns_to_suffix], "_", suffix)
  
  prob_same_state_list[[suffix]] <- current_same_state
}

prob_same_state <- Reduce(function(x, y) left_join(x, y, by = c("state_ori","quarter")), prob_same_state_list)  # Merge the results into a single data frame
write_xlsx(prob_same_state, "1-Intermediate_Processed_Data/prob_same_state_quarterly(at state level).xlsx")

# Probability stay-in same sector for each original state
suffixes <- c("0", "1", "2")   # Define a vector of suffixes for the data frames
prob_same_sector_list <- list()   # Create an empty list to store the results
columns_to_suffix <- c("stay_in_sector_share")

for (suffix in suffixes) {     # Loop over the suffixes and process the data frames
  current_df <- get(paste0("migration_1999_", suffix))
  
  current_same_sector <- current_df %>%
    group_by(year, quarter, state_ori)  %>% 
    mutate(l_1999 = sum(level_employ))  %>% 
    mutate(num = sum(level_employ[sector_ori == sector_dest]))  %>% 
    ungroup()  %>% 
    mutate(stay_in_sector_share = num/l_1999)  %>% 
    select(state_ori, quarter, stay_in_sector_share)  %>% 
    distinct(state_ori, quarter, stay_in_sector_share, .keep_all = TRUE)

  colnames(current_same_sector)[colnames(current_same_sector) %in% columns_to_suffix] <-
    paste0(colnames(current_same_sector)[colnames(current_same_sector) %in% columns_to_suffix], "_", suffix)
  
  prob_same_sector_list[[suffix]] <- current_same_sector
}

prob_same_sector <- Reduce(function(x, y) left_join(x, y, by = c("state_ori", "quarter")), prob_same_sector_list)  # Merge the results into a single data frame
write_xlsx(prob_same_sector, "1-Intermediate_Processed_Data/prob_same_sector_quarterly(at state level).xlsx")


# Transition probability
prob_same_state_sector_0  <- migration_1999_0 %>% 
  group_by(year, quarter, state_ori)  %>% 
  mutate(l_1999 = sum(level_employ))  %>% 
  mutate(stay_in_num = sum(level_employ[state_ori == state_dest & sector_ori == sector_dest]))  %>% 
  ungroup()  %>% 
  mutate(same_state_sector_0 = stay_in_num/l_1999)  %>% 
  select(quarter, state_ori, same_state_sector_0)  %>% 
  distinct(quarter, state_ori, same_state_sector_0, .keep_all = TRUE)

prob_same_state_sector_1  <- migration_1999_1 %>% 
  group_by(year,quarter, state_ori)  %>% 
  mutate(l_1999 = sum(level_employ))  %>% 
  mutate(stay_in_num = sum(level_employ[state_ori == state_dest & sector_ori == sector_dest]))  %>% 
  ungroup()  %>% 
  mutate(same_state_sector_1 = stay_in_num/l_1999)  %>% 
  select(quarter, state_ori, same_state_sector_1)  %>% 
  distinct(quarter, state_ori, same_state_sector_1, .keep_all = TRUE)

prob_same_state_sector_2  <- migration_1999_2 %>% 
  group_by(year,quarter,  state_ori)  %>% 
  mutate(l_1999 = sum(level_employ))  %>% 
  mutate(stay_in_num = sum(level_employ[state_ori == state_dest & sector_ori == sector_dest]))  %>% 
  ungroup()  %>% 
  mutate(same_state_sector_2 = stay_in_num/l_1999)  %>% 
  select(quarter, state_ori, same_state_sector_2)  %>% 
  distinct(quarter, state_ori, same_state_sector_2, .keep_all = TRUE)

transition_prob  <- prob_same_state_sector_0  %>% 
  left_join(prob_same_state_sector_1, by = c('quarter' = 'quarter', 'state_ori' = 'state_ori'))  %>% 
  left_join(prob_same_state_sector_2, by = c('quarter' = 'quarter', 'state_ori' = 'state_ori')) 

transition_prob  <- transition_prob  %>% 
  left_join(prob_same_sector, by = c('quarter' = 'quarter', 'state_ori' = 'state_ori'))  

transition_prob  <- transition_prob  %>% 
  left_join(prob_same_state, by = c('quarter' = 'quarter', 'state_ori' = 'state_ori'))  

transition_prob  <- transition_prob  %>% 
  mutate(same_state_diff_sector_0 = stay_in_state_share_0 - same_state_sector_0)  %>% 
  mutate(same_state_diff_sector_1 = stay_in_state_share_1 - same_state_sector_1)  %>% 
  mutate(same_state_diff_sector_2 = stay_in_state_share_2 - same_state_sector_2)  %>% 
  mutate(diff_state_same_sector_0 = stay_in_sector_share_0 - same_state_sector_0)  %>% 
  mutate(diff_state_same_sector_1 = stay_in_sector_share_1 - same_state_sector_1)  %>% 
  mutate(diff_state_same_sector_2 = stay_in_sector_share_2 - same_state_sector_2)  %>% 
  select(state_ori, quarter, same_state_sector_0, same_state_sector_1, same_state_sector_2, same_state_diff_sector_0, same_state_diff_sector_1, same_state_diff_sector_2, diff_state_same_sector_0, diff_state_same_sector_1, diff_state_same_sector_2, stay_in_sector_share_0, stay_in_sector_share_1, stay_in_sector_share_2, stay_in_state_share_0, stay_in_state_share_1, stay_in_state_share_2)

colnames(transition_prob)   <- gsub("same_state_sector", "same_state_same_sector", colnames(transition_prob))
colnames(transition_prob)   <- gsub("same_state_diff_sector", "chg_sector_not_state", colnames(transition_prob))
colnames(transition_prob)   <- gsub("diff_state_same_sector", "chg_state_not_sector", colnames(transition_prob))

cols_to_multiply  <- 3:17
for (col in cols_to_multiply) {
  transition_prob[, col] <- transition_prob[, col] * 100
}
write_xlsx(transition_prob, "1-Intermediate_Processed_Data/transition_prob_quarterly(at state level).xlsx")

summary_pro  <- transition_prob  %>% 
  select(-state_ori, -quarter)  %>% 
  #group_by(quarter)  %>% 
  mutate(across(everything(), list(Mean = mean, Max = max, Min = min, p25 = ~quantile(.,probs = 0.25), p50 = ~quantile(.,probs = 0.50), p75 = ~quantile(.,probs = 0.75))))  %>% 
  #ungroup()  %>% 
  select(contains("Mean") | contains("Max") | contains("Min") | contains("p25") | contains("p50") | contains("p75"))  %>% 
  distinct()  

summary_pro <- summary_pro %>%
  pivot_longer(cols = everything(), 
               names_to = c("state_sector", ".value"), 
               names_sep = "_(?=Mean|Max|Min|p25|p50|p75)") 
write_xlsx(summary_pro, "1-Intermediate_Processed_Data/quarterly_summary_statistics(at state level).xlsx")

```

```{r transition probability at labour market level}
migration_1999_0  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_case0_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")
migration_1999_1  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_case1_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")
migration_1999_2  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_case2_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# Transition probability (at labour market level)
suffixes <- c("0", "1", "2")   # Define a vector of suffixes for the data frames
trans_list <- list()   # Create an empty list to store the results
columns_to_suffix <- c("same_sec_same_state", "chg_state_not_sec", "chg_sec_not_state", "chg_sec_chg_state")

for (suffix in suffixes) {    # Loop over the suffixes and process the data frames
  mobility_temp <- get(paste0("migration_1999_", suffix))
  
  current_df <- mobility_temp %>%
     group_by(year, quarter, state_ori, sector_ori)  %>% 
     mutate(l_1999 = sum(level_employ))  %>% 
     mutate(chg_state_not_sec = sum(level_employ[sector_ori == sector_dest & state_ori != state_dest]))  %>% 
     mutate(chg_sec_not_state = sum(level_employ[sector_ori != sector_dest & state_ori == state_dest]))  %>%
     mutate(chg_sec_chg_state = sum(level_employ[sector_ori != sector_dest & state_ori != state_dest]))  %>%
     mutate(same_sec_same_state = sum(level_employ[sector_ori == sector_dest & state_ori == state_dest]))  %>% 
     ungroup()  %>% 
     mutate(chg_state_not_sec = (chg_state_not_sec/l_1999)*100)  %>% 
     mutate(chg_sec_not_state = (chg_sec_not_state/l_1999)*100)  %>% 
     mutate(chg_sec_chg_state = (chg_sec_chg_state/l_1999)*100)  %>% 
     mutate(same_sec_same_state = (same_sec_same_state/l_1999)*100)  %>% 
     distinct(quarter, state_ori,sector_ori, .keep_all = TRUE)  %>% 
     select(state_ori, sector_ori, quarter,
            chg_state_not_sec, 
            chg_sec_not_state, 
            chg_sec_chg_state, 
            same_sec_same_state)

  colnames( current_df)[colnames( current_df) %in% columns_to_suffix] <-
    paste0(colnames( current_df)[colnames( current_df) %in% columns_to_suffix], "_", suffix)
  
  trans_list[[suffix]] <- current_df
}

transition_prob <- Reduce(function(x, y) left_join(x, y, by = c("state_ori", "sector_ori", "quarter")), trans_list)   # Merge the results into a single data frame
  

new_column_order <- c(
  "state_ori", "sector_ori", "quarter",
  unique(grep("same_sec_same_state_", colnames(transition_prob), value = TRUE)),
  unique(grep("chg_state_not_sec_", colnames(transition_prob), value = TRUE)),
  unique(grep("chg_sec_not_state_", colnames(transition_prob), value = TRUE)),
  unique(grep("chg_sec_chg_state_", colnames(transition_prob), value = TRUE))
)

# Reorder columns
transition_prob <- transition_prob %>%
  select(all_of(new_column_order)) %>% 
  group_by(state_ori, sector_ori)  %>%
  mutate(across(colnames(transition_prob)[4:15], mean))  %>% 
  ungroup()  %>% 
  distinct(state_ori, sector_ori,.keep_all = TRUE)
  
write_xlsx(transition_prob, "1-Intermediate_Processed_Data/transition_prob_quarterly(at state sector level).xlsx")

summary_pro  <- transition_prob  %>% 
  select(-state_ori, -sector_ori, -quarter)  %>% 
  mutate(across(everything(), list(Mean = mean, Max = max, Min = min, p25 = ~quantile(.,probs = 0.25), p50 = ~quantile(.,probs = 0.50), p75 = ~quantile(.,probs = 0.75))))  %>% 
  select(contains("Mean") | contains("Max") | contains("Min") | contains("p25") | contains("p50") | contains("p75"))  %>% 
  distinct()

summary_pro <- summary_pro %>%
  pivot_longer(cols = everything(), 
               names_to = c("state_sector", ".value"), 
               names_sep = "_(?=Mean|Max|Min|p25|p50|p75)") 
write_xlsx(summary_pro, "1-Intermediate_Processed_Data/summary_statistics_quarterly(at state sector level).xlsx")

# Histogram
transition_prob  %>% 
  ggplot() +
  geom_histogram(aes(x = same_sec_same_state_2))

transition_prob  %>% 
  ggplot() +
  geom_histogram(aes(x = same_sec_same_state_1))


```

```{r transition probability at labour market level no adjustment}
mobility_0  <- read.csv(file = paste("1-Intermediate_Processed_Data/mobility_case0_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")  %>% 
  filter(year == 1999)
mobility_1  <- read.csv(file = paste("1-Intermediate_Processed_Data/mobility_case1_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")  %>% 
  filter(year == 1999)
mobility_2  <- read.csv(file = paste("1-Intermediate_Processed_Data/mobility_case2_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")  %>% 
  filter(year == 1999)

# Transition probability (at labour market level)
suffixes <- c("0", "1", "2")   # Define a vector of suffixes for the data frames
trans_list <- list()   # Create an empty list to store the results
columns_to_suffix <- c("same_sec_same_state", "chg_state_not_sec", "chg_sec_not_state", "chg_sec_chg_state")

for (suffix in suffixes) {    # Loop over the suffixes and process the data frames
  mobility_temp <- get(paste0("mobility_", suffix))
  
  current_df <- mobility_temp %>%
     group_by(year, quarter, state_ori, sector_ori)  %>% 
     mutate(l_1999 = sum(n_cps_adj))  %>% 
     mutate(chg_state_not_sec = sum(n_cps_adj[sector_ori == sector_dest & state_ori != state_dest]))  %>% 
     mutate(chg_sec_not_state = sum(n_cps_adj[sector_ori != sector_dest & state_ori == state_dest]))  %>%
     mutate(chg_sec_chg_state = sum(n_cps_adj[sector_ori != sector_dest & state_ori != state_dest]))  %>%
     mutate(same_sec_same_state = sum(n_cps_adj[sector_ori == sector_dest & state_ori == state_dest]))  %>% 
     ungroup()  %>% 
     mutate(chg_state_not_sec = (chg_state_not_sec/l_1999)*100)  %>% 
     mutate(chg_sec_not_state = (chg_sec_not_state/l_1999)*100)  %>% 
     mutate(chg_sec_chg_state = (chg_sec_chg_state/l_1999)*100)  %>% 
     mutate(same_sec_same_state = (same_sec_same_state/l_1999)*100)  %>% 
     distinct(quarter, state_ori,sector_ori, .keep_all = TRUE)  %>% 
     select(state_ori, sector_ori, quarter,
            chg_state_not_sec, 
            chg_sec_not_state, 
            chg_sec_chg_state, 
            same_sec_same_state)

  colnames( current_df)[colnames( current_df) %in% columns_to_suffix] <-
    paste0(colnames( current_df)[colnames( current_df) %in% columns_to_suffix], "_", suffix)
  
  trans_list[[suffix]] <- current_df
}

transition_prob_no_adj <- Reduce(function(x, y) left_join(x, y, by = c("state_ori", "sector_ori", "quarter")), trans_list)  # Merge the results into a single data frame

new_column_order <- c(
  "state_ori", "sector_ori", "quarter",
  unique(grep("same_sec_same_state_", colnames(transition_prob), value = TRUE)),
  unique(grep("chg_state_not_sec_", colnames(transition_prob), value = TRUE)),
  unique(grep("chg_sec_not_state_", colnames(transition_prob), value = TRUE)),
  unique(grep("chg_sec_chg_state_", colnames(transition_prob), value = TRUE))
)

# Reorder columns
transition_prob_no_adj <- transition_prob_no_adj %>%
  select(all_of(new_column_order))  %>%  
  group_by(state_ori, sector_ori)  %>%
  mutate(across(colnames(transition_prob_no_adj)[4:15], mean))  %>% 
  ungroup()  %>% 
  distinct(state_ori, sector_ori,.keep_all = TRUE)

write_xlsx(transition_prob_no_adj, "1-Intermediate_Processed_Data/transition_prob_no_adj_quarterly(at state sector level).xlsx")

summary_pro_no_adj  <- transition_prob_no_adj  %>% 
  select(-state_ori, -sector_ori, -quarter)  %>% 
  mutate(across(everything(), list(Mean = mean, Max = max, Min = min, p25 = ~quantile(.,probs = 0.25), p50 = ~quantile(.,probs = 0.50), p75 = ~quantile(.,probs = 0.75))))  %>% 
  select(contains("Mean") | contains("Max") | contains("Min") | contains("p25") | contains("p50") | contains("p75"))  %>% 
  distinct()

summary_pro_no_adj <- summary_pro_no_adj %>%
  pivot_longer(cols = everything(), 
               names_to = c("state_sector", ".value"), 
               names_sep = "_(?=Mean|Max|Min|p25|p50|p75)") 
write_xlsx(summary_pro, "1-Intermediate_Processed_Data/summary_statistics_no_adj_quarterly(at state sector level).xlsx")

column <- transition_prob$chg_state_not_sec_2
cat("Mean:", mean(column), "\n")
cat("Maximum:", max(column), "\n")
cat("Minimum:", min(column), "\n")
cat("25th Percentile:", quantile(column, 0.25), "\n")
cat("50th Percentile (Median):", median(column), "\n")
cat("75th Percentile:", quantile(column, 0.75), "\n")

# Histogram
transition_prob_no_adj  %>% 
  ggplot() +
  geom_histogram(aes(x = same_sec_same_state_1))

```

### Annualised migration matrix
```{r}
mu_1999_annualise_long_0  <- mu_1999_annualise_long_0  
mu_1999_annualise_long_1  <- mu_1999_annualise_long_1 
mu_1999_annualise_long_2  <- mu_1999_annualise_long_2 

mu_1999_annualise_long_2_test  <- mu_1999_annualise_long_2[mu_1999_annualise_long_2$sector_dest == mu_1999_annualise_long_2$sector_ori & mu_1999_annualise_long_2$state_dest == mu_1999_annualise_long_2$state_ori ,]

column <-mu_1999_annualise_long_2_test$rel
cat("Mean:", mean(column), "\n")
cat("Maximum:", max(column), "\n")
cat("Minimum:", min(column), "\n")
cat("25th Percentile:", quantile(column, 0.25), "\n")
cat("50th Percentile (Median):", median(column), "\n")
cat("75th Percentile:", quantile(column, 0.75), "\n")


```

### Checks
```{r}
# Does the migration shares differ a lot across quarters?
mu_long_format_quarter_case2  <- mu_long_format_quarter_case2  %>% 
  arrange(year, state_ori, state_dest, sector_ori, sector_dest, quarter)  %>% 
  group_by(year, state_ori, state_dest, sector_ori, sector_dest)  %>% 
  mutate(diff_q = rel - lag(rel))  %>% 
  mutate(diff_q_ab = abs(diff_q))  %>% 
  ungroup()

mu_long_format_quarter_case2_sub  <- mu_long_format_quarter_case2  %>% 
  arrange(desc(diff_q_ab))  %>% 
  filter(diff_q_ab > 0.01)
write_csv(mu_long_format_quarter_case2_sub, "1-Intermediate_Processed_Data/migration_share_diff_case2.csv")

mu_long_format_quarter_case2_test  <- mu_long_format_quarter_case2[mu_long_format_quarter_case2$quarter == 4 & mu_long_format_quarter_case2$sector_dest == mu_long_format_quarter_case2$sector_ori & mu_long_format_quarter_case2$state_dest == mu_long_format_quarter_case2$state_ori ,]

column <- mu_long_format_quarter_case2_test$rel
cat("Mean:", mean(column), "\n")
cat("Maximum:", max(column), "\n")
cat("Minimum:", min(column), "\n")
cat("25th Percentile:", quantile(column, 0.25), "\n")
cat("50th Percentile (Median):", median(column), "\n")
cat("75th Percentile:", quantile(column, 0.75), "\n")

mu_long_format_quarter_case1  <- mu_long_format_quarter_case1  %>% 
  arrange(year, state_ori, state_dest, sector_ori, sector_dest, quarter)  %>% 
  group_by(year, state_ori, state_dest, sector_ori, sector_dest)  %>% 
  mutate(diff_q = rel - lag(rel))  %>% 
  mutate(diff_q_ab = abs(diff_q))  %>% 
  ungroup()

# Does recalculation make difference?
mu_long_format_quarter_no_adj_case2  <- mu_long_format_quarter_no_adj_case2  %>% 
  arrange(year, state_ori, state_dest, sector_ori, sector_dest, quarter)  %>% 
  group_by(year, state_ori, state_dest, sector_ori, sector_dest)  %>% 
  mutate(diff_q = mu - lag(mu))  %>% 
  mutate(diff_q_ab = abs(diff_q))  %>% 
  ungroup()


mu_long_format_quarter_no_adj_case1  <- mu_long_format_quarter_no_adj_case1  %>% 
  arrange(year, state_ori, state_dest, sector_ori, sector_dest, quarter)  %>% 
  group_by(year, state_ori, state_dest, sector_ori, sector_dest)  %>% 
  mutate(diff_q = mu - lag(mu))  %>% 
  mutate(diff_q_ab = abs(diff_q))  %>% 
  ungroup()

# Sectoral mobility 
migration_1999_0  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_case0_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")
migration_1999_1  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_case1_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")
migration_1999_2  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_case2_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

migration_1999_1_same_state  <- migration_1999_1  %>% 
  group_by(year, quarter, state_ori, sector_ori)  %>% 
  mutate(l_1999 = sum(level_employ))  %>% 
  mutate(ouflow_share = level_employ/l_1999)  %>% 
  ungroup()  %>% 
  mutate(flag = ifelse(state_dest == state_ori, 1 , 0))  %>% 
  group_by(year, quarter, state_ori, sector_ori, flag)  %>% 
  mutate(outflow_share_ave = mean(ouflow_share))  %>% 
  ungroup()  %>% 
  mutate(flag = ifelse(sector_ori == sector_dest, 1, 0))


```


### Aside: Calculating the changing state prob from ACS and changing sector from CPS, quarterly and annually

```{r}
# calculate the changing state probability with quarterly ACS
acs <- read.csv(paste("1-Intermediate_Processed_Data/acs_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")
acs_final_temp  <- acs  %>% 
  group_by(quarter, state_ori)  %>% 
  mutate(tot = sum(n))  %>%  # use n or n_acs (rolling-window value)
  ungroup()  %>% 
  mutate(flag = ifelse(state_ori == state_dest, 1, 0))  %>% 
  group_by(quarter, state_ori, flag)  %>% 
  mutate(tot_flag = sum(n))   %>% 
  mutate(ratio = (tot_flag/tot)*100 )  %>% 
  filter(state_ori == state_dest)  %>% 
  mutate(ratio_ = 100 - ratio)  %>% 
  distinct(state_ori, state_dest, .keep_all = TRUE)
  
column <-  acs_final_temp$ratio_[acs_final_temp$quarter == 1]    # rolling-window value has higher probability here
cat("Mean:", mean(column), "\n")
cat("Maximum:", max(column), "\n")
cat("Minimum:", min(column), "\n")
cat("25th Percentile:", quantile(column, 0.25), "\n")
cat("50th Percentile (Median):", median(column), "\n")
cat("75th Percentile:", quantile(column, 0.75), "\n")

# calculate the changing state probability with annual ACS
acs <- read.csv(paste("1-Intermediate_Processed_Data/acs.csv", sep=""), header = TRUE, sep = ",", dec = ".")
acs_final_temp  <- acs  %>% 
  filter(year == 1999)  %>% 
  group_by(state_ori)  %>% 
  mutate(tot = sum(n_acs))  %>%  # use n or n_acs (rolling-window value)
  ungroup()  %>% 
  mutate(flag = ifelse(state_ori == state_dest, 1, 0))  %>% 
  group_by(state_ori, flag)  %>% 
  mutate(tot_flag = sum(n_acs))   %>% 
  mutate(ratio = (tot_flag/tot)*100 )  %>% 
  filter(state_ori == state_dest)  %>% 
  mutate(ratio_ = 100 - ratio)  %>% 
  distinct(state_ori, state_dest, .keep_all = TRUE)
  
column <-  acs_final_temp$ratio_    # rolling-window value has higher probability here
cat("Mean:", mean(column), "\n")
cat("Maximum:", max(column), "\n")
cat("Minimum:", min(column), "\n")
cat("25th Percentile:", quantile(column, 0.25), "\n")
cat("50th Percentile (Median):", median(column), "\n")
cat("75th Percentile:", quantile(column, 0.75), "\n")

# calculate the changing sector probability with quarterly CPS
cps <- read.csv(paste("1-Intermediate_Processed_Data/cps_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")
cps  <- cps  %>% 
  filter(year == 1999 & state_dest == state_ori)  
cps_temp  <- cps  %>% 
    group_by(quarter, state_ori)  %>% 
    mutate(tot = sum(n_cps))  %>% 
    ungroup()  %>% 
    mutate(flag = ifelse(sector_ori == sector_dest, 1, 0))  %>% 
    group_by(quarter, state_ori, flag)  %>% 
    mutate(tot_flag = sum(n_cps))   %>% 
    mutate(ratio = (tot_flag/tot)*100 )  %>% 
    filter(sector_ori == sector_dest)  %>% 
    mutate(ratio_ = 100 - ratio)  %>% 
    distinct(state_ori, quarter, .keep_all = TRUE)
  
column <- cps_temp$ratio_
cat("Mean:", mean(column), "\n")
cat("Maximum:", max(column), "\n")
cat("Minimum:", min(column), "\n")
cat("25th Percentile:", quantile(column, 0.25), "\n")
cat("50th Percentile (Median):", median(column), "\n")
cat("75th Percentile:", quantile(column, 0.75), "\n")

# calculate the changing sector probability with annual CPS
cps <- read.csv(paste("1-Intermediate_Processed_Data/cps_2.csv", sep=""), header = TRUE, sep = ",", dec = ".")
cps  <- cps  %>% 
  filter(year == 1999 & state_dest == state_ori)  
cps_temp  <- cps  %>% 
    group_by(state_ori)  %>% 
    mutate(tot = sum(n_cps))  %>% 
    ungroup()  %>% 
    mutate(flag = ifelse(sector_ori == sector_dest, 1, 0))  %>% 
    group_by(state_ori, flag)  %>% 
    mutate(tot_flag = sum(n_cps))   %>% 
    mutate(ratio = (tot_flag/tot)*100 )  %>% 
    filter(sector_ori == sector_dest)  %>% 
    mutate(ratio_ = 100 - ratio)  %>% 
    distinct(state_ori, .keep_all = TRUE)
  
column <- cps_temp$ratio_
cat("Mean:", mean(column), "\n")
cat("Maximum:", max(column), "\n")
cat("Minimum:", min(column), "\n")
cat("25th Percentile:", quantile(column, 0.25), "\n")
cat("50th Percentile (Median):", median(column), "\n")
cat("75th Percentile:", quantile(column, 0.75), "\n")



mu_1999_prime_temp  <- migration_1999_0  %>% 
  group_by(year, state_ori)  %>% 
  mutate(l_1999 = sum(level_employ))  %>% 
  mutate(chg_state_not_sec_0 = sum(level_employ[sector_ori == sector_dest & state_ori != state_dest]))  %>% 
  mutate(chg_sec_not_state_0 = sum(level_employ[sector_ori != sector_dest & state_ori == state_dest]))  %>%
  mutate(chg_sec_chg_state_0 = sum(level_employ[sector_ori != sector_dest & state_ori != state_dest]))  %>%
  mutate(same_sec_same_state_0 = sum(level_employ[sector_ori == sector_dest & state_ori == state_dest]))  %>% 
  ungroup()  %>% 
  mutate(chg_state_not_sec = (chg_state_not_sec/l_1999)*100)  %>% 
  mutate(chg_sec_not_state = (chg_sec_not_state/l_1999)*100)  %>% 
  mutate(chg_sec_chg_state = (chg_sec_chg_state/l_1999)*100)  %>% 
  mutate(same_sec_same_state = (same_sec_same_state/l_1999)*100)  %>% 
  distinct(quarter, state_ori, .keep_all = TRUE)  %>% 
  select(state_ori, 
         chg_state_not_sec, 
         chg_sec_not_state, 
         chg_sec_chg_state, 
         same_sec_same_state)  

column <- mu_1999_prime_temp$chg_sec_not_state_share_0
cat("Mean:", mean(column), "\n")
cat("Maximum:", max(column), "\n")
cat("Minimum:", min(column), "\n")
cat("25th Percentile:", quantile(column, 0.25), "\n")
cat("50th Percentile (Median):", median(column), "\n")
cat("75th Percentile:", quantile(column, 0.75), "\n")


```






