---
title: "CPS NBER"
author: "Yuanhang(Leo) Yu"
date: "2023-09-10"
output:
  html_document:
    toc: yes
    df_print: paged
  # pdf_document:
    # number_sections: yes
  # html_notebook:
    # toc: yes
    # df_print: paged
    # number_sections: yes
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{pifont}
- \usepackage{mathpazo}
---

```{r clean-up, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list = ls())  
```

```{r set-up, message=FALSE, warning=FALSE, cache=FALSE, include=FALSE, results='hide'}
# Define function
`%notin%` <- Negate(`%in%`)
# libraries
options( scipen=100, digits = 15, stringsAsFactors=FALSE ); # no scientific notation, up to 15 digits 
# vector of libraries to be used
libs <- c( 'dplyr', 'tidyr', 'haven', 'stringr', 'nleqslv', 'gdata', 'formattable', 'ggplot2', 'viridis', 'RColorBrewer', 'reshape2', 'foreign', 'readxl', 'writexl', 'rjson', 'read_excel', 'Matrix', 'geodist', 'readr', 'data.table', 'stringr', 'haven');
# Install libraries in case they are not installed
for( i in seq_along(libs)){ 
    if( !(libs[i] %in% installed.packages()) ) install.packages( libs[i] ) 
};
# Loading libraries
lapply( libs, require, character.only=TRUE );

```

```{r additional data}
# region: US states and other countries
regions <- read.csv("0-Raw_Data/regions.csv")  
c_names <- regions %>% filter(status == "country")
c_names <- c_names$region

s_names <- regions %>% filter(status == "state") 
s_names <- s_names$region

# state codes
states_fips <- read_excel("0-Raw_Data/Fips/states_fips_num.xlsx", range = "A1:D53")
states_fips_mod_ACS <- states_fips %>% 
  select(st_num, st_name) %>%
  mutate(st_num = ifelse(st_num > 8, st_num + 1, st_num)) %>%
  distinct(st_name, .keep_all = TRUE) %>%
  dplyr::rename(st_name1 = st_name)  #state code that is consistent with used in ACS
states_fips <- states_fips %>% select(st_fips, st_num, st_name)

```

```{r Generate cps_nber_2_yearly}
# load CPS data from NBER
cps_nber  <- haven::read_dta("/Users/yyh/Library/CloudStorage/OneDrive-LondonSchoolofEconomics/RUV_data_no_GitHub/CPS_redone/Outputs/clean_data_new.dta")
cps_nber <- cps_nber %>%
  group_by(P_ID) %>%
  filter( min(inter_num) <=4 & max(inter_num) >=5 ) %>%
  ungroup()
write_csv(cps_nber, file = paste("1-Intermediate_Processed_Data/cps_nber_yearly.xlsx", sep = ""))

cps_nber  <- read.csv("1-Intermediate_Processed_Data/cps_nber_yearly.xlsx")
mn_list <- c("jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec")

# matching persons via same month in consecutive years based on H_ID and P_ID
# keep one observation
##base <- c()
##for (yr in 1997:2002) {
##for (mn in mn_list) {
### print(yr)
### print(mn)
##temp_cps_nber <- cps_nber %>%
##  filter(month == mn & ( (year == yr & inter_num==5) | (year == yr-1 & inter_num==1) ))
##
##info_present <- temp_cps_nber %>% 
##  filter(year == yr) %>%
##  dplyr::rename(sector_dest = sector, state_dest = st_name)
##info_past <- temp_cps_nber %>%
##  filter(year == yr-1) %>%
##  select(-year, -month, -wtfinl) %>% 
##  dplyr::rename(sector_ori = sector, state_ori = st_name)
##temp <- full_join(info_present, info_past, by=c("P_ID")) # after matching, get state info for t and t-1 from CPS
##temp <- temp %>%
##  filter(is.na(state_ori) == FALSE & is.na(state_dest) == FALSE) %>% # only matches
##  distinct( P_ID, .keep_all = TRUE)
##base <- rbind(base, temp)
##}
##}

# keep two observations
base <- c()
for (yr in 1997:2002) {
for (mn in mn_list) {
# print(yr)
# print(mn)
temp_cps_nber <- cps_nber %>%
  filter(month == mn & ( (year == yr & inter_num==5) | (year == yr-1 & inter_num==1) | (year == yr & inter_num==6) | (year == yr-1 & inter_num==2))) 

info_present <- temp_cps_nber %>% 
  filter(year == yr) %>%
  dplyr::rename(sector_dest = sector, state_dest = st_name)
info_past <- temp_cps_nber %>%
  filter(year == yr-1) %>%
  select(-year, -month, -wtfinl) %>% 
  dplyr::rename(sector_ori = sector, state_ori = st_name)
temp <- full_join(info_present, info_past, by=c("P_ID"))  %>%  # after matching, get state info for t and t-1 from CPS
        filter(inter_num.x - inter_num.y == 4) 
temp <- temp %>%
  filter(is.na(state_ori) == FALSE & is.na(state_dest) == FALSE) %>% # only matches
  distinct( P_ID, .keep_all = TRUE)
base <- rbind(base, temp)
}
}


#base  <- base  %>% 
#  group_by(P_ID, year, month)  %>% 
#  mutate(n = n())

# rolling basis: five-year window
final_base <- c()
for (yr in 1997:2002) {
temp <- base %>%
  filter(year >= yr - 2 & year <= yr + 2) %>% 
  mutate(year = yr)
final_base <- rbind(final_base, temp)
}
base <- final_base %>% 
  mutate(year = year - 1)   # the original year is the year of the survey at the present; minus one gives the year of survey at the start


# counting sector-sector within state movements
base <- base %>%
  select(-month, -P_ID, -inter_num.x, -inter_num.y, -st_fips.x, -st_fips.y) %>%
  group_by(year, state_ori, sector_ori, state_dest, sector_dest) %>%
  mutate(n_cps = sum(wtfinl)) %>%
  ungroup() %>%
  group_by(year, state_ori, sector_ori) %>%
  mutate(n_sample = n()) %>%
  ungroup() %>%
  distinct(year, state_ori, sector_ori, state_dest, sector_dest, .keep_all = TRUE) %>%
  select(year, state_ori, sector_ori, state_dest, sector_dest, n_cps, n_sample)

##base  %>% 
##  filter(year == 1999)  %>% 
##  filter(n_sample < 10)  %>% 
##  ggplot() +
##  geom_point(aes(x = sector_ori, y = n_sample, color = state_ori))
##
base_temp  <- base  %>% 
  filter(year == 1999)  %>% 
  filter(n_sample < 10)  %>% 
  mutate(name = paste(state_ori, sector_ori))  %>% 
  arrange(state_ori, sector_ori)

unique(base_temp$name)     # list of dropped cases: 72 (state_ori, sector_ori)

base  %>% 
  filter(year == 1999)  %>% 
  select(n_sample)  %>% 
  summary()    # 1st quntile 37; Median 95; Mean: 824; 3rd quntile 390
#base_before_drop  <- base  %>% 
#  arrange(year, state_ori, sector_ori)
base  <- base  %>% 
  filter(n_sample >= 10)  # 224 observations dropped

# adding missing combinations
temp <- data.frame(s_names)
sec  <- c(0:14)
temp_sec  <- data.frame(sec)
yr  <- c(1998:2001)
temp_yr  <- data.frame(yr)
combo_st_sec  <- expand.grid(year = temp_yr$yr,state_ori = temp$s_names, sector_ori = temp_sec$sec, state_dest = temp$s_names, sector_dest = temp_sec$sec)

cps_nber  <- combo_st_sec  %>% 
  left_join(base, by = c('year', 'state_dest', 'state_ori','sector_dest','sector_ori'))  %>% 
  mutate(n_cps = ifelse(is.na(n_cps), 0, n_cps))

before  <-  cps_nber
cps_nber_  <- cps_nber
############################ Modification: proportionality assumption on diagonals ##################################
# replacing 0 in diag based on median non-zero diag shares within year-sector
temp <- cps_nber  %>% 
  mutate(diag = ifelse(sector_ori == sector_dest & state_ori == state_dest, 1, 0))  %>% 
  group_by(year, state_ori, sector_ori)  %>% 
  mutate(stock_ori = sum(n_cps))  %>%  # the sum of people at origin; under restriction, there are many zeros
  mutate(outflow_share = n_cps/stock_ori)  %>% # share of outflow
  mutate(outflow_share = ifelse(is.na(outflow_share), 0, outflow_share))  %>% 
  mutate(stay_in_share = ifelse(diag == 1, outflow_share, 0))  %>%  # there is no stay-in share for those (state_ori, sector_ori) dropped under restriction
  mutate(stay_in_share = max(stay_in_share))  %>% # no NA; minimum 0.44
  ungroup() %>% 
  group_by(year, sector_ori)  %>% 
  mutate(stay_in_share_median = median(stay_in_share))  %>%  # no NA; minimum 0.44
  ungroup()  %>% 
  group_by(year, state_dest, sector_dest)  %>% 
  mutate(stock_dest = sum(n_cps))  %>%  # the sum of people at destination
  mutate(stock_dest_diag = ifelse(diag == 1, stock_dest, 0))  %>% 
  ungroup()  %>% 
  group_by(year, state_ori, sector_ori)  %>% 
  mutate(stock_dest_diag = max(stock_dest_diag))  %>% # repeating the stock_dest_diag within each (state_ori, sector_ori)
  ungroup()  %>% 
  group_by(year, sector_ori)  %>% 
  mutate(stock_dest_diag_min = min(stock_dest_diag[stock_dest_diag > 0]))  %>%   
  ungroup()  %>% 
  mutate(diag_new = ifelse(stay_in_share_median == 1, pmax(stock_dest_diag_min, stock_ori, stock_dest_diag),  pmax(stock_dest_diag_min, stock_ori, stock_dest_diag)/(1-stay_in_share_median) * stay_in_share_median))  %>% 
  #mutate(diag_new = ifelse(stay_in_share_median == 1, pmax(1, stock_ori, stock_dest_diag),  pmax(1, stock_ori, stock_dest_diag)/(1-stay_in_share_median) * stay_in_share_median))  %>% 
  #mutate(diag_new = pmax(1, stock_ori, stock_dest_diag)/(1-stay_in_share_median) * stay_in_share_median)  %>%  # 709 cases takes the value of 1 in all quarter in 1999
  #mutate(diag_new = pmax(1, stock_ori, stock_dest_diag)/(1-stay_in_share_median) * stay_in_share_median)  %>%  # 9 cases stock_ori = stock_dest_diag = 0: Alaska 9/6, Hawaii 6/5/10, Wyoming 6, Georgia 4, Rhodes 4, Montana 11  
  mutate(flag = ifelse(diag == 1 & n_cps == 0, 1, 0))  %>%  #82 cases in 1999
  mutate(n_cps = ifelse(diag == 1 & n_cps == 0, diag_new, n_cps))  %>% 
  select(year, state_ori, sector_ori, state_dest, sector_dest, n_cps) 
cps_nber  <- temp



#filling missing matrix sections as CDP
cps_nber <- cps_nber %>%
  mutate(n_master = ifelse(state_ori == state_dest, n_cps, 0)) %>%
  select(-n_cps) %>%   #actually, n_master == n_cps......
  group_by(year, state_dest, sector_dest, sector_ori) %>% #based on destination state
  mutate(n_cps = max(n_master)) %>%  #n_cps:  each entry takes the value of within destination state migration for that sector-sector movement, therefore same value for same (year, state_dest, sector_dest, sector_ori) across original states
  ungroup() %>%
  select(-n_master) %>%
  arrange(year, state_dest, sector_dest, state_ori, sector_ori)

write.table(cps_nber, file = paste("1-Intermediate_Processed_Data/cps_nber_2_yearly.csv", sep=""), sep = ",", row.names = FALSE) 

############################ Old code without modification ##################################
# replacing 0 in diag for min non-zero diag value
temp <- cps_nber_ %>%
  mutate(diag = ifelse(sector_ori == sector_dest & state_ori == state_dest, 1, 0)) %>%
  filter(diag == 1 & n_cps != 0) %>%
  group_by(year, diag) %>%
  mutate(min_diag = min(n_cps)) %>% #min non-zero diag value within the same year across all diagonals
  ungroup() %>%
  distinct(year, .keep_all = TRUE) %>%
  select(year, min_diag)  #year 1999, 2000, 2001, the minimum is 264.8371; year 2002, the minimum is 277.1613; year 2003, 2004, 2005, 2006, the minimum is 230.9756. 
cps_nber_ <- cps_nber_ %>%
  left_join(temp, by=c("year"="year")) %>%
  mutate(diag = ifelse(sector_ori == sector_dest & state_ori == state_dest, 1, 0)) %>%
  mutate(n_cps = ifelse(diag == 1 & n_cps == 0 , min_diag, n_cps)) %>% #108 cases
  select(-min_diag, -diag) # n_cps: only have within state movements sector-sector migration flows (all diag missing are filled), across state equals zero
rm(temp)

# filling missing matrix sections as CDP
cps_nber_ <- cps_nber_ %>%
  mutate(n_master = ifelse(state_ori == state_dest, n_cps, 0)) %>%
  select(-n_cps) %>%   #actually, n_master == n_cps......
  group_by(year, state_dest, sector_dest, sector_ori) %>% #based on destination state
  mutate(n_cps = max(n_master)) %>%  #n_cps:  each entry takes the value of within destination state migration for that sector movement, therefore same value for same (state_dest, sector_dest)
  ungroup() %>%
  select(-n_master) %>%
  arrange(year, state_dest, sector_dest, state_ori, sector_ori)
write.table(cps_nber_, file = paste("1-Intermediate_Processed_Data/cps_nber_2_case0_yearly.csv", sep=""), sep = ",", row.names = FALSE) 
# generate this file in order to reproduce the very original matrix without modification for comparison later



```

```{r yearly matrix case}
#### Case 0 ####
# loading intermediate CPS
cps <- read.csv(paste("1-Intermediate_Processed_Data/cps_nber_2_case0_yearly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# loading intermediate ACS
acs <- read.csv(paste("1-Intermediate_Processed_Data/acs.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# Mobility matrices
# disaggregating ACS data using CPS sector_ori info and computation of mobility share
# origin in rows and destination in columns
# row shares sum to 1
acs <- acs %>%
  group_by(year, state_ori, state_dest) %>%
  mutate(n_acs = sum(n_acs)) %>% # n_acs: for (state_ori, state_dest) pair, n_acs is the total migration summed over all destination sectors
  ungroup() %>%
  distinct(year, state_ori, state_dest, .keep_all = TRUE) %>%
  select(-sector_dest)  # total migration from state i to state j for each (i,j) combination

# adjusting x's to y's: cps migration pair share times total migration from acs
mobility <- cps %>%
  left_join(acs, by=c('year' = 'year', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori')) %>%
  group_by(year, state_dest, state_ori) %>% 
  mutate(tot_n_cps_accros_sec = sum(n_cps)) %>% # totol within destination state migration (sum over all sector movements)
  ungroup() %>%
  mutate(n_cps_adj = n_cps/tot_n_cps_accros_sec) %>% # migration share across sectors within state (based on destination state)
  mutate(n_cps_adj = ifelse(is.na(n_cps_adj) == TRUE, 0, n_cps_adj)) %>%
  mutate(n_cps_adj = n_cps_adj*n_acs) %>% # use cps within-state across sector migration share times acs total migration across states
  select(-tot_n_cps_accros_sec, -n_cps, -n_acs) 

# mu_1999 prime for L_1999
# the second part of this calculation is in the next step since there is an additional proportionality that has to be implemented in L_2000 so that it is consistent with WIOD
mu_1999_prime <- mobility %>%
  filter(year == 1999) %>%
  group_by(year, state_dest, sector_dest) %>% 
  mutate(tot_n = sum(n_cps_adj)) %>% # total inflows to destination state-sector
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n) %>%  # (inflow share of destination state-sector across original state-sector)rel: share of people from original state-sector pairs to the same destination state-sector
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel)

# mu_1999 prime for L_1999
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars = c("state"), variable.name = "sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector)))
mu_1999_prime <- mu_1999_prime %>%
  left_join(L_2000, by=c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)
write.table(mu_1999_prime, file = paste("1-Intermediate_Processed_Data/mu_1999_prime_nber_case0_yearly.csv", sep=""), sep = ",", row.names = FALSE)

# Computing L_1999 using mobility matrices and L_2000
L_1999 <- mu_1999_prime %>%
  group_by(state_ori, sector_ori) %>%
  mutate(employ = sum(level_employ)) %>%  # 1999 labour distribution
  ungroup() %>%
  distinct(state_ori, sector_ori, .keep_all = TRUE) %>%
  dplyr::rename(state = state_ori, sector = sector_ori) %>%
  select(state, sector, employ) %>%
  arrange(state, sector)
temp_L_1999 <- L_1999
L_1999 <- spread(L_1999, sector, employ, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)

# Recalculating mu_1999 and checking flow 1999-2000
mu_1999 <- mu_1999_prime %>% 
  dplyr::rename(n_cps_adj_ = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj_)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj_/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
write_xlsx(mu_1999, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case0_long_format_yearly.xlsx", sep=""))
mu_1999 <- mu_1999 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999 <- spread(mu_1999, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)

# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999, path = paste("2-Final_Data/mu_1999_nber_case0_yearly.xlsx", sep=""))

# check L_1999 and mu_1999 gives L_2000
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars=c("state"), variable.name="sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector))) %>%
  arrange(state, sector)
L_2000 <- as.matrix(L_2000$employ)
L_1999 <- as.matrix(temp_L_1999$employ)
mu_1999 <- mu_1999 %>% select(-year, -state_ori, -sector_ori)
mu_1999 <- as.matrix(mu_1999)
if(sum(L_2000 - (t(mu_1999)%*%L_1999)) > epsilon) 
  stop(paste("L_1999 and mu_1999 do NOT give L_2000"))

#### Case 1 ####
# loading intermediate CPS
cps_nber <- read.csv(paste("1-Intermediate_Processed_Data/cps_nber_2_yearly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# loading intermediate ACS
acs <- read.csv(paste("1-Intermediate_Processed_Data/acs.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# Mobility matrices
# disaggregating ACS data using CPS sector_ori info and computation of mobility share
# origin in rows and destination in columns
# row shares sum to 1
acs <- acs %>%
  group_by(year, state_ori, state_dest) %>%
  mutate(n_acs = sum(n_acs)) %>% # n_acs: for (state_ori, state_dest) pair, n_acs is the total migration summed over all destination sectors
  ungroup() %>%
  distinct(year, state_ori, state_dest, .keep_all = TRUE) %>%
  select(-sector_dest)  # total migration from state i to state j for each (i,j) combination

# adjusting x's to y's: cps migration pair share times total migration from acs
mobility <- cps_nber %>%
  left_join(acs, by=c('year' = 'year', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori')) %>%
  group_by(year, state_dest, state_ori) %>% 
  mutate(tot_n_cps_accros_sec = sum(n_cps)) %>% # totol within destination state migration (sum over all sector movements)
  ungroup() %>%
  mutate(n_cps_adj = n_cps/tot_n_cps_accros_sec) %>% # migration share across sectors within state (based on destination state)
  mutate(n_cps_adj = ifelse(is.na(n_cps_adj) == TRUE, 0, n_cps_adj)) %>%
  mutate(n_cps_adj = n_cps_adj*n_acs) %>% # use cps within-state across sector migration share times acs total migration across states
  select(-tot_n_cps_accros_sec, -n_cps, -n_acs) 

# mu_1999 prime for L_1999
# the second part of this calculation is in the next step since there is an additional proportionality that has to be implemented in L_2000 so that it is consistent with WIOD
mu_1999_prime <- mobility %>%
  filter(year == 1999) %>%
  group_by(year, state_dest, sector_dest) %>% 
  mutate(tot_n = sum(n_cps_adj)) %>% # total inflows to destination state-sector
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n) %>%  # (inflow share of destination state-sector across original state-sector)rel: share of people from original state-sector pairs to the same destination state-sector
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel)

# mu_1999 prime for L_1999
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars = c("state"), variable.name = "sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector)))
mu_1999_prime <- mu_1999_prime %>%
  left_join(L_2000, by=c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)
write.table(mu_1999_prime, file = paste("1-Intermediate_Processed_Data/mu_1999_prime_nber_case1_yearly.csv", sep=""), sep = ",", row.names = FALSE)

# Computing L_1999 using mobility matrices and L_2000
L_1999 <- mu_1999_prime %>%
  group_by(state_ori, sector_ori) %>%
  mutate(employ = sum(level_employ)) %>%  # 1999 labour distribution
  ungroup() %>%
  distinct(state_ori, sector_ori, .keep_all = TRUE) %>%
  dplyr::rename(state = state_ori, sector = sector_ori) %>%
  select(state, sector, employ) %>%
  arrange(state, sector)
temp_L_1999 <- L_1999
L_1999 <- spread(L_1999, sector, employ, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
# write.table(L_1999, file = paste("1-Intermediate_Processed_Data/L_1999.csv", sep=""), sep = ",", row.names = FALSE)

# Recalculating mu_1999 and checking flow 1999-2000
mu_1999 <- mu_1999_prime %>% 
  dplyr::rename(n_cps_adj_ = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj_)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj_/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
write_xlsx(mu_1999, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case1_long_format_yearly.xlsx", sep=""))
mu_1999 <- mu_1999 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999 <- spread(mu_1999, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)

# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999, path = paste("2-Final_Data/mu_1999_nber_case1_yearly.xlsx", sep=""))


#### Case 2 ####
# loading intermediate CPS
cps <- read.csv(paste("1-Intermediate_Processed_Data/cps_nber_2_yearly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# within states proportionality
temp_within  <- cps %>%           # create the cps share for within state expression
  filter(state_ori == state_dest & year == 1999)  %>% 
  group_by(year, state_dest, state_ori)  %>% 
  mutate(n_cps_two_states_tot = sum(n_cps))  %>% 
  ungroup()  %>% 
  mutate(cps_share_wti = n_cps/n_cps_two_states_tot) %>% 
  select(year, state_ori, state_dest, sector_ori, sector_dest, cps_share_wti)

# between states proportionality
temp_between_cps  <- cps  %>%    # create the cps share for between state expression
  filter(state_ori == state_dest & year == 1999)  %>% 
  group_by(year, state_dest, state_ori, sector_dest)  %>% 
  mutate(n_cps_same_sector_dest = sum(n_cps))  %>% 
  ungroup()  %>% 
  mutate(cps_share_btw = n_cps/n_cps_same_sector_dest)  %>% 
  select(year, state_ori, state_dest, sector_ori, sector_dest, cps_share_btw)

acs <- read.csv(paste("1-Intermediate_Processed_Data/acs.csv", sep=""), header = TRUE, sep = ",", dec = ".")

temp_between_acs  <-  acs  %>%  # create the acs share for between state expression
  filter(year == 1999)  %>% 
  group_by(year, state_dest, state_ori)  %>% 
  mutate(n_acs_two_tot = sum(n_acs))  %>% 
  ungroup()  %>% 
  mutate(acs_share = n_acs/n_acs_two_tot)  %>% 
  mutate(acs_share = ifelse(is.na(acs_share), 0, acs_share))  %>% 
  select(year, state_ori, state_dest, sector_dest, acs_share)

irs <-  read.csv(paste("1-Intermediate_Processed_Data/irs.csv", sep=""), header = TRUE, sep = ",", dec = ".")

mobility  <- cps  %>%   # adjusted migration flows
  filter(year == 1999)  %>% 
  left_join(irs, by=c('year' = 'year', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori')) %>%
  left_join(temp_within, by = c('year' = 'year', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori', 'sector_dest' = 'sector_dest', 'sector_ori' = 'sector_ori'))  %>% 
  left_join(temp_between_acs, by = c('year' = 'year', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori', 'sector_dest' = 'sector_dest'))  %>% 
  left_join(temp_between_cps, by = c('year' = 'year', 'state_dest' = 'state_dest', 'sector_dest' = 'sector_dest', 'sector_ori' = 'sector_ori'))  %>% 
  rename(state_ori = state_ori.x)  %>% 
  mutate(n_cps_adj = exemption * acs_share * cps_share_btw)  %>% 
  mutate(n_cps_adj = ifelse(state_ori == state_dest, exemption*cps_share_wti, n_cps_adj))  %>% 
  select(-state_ori.y)

# mu_1999 prime for L_1999
# the second part of this calculation is in the next step since there is an additional proportionality that has to be implemented in L_2000 so that it is consistent with WIOD
mu_1999_prime <- mobility %>%
  group_by(year, state_dest, sector_dest) %>% 
  mutate(tot_n = sum(n_cps_adj)) %>% # total inflows to destination state-sector
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n) %>%  #(inflow share of destination state-sector across original state-sector) rel: share of people from original state-sector pairs to the same destination state-sector
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel)

# mu_1999 prime for L_1999
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars = c("state"), variable.name = "sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector)))
mu_1999_prime <- mu_1999_prime %>%
  left_join(L_2000, by=c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)
write.table(mu_1999_prime, file = paste("1-Intermediate_Processed_Data/mu_1999_prime_nber_case2_yearly.csv", sep=""), sep = ",", row.names = FALSE)

# Computing L_1999 using mobility matrices and L_2000
L_1999 <- mu_1999_prime %>%
  group_by(state_ori, sector_ori) %>%
  mutate(employ = sum(level_employ)) %>%  # 1999 labour distribution
  ungroup() %>%
  distinct(state_ori, sector_ori, .keep_all = TRUE) %>%
  dplyr::rename(state = state_ori, sector = sector_ori) %>%
  select(state, sector, employ) %>%
  arrange(state, sector)
temp_L_1999 <- L_1999
L_1999 <- spread(L_1999, sector, employ, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
write.table(L_1999, file = paste("1-Intermediate_Processed_Data/L_1999_case2.csv", sep=""), sep = ",", row.names = FALSE)

# Recalculating mu_1999 and checking flow 1999-2000
mu_1999 <- mu_1999_prime %>% 
  dplyr::rename(n_cps_adj_ = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj_)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj_/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
write_xlsx(mu_1999, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case2_long_format_yearly.xlsx", sep=""))
mu_1999 <- mu_1999 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999 <- spread(mu_1999, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)

# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999, path = paste("2-Final_Data/mu_1999_nber_case2_yearly.xlsx", sep=""))

# check L_1999 and mu_1999 gives L_2000
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars=c("state"), variable.name="sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector))) %>%
  arrange(state, sector)
L_2000 <- as.matrix(L_2000$employ)
L_1999 <- as.matrix(temp_L_1999$employ)
mu_1999 <- mu_1999 %>% select(-year, -state_ori, -sector_ori)
mu_1999 <- as.matrix(mu_1999)
if(sum(L_2000 - (t(mu_1999)%*%L_1999)) > epsilon) 
  stop(paste("L_1999 and mu_1999 do NOT give L_2000"))

```

```{r transition probability at labour market level}
migration_1999_0  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_nber_case0_yearly.csv", sep=""), header = TRUE, sep = ",", dec = ".")
migration_1999_1  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_nber_case1_yearly.csv", sep=""), header = TRUE, sep = ",", dec = ".")
migration_1999_2  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_nber_case2_yearly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# Transition probability (at labour market level)
## Same state and sector
suffixes <- c("0", "1", "2")   # Define a vector of suffixes for the data frames
same_state_same_sector_list <- list()   # Create an empty list to store the results
columns_to_suffix <- c("same_state_same_sector")

for (suffix in suffixes) {    # Loop over the suffixes and process the data frames
  current_df <- get(paste0("migration_1999_", suffix))
  
  current_same_state_same_sector <- current_df %>%
    group_by(year, state_ori, sector_ori)  %>% 
    mutate(l_1999 = sum(level_employ))  %>% 
    mutate(stay_in_num = sum(level_employ[state_ori == state_dest & sector_ori == sector_dest]))  %>% 
    ungroup()  %>% 
    mutate(same_state_same_sector = stay_in_num/l_1999)  %>% 
    select(state_ori, sector_ori, same_state_same_sector)  %>% 
    distinct(state_ori, sector_ori, same_state_same_sector, .keep_all = TRUE)

  colnames( current_same_state_same_sector)[colnames( current_same_state_same_sector) %in% columns_to_suffix] <-
    paste0(colnames( current_same_state_same_sector)[colnames( current_same_state_same_sector) %in% columns_to_suffix], "_", suffix)
  
  same_state_same_sector_list[[suffix]] <- current_same_state_same_sector
}

same_state_same_sector <- Reduce(function(x, y) left_join(x, y, by = c("state_ori", "sector_ori")), same_state_same_sector_list)  # Merge the results into a single data frame

## Changing state not sector
suffixes <- c("0", "1", "2")   # Define a vector of suffixes for the data frames
chg_state_not_sector_list <- list()   # Create an empty list to store the results
columns_to_suffix <- c("chg_state_not_sector")

for (suffix in suffixes) {    # Loop over the suffixes and process the data frames
  current_df <- get(paste0("migration_1999_", suffix))
  
  current_chg_state_not_sector <- current_df %>%
    group_by(year, state_ori, sector_ori)  %>% 
    mutate(l_1999 = sum(level_employ))  %>% 
    mutate(stay_in_num = sum(level_employ[state_ori != state_dest & sector_ori == sector_dest]))  %>% 
    ungroup()  %>% 
    mutate(chg_state_not_sector = stay_in_num/l_1999)  %>% 
    select(state_ori, sector_ori, chg_state_not_sector)  %>% 
    distinct(state_ori, sector_ori, chg_state_not_sector, .keep_all = TRUE)

  colnames( current_chg_state_not_sector)[colnames( current_chg_state_not_sector) %in% columns_to_suffix] <-
    paste0(colnames( current_chg_state_not_sector)[colnames( current_chg_state_not_sector) %in% columns_to_suffix], "_", suffix)
  
  chg_state_not_sector_list[[suffix]] <- current_chg_state_not_sector
}

chg_state_not_sector <- Reduce(function(x, y) left_join(x, y, by = c("state_ori", "sector_ori")), chg_state_not_sector_list)  # Merge the results into a single data frame

## Changing sector not state
suffixes <- c("0", "1", "2")   # Define a vector of suffixes for the data frames
chg_sector_not_state_list <- list()   # Create an empty list to store the results
columns_to_suffix <- c("chg_sector_not_state")

for (suffix in suffixes) {    # Loop over the suffixes and process the data frames
  current_df <- get(paste0("migration_1999_", suffix))
  
  current_chg_sector_not_state <- current_df %>%
    group_by(year, state_ori, sector_ori)  %>% 
    mutate(l_1999 = sum(level_employ))  %>% 
    mutate(stay_in_num = sum(level_employ[state_ori == state_dest & sector_ori != sector_dest]))  %>% 
    ungroup()  %>% 
    mutate(chg_sector_not_state = stay_in_num/l_1999)  %>% 
    select(state_ori, sector_ori, chg_sector_not_state)  %>% 
    distinct(state_ori, sector_ori, chg_sector_not_state, .keep_all = TRUE)

  colnames( current_chg_sector_not_state)[colnames( current_chg_sector_not_state) %in% columns_to_suffix] <-
    paste0(colnames( current_chg_sector_not_state)[colnames( current_chg_sector_not_state) %in% columns_to_suffix], "_", suffix)
  
  chg_sector_not_state_list[[suffix]] <- current_chg_sector_not_state
}

chg_sector_not_state <- Reduce(function(x, y) left_join(x, y, by = c("state_ori", "sector_ori")), chg_sector_not_state_list)  

## Changing sector changing state
suffixes <- c("0", "1", "2")   # Define a vector of suffixes for the data frames
chg_state_chg_sector_list <- list()   # Create an empty list to store the results
columns_to_suffix <- c("chg_state_chg_sector")

for (suffix in suffixes) {    # Loop over the suffixes and process the data frames
  current_df <- get(paste0("migration_1999_", suffix))
  
  current_chg_state_chg_sector <- current_df %>%
    group_by(year, state_ori, sector_ori)  %>% 
    mutate(l_1999 = sum(level_employ))  %>% 
    mutate(stay_in_num = sum(level_employ[state_ori != state_dest & sector_ori != sector_dest]))  %>% 
    ungroup()  %>% 
    mutate(chg_state_chg_sector = stay_in_num/l_1999)  %>% 
    select(state_ori, sector_ori, chg_state_chg_sector)  %>% 
    distinct(state_ori, sector_ori, chg_state_chg_sector, .keep_all = TRUE)

  colnames( current_chg_state_chg_sector)[colnames( current_chg_state_chg_sector) %in% columns_to_suffix] <-
    paste0(colnames( current_chg_state_chg_sector)[colnames( current_chg_state_chg_sector) %in% columns_to_suffix], "_", suffix)
  
  chg_state_chg_sector_list[[suffix]] <- current_chg_state_chg_sector
}

chg_state_chg_sector <- Reduce(function(x, y) left_join(x, y, by = c("state_ori", "sector_ori")), chg_state_chg_sector_list)  

transition_prob  <- same_state_same_sector  %>% 
  left_join(chg_sector_not_state, by = c('state_ori', 'sector_ori'))  %>% 
  left_join(chg_state_not_sector, by = c('state_ori', 'sector_ori'))  %>% 
  left_join(chg_state_chg_sector, by = c('state_ori', 'sector_ori')) 

cols_to_multiply  <- 3:14
for (col in cols_to_multiply) {
  transition_prob[, col] <- transition_prob[, col] * 100
}
#write_xlsx(transition_prob, "1-Intermediate_Processed_Data/transition_prob_yearly(at state sector level).xlsx")

summary_pro  <- transition_prob  %>% 
  select(-state_ori, -sector_ori)  %>% 
  mutate(across(everything(), list(Mean = mean, Max = max, Min = min, p25 = ~quantile(.,probs = 0.25), p50 = ~quantile(.,probs = 0.50), p75 = ~quantile(.,probs = 0.75))))  %>% 
  select(contains("Mean") | contains("Max") | contains("Min") | contains("p25") | contains("p50") | contains("p75"))  %>% 
  distinct()

summary_pro <- summary_pro %>%
  pivot_longer(cols = everything(), 
               names_to = c("state_sector", ".value"), 
               names_sep = "_(?=Mean|Max|Min|p25|p50|p75)") 
#write_xlsx(summary_pro, "1-Intermediate_Processed_Data/summary_statistics_yearly(at state sector level).xlsx")

column <- transition_prob$same_state_same_sector_1
cat("Mean:", mean(column), "\n")
cat("Maximum:", max(column), "\n")
cat("Minimum:", min(column), "\n")
cat("25th Percentile:", quantile(column, 0.25), "\n")
cat("50th Percentile (Median):", median(column), "\n")
cat("75th Percentile:", quantile(column, 0.75), "\n")

# Histogram
transition_prob  %>% 
  ggplot() +
  geom_histogram(aes(x = same_state_same_sector_1))

transition_prob  %>% 
  ggplot() +
  geom_histogram(aes(x = same_state_same_sector_2))



```

```{r construct cps_nber_2_quarterly}
# load CPS data from NBER
cps_nber  <- haven::read_dta("/Users/yyh/Library/CloudStorage/OneDrive-LondonSchoolofEconomics/RUV_data_no_GitHub/CPS_redone/Outputs/clean_data_new.dta")
write_csv(cps_nber, file = paste("1-Intermediate_Processed_Data/cps_nber_quarterly.xlsx", sep = ""))

cps_nber  <- read.csv("1-Intermediate_Processed_Data/cps_nber_quarterly.xlsx")
mn_list <- c("jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec")
quart_inter  <- c(1, 4, 5, 8)

# annual matching
a  <- cps_nber  %>% 
  distinct(P_ID)  %>% 
  n_distinct()
# changes for quarterly matrix: match for interview 1&4, 5&8
## keep two observations
##cps_nber  <- cps_nber  %>% 
##  arrange(P_ID, inter_num)
##
##cps_nber  <- cps_nber  %>% 
##  group_by(P_ID)  %>% 
##  filter(inter_num  %in% quart_inter)  %>% 
##  filter(
##    (all(c(1, 4) %in% inter_num)) |
##    (all(c(5, 8) %in% inter_num))
##  )  %>% 
##  ungroup()

## keep only one observation
cps_nber <- cps_nber %>%
  group_by(P_ID) %>%
  filter(any(inter_num == 4) & any(inter_num == 1))  %>% 
  ungroup()
c <- cps_nber  %>% 
  distinct(P_ID)  %>% 
  n_distinct()
# household matching rate
print(c*100/(a))  


# matching persons via same month in consecutive years based on H_ID and P_ID
base <- c()
for (yr in 1999:2001) {
temp_cps  <- cps_nber  %>% 
    filter(year == yr | year == yr - 1)  

info_present  <- temp_cps  %>% 
  group_by(P_ID, year)  %>%    # there will be double accounting issues (when 1&4 and 5&8 are both present)
  filter(inter_num == 4 | inter_num == 8)  %>% 
  ungroup()  %>% 
  dplyr::rename(sector_dest = sector, state_dest = st_name)

info_past  <- temp_cps  %>% 
  group_by(P_ID, year)  %>% 
  filter(inter_num == 1 | inter_num == 5)  %>% 
  ungroup()  %>% 
  select( -year, -month, -wtfinl) %>%
  dplyr::rename(sector_ori = sector, state_ori = st_name)
  
temp <- full_join(info_present, info_past, by = c("P_ID"))  %>% # after matching, get state info for t and t-1 from CPS
  filter( inter_num.x - inter_num.y == 3 )  %>% filter( inter_num.x == 4 | inter_num.x == 8) # keep one observation
  
temp <- temp %>%
  filter(is.na(state_ori) == FALSE & is.na(state_dest) == FALSE) %>% # only matches
  distinct(P_ID, year, month, .keep_all = TRUE)

base <- rbind(base, temp)

}

#base  <- base  %>%
#  group_by(year, month, P_ID) %>%  
#  mutate(n = n())  %>% 
#  ungroup()

#base  <- base  %>% 
#  arrange(year, month, P_ID)

base  <- base  %>% 
  distinct(year, month, P_ID, .keep_all = TRUE)


base  <- base  %>% 
  mutate(quarter = ifelse(month %in% c("jan", "feb", "mar"), 1, 0) )  %>% 
  mutate(quarter = ifelse(month %in% c("apr", "may", "jun"), 2, quarter ))  %>% 
  mutate(quarter = ifelse(month %in% c("jul", "aug", "sep"), 3, quarter ))  %>% 
  mutate(quarter = ifelse(month %in% c("oct", "nov", "dec"), 4, quarter ))  

#before_rolling  <- base  %>% 
#  mutate(year = year - 1)

# rolling basis: 2-year window
final_base <- c()
for (yr in 1997:2002) {
for (q in 1:4) {
  temp <- base %>%
    #filter((year == yr-2 & quarter >= q) | (year >= yr - 1 & year <= yr + 1 ) | (year == yr + 2 & quarter <= q-1 )) %>% # rolling 5-year
    #filter(year == yr & quarter == q)  %>%   # no rolling
    filter((year == yr-1 & quarter >= q) | (year == yr  & quarter <= q )) %>%  # rolling 2-year
    #filter((year == yr-1 & quarter >= q) | (year == yr) |  (year == yr + 1  & quarter <= q-1 )) %>%  # rolling 3-year
    mutate(year = yr) %>% 
    mutate(quarter = q) 
  final_base <- rbind(final_base, temp)
}  
}
base <- final_base
base <- final_base %>% mutate(year = year - 1)

#after_rolling  <- base


# counting sector-sector within state movements
##base <- base %>%
##  select(-month, -P_ID, -inter_num.x, -inter_num.y, -st_fips.x, -st_fips.y) %>%
##  group_by(year, quarter, state_ori, sector_ori, state_dest, sector_dest) %>%
##  mutate(n_cps = sum(wtfinl)) %>%
##  ungroup() %>%
##  distinct(year, quarter, state_ori, sector_ori, state_dest, sector_dest, .keep_all = TRUE) %>%
##  select(year, quarter, state_ori, sector_ori, state_dest, sector_dest, n_cps)

base <- base %>%
  select(-month, -P_ID, -inter_num.x, -inter_num.y, -st_fips.x, -st_fips.y) %>%
  group_by(year, quarter, state_ori, sector_ori, state_dest, sector_dest) %>%
  mutate(n_cps = sum(wtfinl)) %>%
  ungroup() %>%
  group_by(year, quarter, state_ori, sector_ori) %>%
  mutate(n_sample = n()) %>%   # with filtering number of observations
  ungroup() %>%
  distinct(year, quarter, state_ori, sector_ori, state_dest, sector_dest, .keep_all = TRUE) %>%
  select(year, quarter, state_ori, sector_ori, state_dest, sector_dest, n_cps, n_sample)

base_temp  <- base  %>% 
  filter(year == 1999)  %>% 
  filter(n_sample < 10)  %>% 
  mutate(name = paste(state_ori, sector_ori))  %>% 
  arrange(state_ori, sector_ori)

unique(base_temp$name)     # list of dropped cases: 303 (state_ori, sector_ori)

base  %>% 
  filter(year == 1999)  %>%  
  select(n_sample)  %>% 
  summary()     #  1st Qu.:  15


base  <- base  %>% 
  filter(n_sample >= 10)  # 1450 observations dropped
#base  <- base  %>% 
#  filter(n_sample >= 5)  

# adding missing combinations

temp <- data.frame(s_names)  
sec  <- c(0:14)
temp_sec  <- data.frame(sec)
yr  <- c(1998:2001)
temp_yr  <- data.frame(yr) 
qr  <- c(1:4)
temp_qr  <- data.frame(qr)
combo_st_sec_yr  <- expand.grid(year = temp_yr$yr, quarter = temp_qr$qr, state_ori = temp$s_names, state_dest = temp$s_names, sector_ori = temp_sec$sec, sector_dest = temp_sec$sec) 

cps_nber  <- combo_st_sec_yr  %>% 
  left_join(base, by = c('year'='year', 'quarter'='quarter', 'state_ori'='state_ori', 'state_dest'='state_dest', 'sector_ori'='sector_ori','sector_dest'='sector_dest'))  %>% 
  mutate(n_cps = ifelse(is.na(n_cps), 0, n_cps))

cps_nber_  <- cps_nber

before  <- cps_nber
before  ->  cps_nber

############################ Modification: proportionality assumption on diagonals ##################################
# replacing 0 in diag based on median non-zero diag shares within year-sector
temp <- cps_nber  %>% 
  mutate(diag = ifelse(sector_ori == sector_dest & state_ori == state_dest, 1, 0))  %>% 
  group_by(year, quarter, state_ori, sector_ori)  %>% 
  mutate(stock_ori = sum(n_cps))  %>% 
  mutate(outflow_share = n_cps/stock_ori)  %>% 
  mutate(outflow_share = ifelse(is.na(outflow_share), 0, outflow_share))  %>% 
  mutate(stay_in_share = ifelse(diag == 1, outflow_share, 0))  %>% 
  mutate(stay_in_share = max(stay_in_share))  %>%   # filter out the stay_in_share for each pair
  ungroup() %>% 
  group_by(year,quarter, sector_ori)  %>% 
  mutate(stay_in_share_median = median(stay_in_share))  %>% # filter out the median of stay_in_share of the sector
  mutate(stay_in_share_median = ifelse(stay_in_share_median == 0 & any(stay_in_share>0), min(stay_in_share[stay_in_share>0]), stay_in_share_median))  %>%   # when the stay_in_median = 0, then replace it with the minimum non-zero value
  #mutate(stay_in_share_median = ifelse(stay_in_share_median == inf, 0, stay_in_share_median))  %>%  # one case: 2001 q=3 sector_ori = 7 returns inf because no non-zero values
  ungroup()  %>% 
  group_by(year, quarter, state_dest, sector_dest)  %>% 
  mutate(stock_dest = sum(n_cps))  %>% 
  mutate(stock_dest_diag = ifelse(diag == 1, stock_dest, 0))  %>% 
  ungroup()  %>% 
  group_by(year, quarter, state_ori, sector_ori)  %>% 
  mutate(stock_dest_diag = max(stock_dest_diag))  %>% 
  ungroup()  %>%
  group_by(year, quarter, sector_ori)  %>% 
  mutate(stock_dest_diag_min = min(stock_dest_diag[stock_dest_diag > 0]))  %>%   
  ungroup()  %>% 
  mutate(diag_new = ifelse(stay_in_share_median == 1, pmax(stock_dest_diag_min, stock_ori, stock_dest_diag),  pmax(stock_dest_diag_min, stock_ori, stock_dest_diag)/(1-stay_in_share_median) * stay_in_share_median))  %>% 
  #mutate(diag_new = ifelse(stay_in_share_median == 1, pmax(1, stock_ori, stock_dest_diag),  pmax(1, stock_ori, stock_dest_diag)/(1-stay_in_share_median) * stay_in_share_median))  %>% 
  #mutate(diag_new = pmax(1, stock_ori, stock_dest_diag)/(1-stay_in_share_median) * stay_in_share_median)  %>%  # 709 cases takes the value of 1 in all quarter in 1999
  mutate(flag = ifelse(diag == 1 & n_cps == 0, 1, 0))  %>%  
  mutate(n_cps = ifelse(diag == 1 & n_cps == 0, diag_new, n_cps))  %>% 
  select(year, quarter, state_ori, sector_ori, state_dest, sector_dest, n_cps) 
cps_nber  <- temp

#filling missing matrix sections as CDP
cps_nber <- cps_nber %>%
  mutate(n_master = ifelse(state_ori == state_dest, n_cps, 0)) %>%
  select(-n_cps) %>%   #actually, n_master == n_cps......
  group_by(year, quarter, state_dest, sector_dest, sector_ori) %>% #based on destination state
  mutate(n_cps = max(n_master)) %>%  #n_cps:  each entry takes the value of within destination state migration for that sector-sector movement, therefore same value for same (year, state_dest, sector_dest, sector_ori) across original states
  ungroup() %>%
  select(-n_master) %>%
  arrange(year, quarter, state_dest, sector_dest, state_ori, sector_ori)

cps_nber  <- cps_nber  %>% 
  mutate(diag = ifelse(state_dest == state_ori & sector_ori == sector_dest, 1, 0))

write.table(cps_nber, file = paste("1-Intermediate_Processed_Data/cps_nber_2_quarterly.csv", sep=""), sep = ",", row.names = FALSE)

############################ Old code without modification ##################################
# replacing 0 in diag for min non-zero diag value
temp <- cps_nber_ %>%
  mutate(diag = ifelse(sector_ori == sector_dest & state_ori == state_dest, 1, 0)) %>%
  filter(diag == 1 & n_cps != 0) %>%
  group_by(year, quarter, diag) %>%
  mutate(min_diag = min(n_cps)) %>% #min non-zero diag value within the same year across all diagonals
  ungroup() %>%
  distinct(year, quarter, .keep_all = TRUE) %>%
  select(year, quarter, min_diag)  #year 1999, 2000, 2001, the minimum is 264.8371; year 2002, the minimum is 277.1613; year 2003, 2004, 2005, 2006, the minimum is 230.9756. 
cps_nber_ <- cps_nber_  %>%
  left_join(temp, by=c("year"="year", "quarter"="quarter")) %>%
  mutate(diag = ifelse(sector_ori == sector_dest & state_ori == state_dest, 1, 0)) %>%
  mutate(n_cps = ifelse(diag == 1 & n_cps == 0 , min_diag, n_cps)) %>% #108 cases
  select(-min_diag, -diag) # n_cps: only have within state movements sector-sector migration flows (all diag missing are filled), across state equals zero
rm(temp)

# filling missing matrix sections as CDP
cps_nber_ <- cps_nber_ %>%
  mutate(n_master = ifelse(state_ori == state_dest, n_cps, 0)) %>%
  select(-n_cps) %>%   #actually, n_master == n_cps......
  group_by(year, quarter, state_dest, sector_dest, sector_ori) %>% #based on destination state
  mutate(n_cps = max(n_master)) %>%  #n_cps:  each entry takes the value of within destination state migration for that sector movement, therefore same value for same (state_dest, sector_dest)
  ungroup() %>%
  select(-n_master) %>%
  arrange(year, quarter, state_dest, sector_dest, state_ori, sector_ori)
write.table(cps_nber_, file = paste("1-Intermediate_Processed_Data/cps_nber_2_case0_quarterly.csv", sep=""), sep = ",", row.names = FALSE) 


```

### Quarterly matrix with IRS, ACS and CPS (Case 2)

```{r}
# loading intermediate CPS
cps <- read.csv(paste("1-Intermediate_Processed_Data/cps_nber_2_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# within states proportionality
temp_within  <- cps %>%           # create the cps share for within state expression
  filter(state_ori == state_dest & year == 1999)  %>% 
  group_by(year, quarter, state_dest, state_ori)  %>% 
  mutate(n_cps_two_states_tot = sum(n_cps))  %>% 
  ungroup()  %>% 
  mutate(cps_share_wti = n_cps/n_cps_two_states_tot) %>% 
  select(year, quarter, state_ori, state_dest, sector_ori, sector_dest, cps_share_wti)

# between states proportionality
temp_between_cps  <- cps  %>%    # create the cps share for between state expression
  filter(state_ori == state_dest & year == 1999)  %>% 
  group_by(year, quarter, state_dest, state_ori, sector_dest)  %>% 
  mutate(n_cps_same_sector_dest = sum(n_cps))  %>% 
  ungroup()  %>% 
  mutate(cps_share_btw = n_cps/n_cps_same_sector_dest)  %>% 
  mutate(cps_share_btw = ifelse(is.na(cps_share_btw), 0, cps_share_btw))  %>% 
  select(year, quarter, state_ori, state_dest, sector_ori, sector_dest, cps_share_btw)

acs <- read.csv(paste("1-Intermediate_Processed_Data/acs_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

temp_between_acs  <-  acs  %>%  # create the acs share for between state expression
  filter(year == 1999)  %>% 
  group_by(year, quarter, state_dest, state_ori)  %>% 
  mutate(n_acs_two_tot = sum(n_acs))  %>% 
  ungroup()  %>% 
  mutate(acs_share = n_acs/n_acs_two_tot)  %>% 
  mutate(acs_share = ifelse(is.na(acs_share), 0, acs_share))  %>% 
  select(year, quarter, state_ori, state_dest, sector_dest, acs_share)

# quarterly irs data
irs  <- read.csv(paste("1-Intermediate_Processed_Data/irs.csv", sep=""), header = TRUE, sep = ",", dec = ".")  %>% 
  mutate(exemption = exemption/4)

temp <- data.frame(s_names)  
qr  <- c(1:4)
temp_qr  <- data.frame(qr)
combo_st_qr  <- expand.grid(quarter = temp_qr$qr, state_ori = temp$s_names, state_dest = temp$s_names)  %>% 
  mutate(year = 1999)

irs  <- combo_st_qr  %>% 
  left_join(irs, by = c('state_ori' = 'state_ori',  'state_dest' = 'state_dest', 'year' = 'year'))

# migration matrix
mobility  <- cps  %>%   # adjusted migration flows
  filter(year == 1999)  %>% 
  left_join(irs, by=c('year' = 'year', 'quarter'='quarter', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori')) %>%
  left_join(temp_within, by = c('year' = 'year', 'quarter'='quarter', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori', 'sector_dest' = 'sector_dest', 'sector_ori' = 'sector_ori'))  %>% 
  left_join(temp_between_acs, by = c('year' = 'year', 'quarter'='quarter', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori', 'sector_dest' = 'sector_dest'))  %>% 
  left_join(temp_between_cps, by = c('year' = 'year', 'quarter'='quarter', 'state_dest' = 'state_dest', 'sector_dest' = 'sector_dest', 'sector_ori' = 'sector_ori'))  %>% 
  rename(state_ori = state_ori.x)  %>% 
  mutate(n_cps_adj = exemption * acs_share * cps_share_btw)  %>% 
  mutate(n_cps_adj = ifelse(state_ori == state_dest, exemption*cps_share_wti, n_cps_adj))  %>% 
  select(-state_ori.y)
mu_long_format_quarter_no_adj_case2   <- mobility  %>% 
  group_by(year, quarter, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(mu = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(year, quarter, state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE)
write_csv(mobility, file = paste("1-Intermediate_Processed_Data/mobility_nber_case2_quarterly.csv", sep=""))

# mu_1999 prime for L_1999
# the second part of this calculation is in the next step since there is an additional proportionality that has to be implemented in L_2000 so that it is consistent with WIOD
mu_1999_prime <- mobility %>%
  group_by(year, quarter, state_dest, sector_dest) %>% 
  mutate(tot_n = sum(n_cps_adj)) %>% # total inflows to destination state-sector
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n) %>%  #(inflow share of destination state-sector across original state-sector) rel: share of people from original state-sector pairs to the same destination state-sector
  mutate(rel = ifelse(is.na(rel), 0, rel))  %>% 
  select(year, quarter, state_dest, state_ori, sector_dest, sector_ori, rel)


mu_1999_prime_q1  <- mu_1999_prime  %>% 
  filter(quarter == 1)
mu_1999_prime_q2  <- mu_1999_prime  %>% 
  filter(quarter == 2)
mu_1999_prime_q3  <- mu_1999_prime  %>% 
  filter(quarter == 3)
mu_1999_prime_q4  <- mu_1999_prime  %>% 
  filter(quarter == 4)

# mu_1999 prime for L_1999
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars = c("state"), variable.name = "sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector)))

mu_1999_prime_q4 <- mu_1999_prime_q4 %>%
  left_join(L_2000, by=c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)

L_2000_temp  <- mu_1999_prime_q4  %>% 
  group_by(state_ori, sector_ori)  %>% 
  mutate(employ = sum(level_employ))  %>% 
  ungroup()  %>% 
  distinct(year, state_ori, sector_ori, .keep_all = TRUE) %>% 
  rename(state = state_ori, sector = sector_ori)  %>% 
  select(state, sector, employ)

mu_1999_prime_q3 <- mu_1999_prime_q3 %>%
  left_join(L_2000_temp, by = c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)

L_2000_temp  <- mu_1999_prime_q3  %>% 
  group_by(state_ori, sector_ori)  %>% 
  mutate(employ = sum(level_employ))  %>% 
  ungroup()  %>% 
  distinct(year, state_ori, sector_ori, .keep_all = TRUE) %>% 
  rename(state = state_ori, sector = sector_ori)  %>% 
  select(state, sector, employ)

mu_1999_prime_q2 <- mu_1999_prime_q2 %>%
  left_join(L_2000_temp, by = c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)

L_2000_temp  <- mu_1999_prime_q2  %>% 
  group_by(state_ori, sector_ori)  %>% 
  mutate(employ = sum(level_employ))  %>% 
  ungroup()  %>% 
  distinct(year, state_ori, sector_ori, .keep_all = TRUE) %>% 
  rename(state = state_ori, sector = sector_ori)  %>% 
  select(state, sector, employ)

mu_1999_prime_q1 <- mu_1999_prime_q1 %>%
  left_join(L_2000_temp, by = c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)

mu_1999_prime <- c()
mu_1999_prime <- bind_rows(mu_1999_prime_q1, mu_1999_prime_q2)
mu_1999_prime <- bind_rows(mu_1999_prime, mu_1999_prime_q3)
mu_1999_prime <- bind_rows(mu_1999_prime, mu_1999_prime_q4)
  
write_csv(mu_1999_prime, file = paste("1-Intermediate_Processed_Data/mu_1999_prime_nber_case2_quarterly.csv", sep=""))

# Recalculating mu_1999 and checking flow 1999-2000
mu_1999_q1 <- mu_1999_prime_q1 %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
long_format_q1  <- mu_1999_q1  %>% 
  mutate(quarter = 1)

mu_1999_q1 <- mu_1999_q1 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999_q1 <- spread(mu_1999_q1, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
A  <- mu_1999_q1[,4:ncol(mu_1999_q1)]
# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999_q1 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_q1, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case2_q1.xlsx", sep=""))

mu_1999_q2 <- mu_1999_prime_q2 %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
long_format_q2  <- mu_1999_q2  %>% 
  mutate(quarter = 2)

mu_1999_q2 <- mu_1999_q2 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999_q2 <- spread(mu_1999_q2, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
B  <- mu_1999_q2[,4:ncol(mu_1999_q2)]
# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999_q2 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_q2, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case2_q2.xlsx", sep=""))

mu_1999_q3 <- mu_1999_prime_q3 %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
long_format_q3  <- mu_1999_q3  %>% 
  mutate(quarter = 3)

mu_1999_q3 <- mu_1999_q3 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999_q3 <- spread(mu_1999_q3, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
C  <- mu_1999_q3[,4:ncol(mu_1999_q3)]
# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999_q3 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_q3, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case2_q3.xlsx", sep=""))

mu_1999_q4 <- mu_1999_prime_q4 %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
long_format_q4  <- mu_1999_q4  %>% 
  mutate(quarter = 4)

mu_1999_q4 <- mu_1999_q4 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999_q4 <- spread(mu_1999_q4, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
D  <- mu_1999_q4[,4:ncol(mu_1999_q4)]
columns  <- mu_1999_q4  %>% 
  select(year, state_ori, sector_ori)

mu_long_format_quarter_case2  <- long_format_q1  %>% 
  bind_rows(long_format_q2)  %>% 
  bind_rows(long_format_q3)  %>% 
  bind_rows(long_format_q4) 

# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999_q4 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_q4, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case2_q4.xlsx", sep=""))

A <- apply(A, c(1, 2), function(x) as.numeric(as.character(x)))
B <- apply(B, c(1, 2), function(x) as.numeric(as.character(x)))
C <- apply(C, c(1, 2), function(x) as.numeric(as.character(x)))
D <- apply(D, c(1, 2), function(x) as.numeric(as.character(x)))
mu_1999_annualise  <- A %*% B %*% C %*% D
mu_1999_annualise  <- bind_cols(mu_1999_annualise, columns)
mu_1999_annualise  <- mu_1999_annualise  %>% 
  select(year, state_ori, sector_ori, everything())

mu_1999_annualise_long_2  <- mu_1999_annualise  %>% 
  pivot_longer(cols = 4:ncol(.), names_to = "state_dest_sector_dest", values_to = "rel")  %>% 
  separate(state_dest_sector_dest, into = c("state_dest", "sector_dest"), sep = "_")   %>% 
  mutate(sector_dest = recode(as.character(sector_dest), '00' ="0", '01' ="1", '02' ="2", '03' ="3", '04' ="4", '05' ="5", '06' ="6", '07' ="7", '08' ="8", '09' ="9" ))

epsilon <- 0.01
check <- mu_1999_annualise %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_annualise, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case2_qr_annualised.xlsx", sep=""))


```

### Quarterly matrix with ACS and CPS (Case 1)

```{r}
# loading intermediate CPS
cps_nber <- read.csv(paste("1-Intermediate_Processed_Data/cps_nber_2_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# loading intermediate ACS
acs <- read.csv(paste("1-Intermediate_Processed_Data/acs_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# Mobility matrices
# disaggregating ACS data using CPS sector_ori info and computation of mobility share
# origin in rows and destination in columns
# row shares sum to 1
acs <- acs %>%
  group_by(year, quarter, state_ori, state_dest) %>%
  mutate(n_acs = sum(n_acs)) %>% # n_acs: for (state_ori, state_dest) pair, n_acs is the total migration summed over all destination sectors
  ungroup() %>%
  distinct(year, quarter, state_ori, state_dest, .keep_all = TRUE) %>%
  select(-sector_dest)  # total migration from state i to state j for each (i,j) combination

# adjusting x's to y's: cps migration pair share times total migration from acs
mobility <- cps_nber %>%
  left_join(acs, by=c('year' = 'year', 'quarter' = 'quarter', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori')) %>%
  group_by(year, quarter, state_dest, state_ori) %>% 
  mutate(tot_n_cps_accros_sec = sum(n_cps)) %>% # totol within destination state migration (sum over all sector movements)
  ungroup() %>%
  mutate(n_cps_adj = n_cps/tot_n_cps_accros_sec) %>% # migration share across sectors within state (based on destination state)
  mutate(n_cps_adj = ifelse(is.na(n_cps_adj) == TRUE, 0, n_cps_adj)) %>%
  mutate(n_cps_adj = n_cps_adj*n_acs) %>% # use cps within-state across sector migration share times acs total migration across states
  select(-tot_n_cps_accros_sec, -n_cps, -n_acs) 
mu_long_format_quarter_no_adj_case1   <- mobility  %>% 
  group_by(year, quarter, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(mu = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(year, quarter, state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE)
#write_csv(mobility, file = paste("1-Intermediate_Processed_Data/mobility_case1_quarterly.csv", sep=""))  

# mu_1999 prime for L_1999
# the second part of this calculation is in the next step since there is an additional proportionality that has to be implemented in L_2000 so that it is consistent with WIOD
mu_1999_prime <- mobility %>%
  filter(year == 1999) %>%
  group_by(year, quarter, state_dest, sector_dest) %>% 
  mutate(tot_n = sum(n_cps_adj)) %>% # total inflows to destination state-sector
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n) %>%  # (inflow share of destination state-sector across original state-sector)rel: share of people from original state-sector pairs to the same destination state-sector
  mutate(rel = ifelse(is.na(rel), 0, rel))  %>% 
  select(year, quarter, state_dest, state_ori, sector_dest, sector_ori, rel)


mu_1999_prime_q1  <- mu_1999_prime  %>% 
  filter(quarter == 1)
mu_1999_prime_q2  <- mu_1999_prime  %>% 
  filter(quarter == 2)
mu_1999_prime_q3  <- mu_1999_prime  %>% 
  filter(quarter == 3)
mu_1999_prime_q4  <- mu_1999_prime  %>% 
  filter(quarter == 4)

# mu_1999 prime for L_1999
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars = c("state"), variable.name = "sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector)))

mu_1999_prime_q4 <- mu_1999_prime_q4 %>%
  left_join(L_2000, by=c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)

L_2000_temp  <- mu_1999_prime_q4  %>% 
  group_by(state_ori, sector_ori)  %>% 
  mutate(employ = sum(level_employ))  %>% 
  ungroup()  %>% 
  distinct(year, state_ori, sector_ori, .keep_all = TRUE) %>% 
  rename(state = state_ori, sector = sector_ori)  %>% 
  select(state, sector, employ)

mu_1999_prime_q3 <- mu_1999_prime_q3 %>%
  left_join(L_2000_temp, by = c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)

L_2000_temp  <- mu_1999_prime_q3  %>% 
  group_by(state_ori, sector_ori)  %>% 
  mutate(employ = sum(level_employ))  %>% 
  ungroup()  %>% 
  distinct(year, state_ori, sector_ori, .keep_all = TRUE) %>% 
  rename(state = state_ori, sector = sector_ori)  %>% 
  select(state, sector, employ)

mu_1999_prime_q2 <- mu_1999_prime_q2 %>%
  left_join(L_2000_temp, by = c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)

L_2000_temp  <- mu_1999_prime_q2  %>% 
  group_by(state_ori, sector_ori)  %>% 
  mutate(employ = sum(level_employ))  %>% 
  ungroup()  %>% 
  distinct(year, state_ori, sector_ori, .keep_all = TRUE) %>% 
  rename(state = state_ori, sector = sector_ori)  %>% 
  select(state, sector, employ)

mu_1999_prime_q1 <- mu_1999_prime_q1 %>%
  left_join(L_2000_temp, by = c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)

mu_1999_prime <- c()
mu_1999_prime <- bind_rows(mu_1999_prime_q1, mu_1999_prime_q2)
mu_1999_prime <- bind_rows(mu_1999_prime, mu_1999_prime_q3)
mu_1999_prime <- bind_rows(mu_1999_prime, mu_1999_prime_q4)
write_csv(mu_1999_prime, file = paste("1-Intermediate_Processed_Data/mu_1999_prime_nber_case1_quarterly.csv", sep=""))

# Recalculating mu_1999 and checking flow 1999-2000
mu_1999_q1 <- mu_1999_prime_q1 %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
long_format_q1  <- mu_1999_q1  %>%  
  mutate(quarter = 1)

mu_1999_q1 <- mu_1999_q1 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999_q1 <- spread(mu_1999_q1, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
A  <- mu_1999_q1[,4:ncol(mu_1999_q1)]
# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999_q1 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_q1, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case1_q1.xlsx", sep=""))

mu_1999_q2 <- mu_1999_prime_q2 %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
long_format_q2  <- mu_1999_q2  %>%  
  mutate(quarter = 2)
#write_xlsx(mu_1999, path = paste("1-Intermediate_Processed_Data/mu_1999_irs_4_long_format.xlsx", sep=""))
mu_1999_q2 <- mu_1999_q2 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999_q2 <- spread(mu_1999_q2, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
B  <- mu_1999_q2[,4:ncol(mu_1999_q2)]
# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999_q2 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_q2, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case1_q2.xlsx", sep=""))

mu_1999_q3 <- mu_1999_prime_q3 %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
long_format_q3  <- mu_1999_q3  %>%  
  mutate(quarter = 3)

mu_1999_q3 <- mu_1999_q3 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999_q3 <- spread(mu_1999_q3, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
C  <- mu_1999_q3[,4:ncol(mu_1999_q3)]
# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999_q3 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_q3, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case1_q3.xlsx", sep=""))

mu_1999_q4 <- mu_1999_prime_q4 %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
long_format_q4  <- mu_1999_q4  %>%  
  mutate(quarter = 4)
#write_xlsx(mu_1999, path = paste("1-Intermediate_Processed_Data/mu_1999_irs_4_long_format.xlsx", sep=""))
mu_1999_q4 <- mu_1999_q4 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999_q4 <- spread(mu_1999_q4, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
D  <- mu_1999_q4[,4:ncol(mu_1999_q4)]
columns  <- mu_1999_q4  %>% 
  select(year, state_ori, sector_ori)

mu_long_format_quarter_case1  <- long_format_q1  %>% 
  bind_rows(long_format_q2)  %>% 
  bind_rows(long_format_q3)  %>% 
  bind_rows(long_format_q4) 

# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999_q4 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_q4, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case1_q4.xlsx", sep=""))

A <- apply(A, c(1, 2), function(x) as.numeric(as.character(x)))
B <- apply(B, c(1, 2), function(x) as.numeric(as.character(x)))
C <- apply(C, c(1, 2), function(x) as.numeric(as.character(x)))
D <- apply(D, c(1, 2), function(x) as.numeric(as.character(x)))
mu_1999_annualise  <- A %*% B %*% C %*% D
mu_1999_annualise  <- bind_cols(mu_1999_annualise, columns)
mu_1999_annualise  <- mu_1999_annualise  %>% 
  select(year, state_ori, sector_ori, everything())

mu_1999_annualise_long_1  <- mu_1999_annualise  %>% 
  pivot_longer(cols = 4:ncol(.), names_to = "state_dest_sector_dest", values_to = "rel")  %>% 
  separate(state_dest_sector_dest, into = c("state_dest", "sector_dest"), sep = "_")   %>% 
  mutate(sector_dest = recode(as.character(sector_dest), '00' ="0", '01' ="1", '02' ="2", '03' ="3", '04' ="4", '05' ="5", '06' ="6", '07' ="7", '08' ="8", '09' ="9" ))

epsilon <- 0.01
check <- mu_1999_annualise %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_annualise, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case1_qr_annualised.xlsx", sep=""))

```

### Quarterly matrix with ACS and CPS (Case 0)

```{r}
# loading intermediate CPS
cps <- read.csv(paste("1-Intermediate_Processed_Data/cps_nber_2_case0_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# loading intermediate ACS
acs <- read.csv(paste("1-Intermediate_Processed_Data/acs_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# Mobility matrices
# disaggregating ACS data using CPS sector_ori info and computation of mobility share
# origin in rows and destination in columns
# row shares sum to 1
acs <- acs %>%
  group_by(year, quarter, state_ori, state_dest) %>%
  mutate(n_acs = sum(n_acs)) %>% # n_acs: for (state_ori, state_dest) pair, n_acs is the total migration summed over all destination sectors
  ungroup() %>%
  distinct(year, quarter, state_ori, state_dest, .keep_all = TRUE) %>%
  select(-sector_dest)  # total migration from state i to state j for each (i,j) combination

# adjusting x's to y's: cps migration pair share times total migration from acs
mobility <- cps %>%
  left_join(acs, by = c('year' = 'year','quarter' = 'quarter', 'state_dest' = 'state_dest', 'state_ori' = 'state_ori')) %>%
  group_by(year, quarter, state_dest, state_ori) %>% 
  mutate(tot_n_cps_accros_sec = sum(n_cps)) %>% # totol within destination state migration (sum over all sector movements)
  ungroup() %>%
  mutate(n_cps_adj = n_cps/tot_n_cps_accros_sec) %>% # migration share across sectors within state (based on destination state)
  mutate(n_cps_adj = ifelse(is.na(n_cps_adj) == TRUE, 0, n_cps_adj)) %>%
  mutate(n_cps_adj = n_cps_adj*n_acs) %>% # use cps within-state across sector migration share times acs total migration across states
  select(-tot_n_cps_accros_sec, -n_cps, -n_acs) 
mu_long_format_quarter_no_adj_case0   <- mobility  %>% 
  group_by(year, quarter, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(mu = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(year, quarter, state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE)
#write_csv(mobility, file = paste("1-Intermediate_Processed_Data/mobility_case0_quarterly.csv", sep=""))

# mu_1999 prime for L_1999
# the second part of this calculation is in the next step since there is an additional proportionality that has to be implemented in L_2000 so that it is consistent with WIOD
mu_1999_prime <- mobility %>%
  filter(year == 1999) %>%
  group_by(year, quarter, state_dest, sector_dest) %>% 
  mutate(tot_n = sum(n_cps_adj)) %>% # total inflows to destination state-sector
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n) %>%  # (inflow share of destination state-sector across original state-sector)rel: share of people from original state-sector pairs to the same destination state-sector
  select(year, quarter, state_dest, state_ori, sector_dest, sector_ori, rel)


mu_1999_prime_q1  <- mu_1999_prime  %>% 
  filter(quarter == 1)
mu_1999_prime_q2  <- mu_1999_prime  %>% 
  filter(quarter == 2)
mu_1999_prime_q3  <- mu_1999_prime  %>% 
  filter(quarter == 3)
mu_1999_prime_q4  <- mu_1999_prime  %>% 
  filter(quarter == 4)

# mu_1999 prime for L_1999
L_2000 <- read.csv(paste("1-Intermediate_Processed_Data/L_2000.csv", sep=""), header = TRUE, sep = ",", dec = ".")
L_2000 <- melt(L_2000, id.vars = c("state"), variable.name = "sector", value.name = "employ")
L_2000 <- L_2000 %>% 
  mutate(sector = as.numeric(gsub("X", "", sector)))

mu_1999_prime_q4 <- mu_1999_prime_q4 %>%
  left_join(L_2000, by=c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)

L_2000_temp  <- mu_1999_prime_q4  %>% 
  group_by(state_ori, sector_ori)  %>% 
  mutate(employ = sum(level_employ))  %>% 
  ungroup()  %>% 
  distinct(year, state_ori, sector_ori, .keep_all = TRUE) %>% 
  rename(state = state_ori, sector = sector_ori)  %>% 
  select(state, sector, employ)

mu_1999_prime_q3 <- mu_1999_prime_q3 %>%
  left_join(L_2000_temp, by = c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)

L_2000_temp  <- mu_1999_prime_q3  %>% 
  group_by(state_ori, sector_ori)  %>% 
  mutate(employ = sum(level_employ))  %>% 
  ungroup()  %>% 
  distinct(year, state_ori, sector_ori, .keep_all = TRUE) %>% 
  rename(state = state_ori, sector = sector_ori)  %>% 
  select(state, sector, employ)

mu_1999_prime_q2 <- mu_1999_prime_q2 %>%
  left_join(L_2000_temp, by = c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)

L_2000_temp  <- mu_1999_prime_q2  %>% 
  group_by(state_ori, sector_ori)  %>% 
  mutate(employ = sum(level_employ))  %>% 
  ungroup()  %>% 
  distinct(year, state_ori, sector_ori, .keep_all = TRUE) %>% 
  rename(state = state_ori, sector = sector_ori)  %>% 
  select(state, sector, employ)

mu_1999_prime_q1 <- mu_1999_prime_q1 %>%
  left_join(L_2000_temp, by = c('state_dest' = 'state', 'sector_dest' = 'sector')) %>% 
  mutate(level_employ = rel*employ) %>%   # generate the 1999 migration flows based on the 2000 distribution and 1999 migration share
  select(-rel, -employ)

mu_1999_prime <- c()
mu_1999_prime <- bind_rows(mu_1999_prime_q1, mu_1999_prime_q2)
mu_1999_prime <- bind_rows(mu_1999_prime, mu_1999_prime_q3)
mu_1999_prime <- bind_rows(mu_1999_prime, mu_1999_prime_q4)
write_csv(mu_1999_prime, file = paste("1-Intermediate_Processed_Data/mu_1999_prime_nber_case0_quarterly.csv", sep=""))

# Recalculating mu_1999 and checking flow 1999-2000
mu_1999_q1 <- mu_1999_prime_q1 %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
long_format_q1  <- mu_1999_q1  %>%  
  mutate(quarter = 1)

mu_1999_q1 <- mu_1999_q1 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999_q1 <- spread(mu_1999_q1, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
A  <- mu_1999_q1[,4:ncol(mu_1999_q1)]
# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999_q1 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_q1, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case0_q1.xlsx", sep=""))

mu_1999_q2 <- mu_1999_prime_q2 %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
long_format_q2  <- mu_1999_q2  %>%  
  mutate(quarter = 2)

mu_1999_q2 <- mu_1999_q2 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999_q2 <- spread(mu_1999_q2, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
B  <- mu_1999_q2[,4:ncol(mu_1999_q2)]
# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999_q2 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_q2, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case0_q2.xlsx", sep=""))

mu_1999_q3 <- mu_1999_prime_q3 %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
long_format_q3  <- mu_1999_q3  %>%  
  mutate(quarter = 3)

mu_1999_q3 <- mu_1999_q3 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999_q3 <- spread(mu_1999_q3, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
C  <- mu_1999_q3[,4:ncol(mu_1999_q3)]
# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999_q3 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_q3, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case0_q3.xlsx", sep=""))

mu_1999_q4 <- mu_1999_prime_q4 %>% 
  dplyr::rename(n_cps_adj = level_employ) %>%
  group_by(year, state_ori, sector_ori) %>% 
  mutate(tot_n_cps_accros_dest = sum(n_cps_adj)) %>% 
  ungroup() %>%
  mutate(rel = n_cps_adj/tot_n_cps_accros_dest) %>% # migration (out) share in 1999
  distinct(state_dest, state_ori, sector_dest, sector_ori, .keep_all = TRUE) %>% 
  select(year, state_dest, state_ori, sector_dest, sector_ori, rel) %>%
  arrange(year, state_ori, sector_ori, state_dest, sector_dest)
long_format_q4  <- mu_1999_q4  %>%  
  mutate(quarter = 4)

mu_1999_q4 <- mu_1999_q4 %>%
  mutate(sector_dest = recode(as.character(sector_dest), '0' ="00", '1' ="01", '2' ="02", '3' ="03", '4' ="04", '5' ="05", '6' ="06", '7' ="07", '8' ="08", '9' ="09" )) %>%
  mutate(state_dest_sector_dest = paste(state_dest, sector_dest, sep="_")) %>%
  select(-state_dest, -sector_dest)
mu_1999_q4 <- spread(mu_1999_q4, state_dest_sector_dest, rel, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
D  <- mu_1999_q4[,4:ncol(mu_1999_q4)]
columns  <- mu_1999_q4  %>% 
  select(year, state_ori, sector_ori)

mu_long_format_quarter_case0  <- long_format_q1  %>% 
  bind_rows(long_format_q2)  %>% 
  bind_rows(long_format_q3)  %>% 
  bind_rows(long_format_q4)

# check sum(prob)==1
epsilon <- 0.01
check <- mu_1999_q4 %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_q4, path = paste("1-Intermediate_Processed_Data/mu_1999_nber_case0_q4.xlsx", sep=""))

A <- apply(A, c(1, 2), function(x) as.numeric(as.character(x)))
B <- apply(B, c(1, 2), function(x) as.numeric(as.character(x)))
C <- apply(C, c(1, 2), function(x) as.numeric(as.character(x)))
D <- apply(D, c(1, 2), function(x) as.numeric(as.character(x)))
mu_1999_annualise  <- A %*% B %*% C %*% D
mu_1999_annualise  <- bind_cols(mu_1999_annualise, columns)
mu_1999_annualise  <- mu_1999_annualise  %>% 
  select(year, state_ori, sector_ori, everything())

mu_1999_annualise_long_0  <- mu_1999_annualise  %>% 
  pivot_longer(cols = 4:ncol(.), names_to = "state_dest_sector_dest", values_to = "rel")  %>% 
  separate(state_dest_sector_dest, into = c("state_dest", "sector_dest"), sep = "_")   %>% 
  mutate(sector_dest = recode(as.character(sector_dest), '00' ="0", '01' ="1", '02' ="2", '03' ="3", '04' ="4", '05' ="5", '06' ="6", '07' ="7", '08' ="8", '09' ="9" ))

#pro_long_0  <- mu_1999_annualise_long_0  %>% 
#  group_by(year, state_ori, sector_ori)  %>% 
#  mutate(chg_state_not_sec_0 = sum(rel[sector_ori == sector_dest & state_ori != state_dest]))  %>% 
#  mutate(chg_sec_not_state_0 = sum(rel[sector_ori != sector_dest & state_ori == state_dest]))  %>%
#  mutate(chg_sec_chg_state_0 = sum(rel[sector_ori != sector_dest & state_ori != state_dest]))  %>%
#  mutate(same_sec_same_state_0 = sum(rel[sector_ori == sector_dest & state_ori == state_dest]))  %>%
#  ungroup()  %>% 
#  distinct(year, state_ori, sector_ori, .keep_all = TRUE)  %>% 
#  select(-state_dest, - sector_dest)
#
#column <- pro_long_0$chg_sec_chg_state_0
#cat("Mean:", mean(column), "\n")
#cat("Maximum:", max(column), "\n")
#cat("Minimum:", min(column), "\n")
#cat("25th Percentile:", quantile(column, 0.25), "\n")
#cat("50th Percentile (Median):", median(column), "\n")
#cat("75th Percentile:", quantile(column, 0.75), "\n")

epsilon <- 0.01
check <- mu_1999_annualise %>% select(-year, -state_ori, -sector_ori)
if(sum(abs(as.matrix(rowSums(check)) - matrix(1, dim(check)[1], 1))) > epsilon) 
  stop("mobility shares do not add to 1")
write_xlsx(mu_1999_annualise, path=paste("1-Intermediate_Processed_Data/mu_1999_nber_case0_qr_annualised.xlsx", sep=""))

```

```{r transition probability at labour market level}
migration_1999_0  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_nber_case0_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")
migration_1999_1  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_nber_case1_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")
migration_1999_2  <- read.csv(file = paste("1-Intermediate_Processed_Data/mu_1999_prime_nber_case2_quarterly.csv", sep=""), header = TRUE, sep = ",", dec = ".")

# Transition probability (at labour market level)
suffixes <- c("0", "1", "2")   # Define a vector of suffixes for the data frames
trans_list <- list()   # Create an empty list to store the results
columns_to_suffix <- c("same_sec_same_state", "chg_state_not_sec", "chg_sec_not_state", "chg_sec_chg_state")

for (suffix in suffixes) {    # Loop over the suffixes and process the data frames
  mobility_temp <- get(paste0("migration_1999_", suffix))
  
  current_df <- mobility_temp %>%
     group_by(year, quarter, state_ori, sector_ori)  %>% 
     mutate(l_1999 = sum(level_employ))  %>% 
     mutate(chg_state_not_sec = sum(level_employ[sector_ori == sector_dest & state_ori != state_dest]))  %>% 
     mutate(chg_sec_not_state = sum(level_employ[sector_ori != sector_dest & state_ori == state_dest]))  %>%
     mutate(chg_sec_chg_state = sum(level_employ[sector_ori != sector_dest & state_ori != state_dest]))  %>%
     mutate(same_sec_same_state = sum(level_employ[sector_ori == sector_dest & state_ori == state_dest]))  %>% 
     ungroup()  %>% 
     mutate(chg_state_not_sec = (chg_state_not_sec/l_1999)*100)  %>% 
     mutate(chg_sec_not_state = (chg_sec_not_state/l_1999)*100)  %>% 
     mutate(chg_sec_chg_state = (chg_sec_chg_state/l_1999)*100)  %>% 
     mutate(same_sec_same_state = (same_sec_same_state/l_1999)*100)  %>% 
     distinct(quarter, state_ori,sector_ori, .keep_all = TRUE)  %>% 
     select(state_ori, sector_ori, quarter,
            chg_state_not_sec, 
            chg_sec_not_state, 
            chg_sec_chg_state, 
            same_sec_same_state)

  colnames( current_df)[colnames( current_df) %in% columns_to_suffix] <-
    paste0(colnames( current_df)[colnames( current_df) %in% columns_to_suffix], "_", suffix)
  
  trans_list[[suffix]] <- current_df
}

transition_prob <- Reduce(function(x, y) left_join(x, y, by = c("state_ori", "sector_ori", "quarter")), trans_list)   # Merge the results into a single data frame
  

new_column_order <- c(
  "state_ori", "sector_ori", "quarter",
  unique(grep("same_sec_same_state_", colnames(transition_prob), value = TRUE)),
  unique(grep("chg_state_not_sec_", colnames(transition_prob), value = TRUE)),
  unique(grep("chg_sec_not_state_", colnames(transition_prob), value = TRUE)),
  unique(grep("chg_sec_chg_state_", colnames(transition_prob), value = TRUE))
)

# Reorder columns
transition_prob <- transition_prob %>%
  select(all_of(new_column_order)) %>% 
  group_by(state_ori, sector_ori)  %>%
  mutate(across(colnames(transition_prob)[4:15], mean))  %>%  # this gives the average of the transitional probability over four quarters
  ungroup()  %>% 
  distinct(state_ori, sector_ori,.keep_all = TRUE)
  
write_xlsx(transition_prob, "1-Intermediate_Processed_Data/transition_prob_quarterly(at state sector level).xlsx")

summary_pro  <- transition_prob  %>% 
  select(-state_ori, -sector_ori, -quarter)  %>% 
  mutate(across(everything(), list(Mean = mean, Max = max, Min = min, p25 = ~quantile(.,probs = 0.25), p50 = ~quantile(.,probs = 0.50), p75 = ~quantile(.,probs = 0.75))))  %>% 
  select(contains("Mean") | contains("Max") | contains("Min") | contains("p25") | contains("p50") | contains("p75"))  %>% 
  distinct()

summary_pro <- summary_pro %>%
  pivot_longer(cols = everything(), 
               names_to = c("state_sector", ".value"), 
               names_sep = "_(?=Mean|Max|Min|p25|p50|p75)") 
write_xlsx(summary_pro, "1-Intermediate_Processed_Data/summary_statistics_quarterly(at state sector level).xlsx")

# Histogram
transition_prob  %>% 
  ggplot() +
  geom_histogram(aes(x = same_sec_same_state_1))

transition_prob  %>% 
  ggplot() +
  geom_histogram(aes(x = same_sec_same_state_2))

```
