---
title: "data_agriculture"
output:
  html_document:
    df_print: paged
    number_sections: yes    
  pdf_document:
    number_sections: yes
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{pifont}
- \usepackage{mathpazo}
- \newcommand{\xmark}{\ding{55}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, include=FALSE, message=FALSE, results='hide', cache=FALSE}
# libraries
remove(list = ls())
# vector of libraries to be used
libs <- c( 'dplyr', 'tidyr', 'readstata13', 'haven', 'stringr', 'nleqslv', 'gdata', 'Statamarkdown', 'formattable', 'reshape', 'ggplot2', 'viridis', 'RColorBrewer', 'reshape2', 'foreign', 'readxl');
#Installing libraries in case they are not installed
#for( i in length(libs)){ 
  #if( !(libs[i] %in% installed.packages()) ) install.packages( libs ) 
#};
#Loading libraries
lapply( libs, require, character.only=TRUE );
```

## Final Objective
To create the file data_agriculture.csv that will contain information about distances between regions, agricultural production for all regions and agricultural consumption for countries.

#importing bases
```{r}
#General parameters
regions <- read_excel("0-Raw_Data/regions.xlsx")
c.names <- regions %>% filter(status=="country", region!="USA")
c.names <- c.names$region

s.names <- regions %>% filter(status=="state") 
s.names <- s.names$region

n.s <- length(s.names)
n.c <- length(c.names)

sector.file <- read_excel("0-Raw_Data/sectors.xlsx")
id.sectors <- sector.file %>% 
  select(final_sector, WIOD_sector) %>%
  distinct(WIOD_sector, .keep_all = TRUE)

#WIOD
WIOD.base <- c()
for (yr in 2000:2007) {
  wiot <- country.country <- read.csv(paste('1-Intermediate_Processed_Data//country_country_step_', yr, '.txt', sep= ""), header = TRUE, sep = ",", dec = ".")
  WIOD.base <- rbind(WIOD.base, wiot)
}
WIOD.full <- read.dta13("1-Intermediate_Processed_Data//wiot_full.dta")
WIOD.full <- WIOD.full %>% 
  left_join(id.sectors, by=c('row_item'='WIOD_sector')) %>%
  mutate(row_item = final_sector) %>%
  select(-final_sector) %>%
  left_join(id.sectors, by=c('col_item'='WIOD_sector')) %>%
  mutate(col_item = final_sector) %>%
  select(-final_sector) %>%
  arrange(year, row_country, col_country, row_item, col_item) %>%
  group_by(year, row_country, col_country, row_item, col_item) %>% #aggregating repeated r-c sequence
  mutate(value1= sum(value)) %>%
  ungroup() %>%
  distinct(year, row_country, col_country, row_item, col_item, .keep_all = TRUE) %>%
  select(-value) %>%
  dplyr::rename(value=value1)

#CENSUS
CENSUS <- read.dta13("1-Intermediate_Processed_Data//state_imports_exports.dta")
state_imp_exp.0 <- CENSUS %>%
  filter(origin!="AllStates", destination!="AllStates")
  
#Agriculture production states
data_agri <- read.csv("0-Raw_Data//Agriculture_Census//data_agriculture.csv")

#Trade distances
data_agriculture <- read.csv("1-Intermediate_Processed_Data//data_services.csv")
data_agriculture <- data_agriculture %>%
  mutate(Y_i=NA, X_j=NA, Y_i.1=NA, Y_i.2=NA)

epsilon <- 0.0001

sector.file <- read_excel("0-Raw_Data/sectors.xlsx")
n.sec <- length(unique(sector.file$final_sector)) -3

```


#State production 
```{r}
#Each state agricultural production is defined as the sum of: i) total exports to other countries (we apply proportionality to Census so that the total US export to country c according to WIOD equals the sum of exports of each state to that country) and ii) the total exports to US states (the sum of these exports across states equals US to US exports in WIOD; this last value is divided between states to obtain ii, according to the Agriculture Census relative state production). 
#Initially, state production (total export) was defined as a fraction of US total export from WIOD, depending on state Agri Census relative production. But, this definition generated some problems, for example, when comparing Alaska's and Illionois's total export to countries with their total export; specifically, the first term was 26 times bigger than the second, when theoretically, the first is a part of the second. This problem may be due to subestimations in their calculation of those states' productions. 
#One way to solve this is to apply the definition used at the beginning, which assumes that the distribution of US total export by state applies as well to US total export to states. One way is to apply this solution only to the states that generate issues, but this would require to apply proportionality again and verify that new problems of the same nature don't arise. Therefore, and for now, the solution will be applied to all states, guaranteeing, by definition, that the issue doesn't occur again. 


##########Component i of state production: export to countries

step3y.1 <- c()
for (yr in 2000:2007) {

#WIOD
WIOD <- subset(WIOD.base, year==yr)
WIOD <- subset(WIOD, select = -year) 


#Base year for exports (2002)
yr.=yr
if(yr<2002){yr.=2002}
state_imp_exp <- data.frame(state_imp_exp.0) %>% 
  filter(year==yr., file=="i in US, j not in US") %>%
  select(-year, -file)
state_imp_exp <-spread(state_imp_exp, origin, value, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
#no trade from US states to SVK in sector 4 in 2002
if(yr<=2002) {row <- c("SVK", 4L, matrix(0, nrow=1, ncol=n.s))
state_imp_exp <- rbind(state_imp_exp, row)}
state_imp_exp$sector <- as.numeric(state_imp_exp$sector)

Base.y <- state_imp_exp %>% 
  arrange(sector, destination) %>%
  filter(sector==(n.sec+2))
colnames(Base.y)= c("importer", "sector", s.names)
Base.y[is.na(Base.y)] <- 0
Base.y <- cbind(Base.y[, 1:2], mapply(Base.y[, 3:dim(Base.y)[2]], FUN=as.numeric))


##################################################

##################################################

yijkBase <- Base.y[, 3:dim(Base.y)[2]] / rowSums(Base.y[, 3:dim(Base.y)[2]]) 

############################### Main variable
#y
df.WIOD = data.frame(WIOD)
df.WIOD <- df.WIOD %>%
  filter(sector==n.sec+2) %>%
  filter(importer!='USA') 

df.WIOD1 <- df.WIOD %>% select(importer, sector, USA)

step3y <- yijkBase*df.WIOD1$USA
step3y <- cbind(df.WIOD1[, 1:2], step3y)

#Check
check= as.matrix(rowSums(step3y[, 3:dim(step3y)[2]]) - df.WIOD1$USA)


##############################
#Correcting if needed
Base.y1 <- melt(Base.y, id.vars=c("importer", "sector"), variable.name="origin", value.name = "value")
Base.y1 <-spread(Base.y1, importer, value, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)

m.correct <- c()
for (sec in (n.sec+2)) {
m <- Base.y1 %>% filter(sector==sec)
m <- (rowSums(m[, 3:dim(m)[2]]) / sum(m[, 3:dim(m)[2]]))
m= t(matrix(replicate(n.c, m), nrow = length(m), ncol = n.c))
m.correct <- rbind(m.correct, m) 
}
m.correct <- m.correct*df.WIOD1$USA

for (r in 1:(dim(check)[1])) {
  if(is.na(check[r])==TRUE){step3y[r, 3:dim(step3y)[2]] = m.correct[r, ]}
}

if(abs(sum(rowSums(step3y[, 3:dim(step3y)[2]]) - df.WIOD1$USA))>epsilon) 
   stop(paste("states' exports to countries != WIOD US exports to countries for", yr, " value=", abs(sum(step3y[, 3:dim(step3y)[2]] - df.WIOD1$value))))
################

step3y <- step3y %>%
  mutate(year=yr) %>%
  select(year, importer, sector, everything()) %>%
  filter(sector==n.sec+2) %>%
  select(-sector)
colnames(step3y) <- c("year", "importer", s.names)

step3y.1 <- rbind(step3y.1, step3y)
}


CENSUS.exp <- melt(step3y.1, id.var=c("year", "importer"), variable.name = "origin")
CENSUS.exp$origin <- as.character(CENSUS.exp$origin)
write.table(CENSUS.exp, file = paste("1-Intermediate_Processed_Data//census.exp.agri.proportionality.csv", sep=""), sep = ",", row.names = FALSE)
state.exports.to.countries <- CENSUS.exp %>%
  group_by(year, origin) %>%
  mutate(exp= sum(value)) %>%
  ungroup() %>%
  distinct(year, origin, .keep_all = TRUE) %>%
  arrange(year, origin)
for (yr in 2000:2007) {
  for (i in 1:n.s) {
    value <- state.exports.to.countries %>%
      filter(year==yr, origin==s.names[i])
    value <- value$exp[1]
    data_agriculture <- data_agriculture %>%
      mutate(Y_i.1 = ifelse(year==yr & iso_o==s.names[i], value, Y_i.1))
  }
}

##########Component ii of state production: export to US states
WIOD.agri <- WIOD.full %>%
  filter(row_country=="USA", col_country=="USA", row_item==(n.sec+2)) %>%
  group_by(year) %>%
  mutate(production= sum(value)) %>%
  ungroup() %>%
  distinct(year, .keep_all = TRUE)

#calculating relative state productions
data_agri <- data_agri %>%
  mutate(Y_i= Y_i/1000) %>%
  group_by(year) %>%
  mutate(tot.produ= sum(Y_i)) %>%
  ungroup() %>%
  mutate(rel= Y_i/tot.produ) 
#checking 
#h=sum(data_agri$rel)

# agricultural production for states (values add to WIOD US-US production)
# 2000-2004 use Agriculture Census 2002
agri.2002 <- data_agri %>% filter(year==2002)
for (i in 1:n.s) {
  num <- agri.2002$rel[i]
  data_agriculture <- data_agriculture %>%
    mutate(Y_i.2= ifelse(year<=2004 & iso_o==agri.2002$iso_o[i], num, Y_i.2))
}
# 2005-2007 use Agriculture Census 2007
agri.2007 <- data_agri %>% filter(year==2007)
for (i in 1:n.s) {
  num <- agri.2007$rel[i]
  data_agriculture <- data_agriculture %>%
    mutate(Y_i.2= ifelse(year>=2005 & iso_o==agri.2007$iso_o[i], num, Y_i.2))
}  
#Applying proportionality
for (yr in 2000:2007) {
  wiod.value <- WIOD.agri %>%
    filter(year==yr)
  wiod.value <- wiod.value$production[1]
  data_agriculture <- data_agriculture %>%
    mutate(Y_i.2= ifelse(year==yr & (iso_o %in% s.names), Y_i.2*wiod.value, Y_i.2))
}

data_agriculture <- data_agriculture %>%
  mutate(Y_i = ifelse( (iso_o %in% s.names), Y_i.1 + Y_i.2, Y_i)) %>%
  select(-Y_i.1, -Y_i.2)

```

#Production and consumption for countries
```{r}
#agricultural production for countries 
WIOD.p <- WIOD.full %>%
  filter(row_item==n.sec+2) %>%
  group_by(year, row_country) %>%
  mutate(production= sum(value)) %>%
  ungroup() %>%
  distinct(year, row_country, .keep_all = TRUE) 
for (i in 1:dim(WIOD.p)[1]) {
  yr=WIOD.p$year[i]
  country=WIOD.p$row_country[i]
  num=WIOD.p$production[i]
  data_agriculture <- data_agriculture %>%
    mutate(Y_i= ifelse(year==yr & iso_o==country, num, Y_i))
}
#agricultural consumption for countries 
WIOD.c <- WIOD.full %>%
  filter(row_item==n.sec+2) %>%
  group_by(year, col_country) %>%
  mutate(consumption= sum(value)) %>%
  ungroup() %>%
  distinct(year, col_country, .keep_all = TRUE) 
for (i in 1:dim(WIOD.c)[1]) {
  yr=WIOD.c$year[i]
  country=WIOD.c$col_country[i]
  num=WIOD.c$consumption[i]
  data_agriculture <- data_agriculture %>%
    mutate(X_j= ifelse(year==yr & iso_d==country, num, X_j))
}

data_agriculture <- data_agriculture %>%
  arrange(year, iso_o, iso_d)

write.table(data_agriculture, file = paste("1-Intermediate_Processed_Data//data_agriculture.csv", sep=""), sep = ",", row.names = FALSE)
```


#### State imports from countries
```{r}
### Base year for imports (2008)
state_imp_exp <- data.frame(state_imp_exp.0) %>% 
  filter(year==2008, file=="i not in US, j in US") %>%
  select(-year, -file)

state_imp_exp <-spread(state_imp_exp, origin, value, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
Base.e <- state_imp_exp %>% 
  arrange(sector, destination) %>%
  filter(sector==n.sec+2)

colnames(Base.e)= c("importer", "sector", c.names)
Base.e[is.na(Base.e)] <- 0

step3e.1 <- c()
for (yr in 2000:2007) {

#WIOD
WIOD <- subset(WIOD.base, year==yr)
WIOD <- subset(WIOD, select = -year) 


##################################################

eijkBase <- melt(Base.e, id.vars=c("importer", "sector"), variable.name="origin", value.name = "value")
eijkBase <-spread(eijkBase, importer, value, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
eijkBase <- eijkBase[, 3:dim(eijkBase)[2]] / rowSums(eijkBase[, 3:dim(eijkBase)[2]]) 


#######################################Main Variable
#e
df.WIOD = data.frame(WIOD)
df.WIOD <- df.WIOD %>%
  filter(sector==n.sec+2) %>%
  filter(importer=='USA')
df.WIOD1 <- df.WIOD %>% select(-USA, -importer, -importer)
colnames(df.WIOD1) <- c("sector", c.names)
df.WIOD1 <- melt(df.WIOD1, id.vars=c("sector"), variable.name="origin", value.name = "value")
df.WIOD1 <- df.WIOD1 %>% arrange(sector, origin)

step3e=eijkBase*df.WIOD1$value
step3e <- cbind(df.WIOD1[, 1:2], step3e)


#Check
check= as.matrix(rowSums(step3e[, 3:dim(step3e)[2]]) - df.WIOD1$value)

##############################
#Correcting if needed
m.correct <- c()
for (sec in (n.sec+2)) {
m <- Base.e %>% filter(sector==sec)
m <- (rowSums(m[, 3:dim(m)[2]]) / sum(m[, 3:dim(m)[2]]))
m= t(matrix(replicate(n.c, m), nrow = length(m), ncol = n.c))
m.correct <- rbind(m.correct, m) 
}
m.correct <- m.correct*df.WIOD1$value

for (r in 1:(dim(check)[1])) {
  if(is.na(check[r])==TRUE){step3e[r, 3:dim(step3e)[2]] = m.correct[r, ]}
}

if(abs(sum(rowSums(step3e[, 3:dim(step3e)[2]]) - df.WIOD1$value))>epsilon) 
   stop(paste("states' imports from countries != WIOD US imports from countries for", yr, " value=", abs(sum(step3e[, 3:dim(step3e)[2]] - df.WIOD1$value))))
################

step3e <- melt(step3e, id.vars=c("origin", "sector"), variable.name="importer", value.name = "value")
step3e <-spread(step3e, origin, value, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)

step3e <- step3e %>%
  mutate(year=yr) %>%
  select(year, importer, sector, everything()) %>%
  select(-sector)
step3e.1 <- rbind(step3e.1, step3e)

}

CENSUS.imp <- melt(step3e.1, id.var=c("year", "importer"), variable.name = "origin")
CENSUS.imp$origin <- as.character(CENSUS.imp$origin)
write.table(CENSUS.imp, file = paste("1-Intermediate_Processed_Data//census.imp.agri.proportionality.csv", sep=""), sep = ",", row.names = FALSE)

```

