---
title: "6-1-Deficits"
output:
  html_document:
    df_print: paged
  pdf_document:
    number_sections: yes
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{pifont}
- \usepackage{mathpazo}
- \newcommand{\xmark}{\ding{55}}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list = ls())
```

```{r warning=FALSE, include=FALSE, message=FALSE, results='hide', cache=FALSE}
# libraries
options( scipen=100, stringsAsFactors=FALSE );
# vector of libraries to be used
libs <- c( 'dplyr', 'tidyr', 'readstata13', 'haven', 'stringr', 'nleqslv', 'gdata', 'Statamarkdown', 'readxl', 'writexl', 'reshape2');
# Install libraries in case they are not installed
for( i in length(libs)){ 
if( !(libs[i] %in% installed.packages()) ) install.packages( libs ) 
};
# Carga de bibliotecas
lapply( libs, require, character.only=TRUE );
```


## Importing datasets to R
```{r}
Base=c()
for (yr in 2000:2007) {
##Final Matrix  
m <- read.csv(paste("1-Intermediate_Processed_Data//final_matrix_", yr, ".csv", sep=""), header = TRUE, sep = ",", dec = ".")

m$year=yr
m <- m %>% select(year, everything())

Base=rbind(Base, m)

}
```


# General Instructions
The purpose of this task is to calculate region-sector level deficits. The deficit for a region $i$ in a sector $k$ would be defined as: 
$$
D_{i,k}=\sum_j X_{ij,k} - \sum_j X_{ji,k}
$$
```{r}
tot.imp <- rowSums(Base[, 4:dim(Base)[2]])

Base1 <- melt(Base, id.vars=c("year", "importer", "sector"), variable.name="exporter", value.name = "value")
Base1 <-spread(Base1, importer, value, fill = NA, convert = TRUE,  drop = TRUE, sep = NULL)
tot.exp <- rowSums(Base1[, 4:dim(Base1)[2]])

#deficit
deficit <- data.frame(tot.exp - tot.imp)
deficit <- cbind(Base[, 1:3], deficit)
colnames(deficit) <- c("year", "importer", "sector", "deficit")

for (yr in 2000:2007) {
  final <- deficit %>% filter(year==yr)
  write.table(final, file = paste("1-Intermediate_Processed_Data//deficits_", yr, ".csv", sep=""), sep = ",", row.names = FALSE)
}

```
