---
title: "Creating bilateral trade in agriculture with Gravity solution"
author: "JP"
date: "April 6, 2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##General description

This file uses the ouputs of the agriculture gravity system that we solved in matlab to create the bilateral trade flow matrix between states in sector 14.

##Data and Libraries
```{r warning=FALSE, include=FALSE, message=FALSE, results='hide', cache=FALSE}
# libraries
remove(list = ls())
options( scipen=100, stringsAsFactors=FALSE );
# vector of libraries to be used
libs <- c( 'dplyr', 'readstata13', 'nleqslv', 'haven', 'tidyverse', 'optimx', 'optimization',
           'optimx', 'tidyr', 'readxl', 'Rcpp', 'DEoptim', 'parallel');
# Install libraries in case they are not installed
for( i in length(libs)){ 
  if( !(libs[i] %in% installed.packages()) ) install.packages( libs ) 
};
# Carga de bibliotecas
lapply( libs, require, character.only=TRUE );
```

```{r warning=FALSE}
# OPTIONS AND LIBRARIES
options( scipen=100 );
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#example vs real
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
## real
# number of countries (n.c) and number of states (n.s)
n.c <- 37; 
n.s <- 50; 
WIOD.base <- read.dta13( file="1-Intermediate_Processed_Data//WIOD_countries.dta" )
data_gravity_agriculture.base <- read.csv( file="1-Intermediate_Processed_Data//data_agriculture.csv", header=TRUE, sep="," )
#state level imports and exports
CENSUS.2 <- read.csv("1-Intermediate_Processed_Data//census.agri.proportionality.csv")
state_imp_exp.0 <- read.dta13("1-Intermediate_Processed_Data//state_imports_exports.dta")
state_imp_exp.0 <- state_imp_exp.0 %>%
  mutate(origin= recode(origin, "New Hampshire"="NewHampshire", "New Jersey"="NewJersey", "New Mexico"="NewMexico", "New York"="NewYork", "North Carolina"="NorthCarolina", "North Dakota"="NorthDakota", "Rhode Island"="RhodeIsland", "South Carolina"="SouthCarolina", "South Dakota"="SouthDakota", "West Virginia"="WestVirginia")) %>%
  mutate(destination= recode(destination, "New Hampshire"="NewHampshire", "New Jersey"="NewJersey", "New Mexico"="NewMexico", "New York"="NewYork", "North Carolina"="NorthCarolina", "North Dakota"="NorthDakota", "Rhode Island"="RhodeIsland", "South Carolina"="SouthCarolina", "South Dakota"="SouthDakota", "West Virginia"="WestVirginia"))
wiot.full <- read.dta13("1-Intermediate_Processed_Data//wiot_full.dta")
wiot.full=data.frame(wiot.full)
wiot.full <- wiot.full %>% 
  filter(year>=2000, col_country!="LUX", col_country!="LVA", col_country!="MLT", row_country!="LUX", row_country!="LVA", row_country!="MLT") %>% #since distances are available from that year on
  mutate(row_country= ifelse(row_country=="ROM", "ROU", row_country)) %>%
  mutate(col_country= ifelse(col_country=="ROM", "ROU", col_country)) 
#CFS
CFS.base <- read_dta("1-Intermediate_Processed_Data//CFS_Xijk.dta")
CFS <- subset(CFS.base, year==2002)
CFS <- subset(CFS, select = -year )

# # ##################example  (do not run creation of dist.matrix in section 3.1)
# ####################Select the block of code that you want to comment. Press Ctrl + Shift + C.
# example <- read_excel( "1-Intermediate_Processed_Data//ejemplo.xlsx")
# WIOD.base <- WIOD.base [1:3, 1:7]
# WIOD.base$value_AUS[2] <- example$`X_{ij}`[1]
# WIOD.base$value_AUS[3] <- example$`X_{ij}`[2]
# WIOD.base$value_AUT[2] <- example$`X_{ij}`[5]
# WIOD.base$value_AUT[3] <- example$`X_{ij}`[6]
# WIOD.base$value_AUS[1] <- example$`X_{ij}`[3] + example$`X_{ij}`[4]
# WIOD.base$value_AUT[1] <- example$`X_{ij}`[7] + example$`X_{ij}`[8]
# WIOD.base$value_USA[2] <- example$`X_{ij}`[9] + example$`X_{ij}`[13]
# WIOD.base$value_USA[3] <- example$`X_{ij}`[10] + example$`X_{ij}`[14]
# WIOD.base$value_USA[1] <- NA
# WIOD.base <- WIOD.base %>%
#   mutate(sector=14)
# data_gravity_agriculture.base <- data_gravity_agriculture.base %>%
#   filter(year==2000, (iso_o=="Alabama" | iso_o=="Alaska" | iso_o=="AUS" | iso_o=="AUT"), (iso_d=="Alabama" | iso_d=="Alaska" | iso_d=="AUS" | iso_d=="AUT") ) %>%
#   mutate(X_j= ifelse(iso_d=="AUS", example$X_j[1], X_j)) %>%
#   mutate(X_j= ifelse(iso_d=="AUT", example$X_j[2], X_j)) %>%
#   mutate(Y_i= ifelse(iso_o=="AUS", example$Y_i[1], Y_i)) %>%
#   mutate(Y_i= ifelse(iso_o=="AUT", example$Y_i[5], Y_i)) %>%
#   mutate(Y_i= ifelse(iso_o=="Alabama", example$Y_i[9], Y_i)) %>%
#   mutate(Y_i= ifelse(iso_o=="Alaska", example$Y_i[13], Y_i))
# data_gravity_agriculture.base$Y_i <- as.numeric((data_gravity_agriculture.base$Y_i))
# data_gravity_agriculture.base$X_j <- as.numeric(as.character(data_gravity_agriculture.base$X_j))
# dist.matrix <- matrix(c(example$phi_ij[11], example$phi_ij[12], example$phi_ij[9], example$phi_ij[10], example$phi_ij[15], example$phi_ij[16], example$phi_ij[13], example$phi_ij[14], example$phi_ij[3], example$phi_ij[4], example$phi_ij[1], example$phi_ij[2], example$phi_ij[7], example$phi_ij[8], example$phi_ij[5], example$phi_ij[6]), nrow=4, ncol=4)
# dist.matrix <- data.frame(dist.matrix)
# colnames(dist.matrix) <- c("1", "2", "3", "4")
# dist.matrix <- matrix(unlist(dist.matrix), ncol = 4, byrow = TRUE)
# n.c <- 2;
# n.s <- 2;
# yr=2000
# CENSUS.2 <- CENSUS.2 %>%
#   filter(year==2000, (origin=="Alabama" | origin=="Alaska"), (importer=="AUS" | importer=="AUT")) %>%
#   mutate(value= ifelse(origin=="Alabama" & importer=="AUS", example$`X_{ij}`[9], value)) %>%
#   mutate(value= ifelse(origin=="Alabama" & importer=="AUT", example$`X_{ij}`[10], value)) %>%
#   mutate(value= ifelse(origin=="Alaska" & importer=="AUS", example$`X_{ij}`[13], value)) %>%
#   mutate(value= ifelse(origin=="Alaska" & importer=="AUT", example$`X_{ij}`[14], value))
# wiot.full <- wiot.full %>%
#   filter(year==2000, (row_country=="AUS" | row_country=="AUT" | row_country=="USA"), (col_country=="AUS" | col_country=="AUT" | col_country=="USA"), row_item==1, col_item==1) %>%
#   mutate(value= ifelse(row_country=="AUS" & col_country=="AUS", WIOD.base$value_AUS[2], value)) %>%
#   mutate(value= ifelse(row_country=="AUS" & col_country=="AUT", WIOD.base$value_AUS[3], value)) %>%
#   mutate(value= ifelse(row_country=="AUS" & col_country=="USA", WIOD.base$value_AUS[1], value)) %>%
#   mutate(value= ifelse(row_country=="AUT" & col_country=="AUS", WIOD.base$value_AUT[2], value)) %>%
#   mutate(value= ifelse(row_country=="AUT" & col_country=="AUT", WIOD.base$value_AUT[3], value)) %>%
#   mutate(value= ifelse(row_country=="AUT" & col_country=="USA", WIOD.base$value_AUT[1], value)) %>%
#   mutate(value= ifelse(row_country=="USA" & col_country=="AUS", WIOD.base$value_USA[2], value)) %>%
#   mutate(value= ifelse(row_country=="USA" & col_country=="AUT", WIOD.base$value_USA[3], value)) %>%
#   mutate(value= ifelse(row_country=="USA" & col_country=="USA", WIOD.base$value_USA[1], value))
# CENSUS.2$value <- as.numeric(CENSUS.2$value)
# # ##############################

# matrix state imports from countries
names.states <- matrix(unique(CFS$importer))
names.countries <- matrix(WIOD.base$importer_country[2:(n.c+1)])
num.states <- n.s
num.countries <- n.c

state_imp_exp <- data.frame(state_imp_exp.0)
state_imp_exp <- subset(state_imp_exp.0, year==2008)
Base.e=c()
sec=c(14)
for (sectors in sec) {
  Base.e0= matrix(0, dim(names.states)[1], dim(names.countries)[1])
  Base.e0=data.frame(Base.e0)
  for (j in 1:(dim(names.states)[1])) {
    for (i in 1:(dim(names.countries)[1])) {
      temp <- state_imp_exp %>%
        filter(sector==sectors, origin==names.countries[i], destination==names.states[j])
      val=temp[1,5]
      Base.e0[j,i]=val
      
    }
  }
  Base.e0 <- Base.e0 %>%
    mutate(importer=names.states, sector=sectors) %>%
    select(importer, sector, everything())
  Base.e <- rbind(Base.e, Base.e0)
}
col=c("importer", "sector", names.countries)
colnames(Base.e)= col
Base.e[is.na(Base.e)] <- 0

#### epsilon to check between calculations
epsilon<-0.001;

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
Looping over years
```{r warning=FALSE}
for (yr in 2000:2007) {
# 1. LOAD DATA
WIOD<-WIOD.base
## WIOD
WIOD <- WIOD.base %>% 
  filter( year==yr, sector==14 ) %>% 
  filter( importer_country!='USA' ) %>% 
  select( -year, -value_USA, -sector, -importer_country, -importer  ) ;
## Gravity data csv format with comma as the separator
data_gravity_agriculture <- data_gravity_agriculture.base %>% 
  filter( year==yr ) %>% 
  select( -year ) %>% 
  mutate( iso_o=as.character(iso_o), iso_d=as.character(iso_d) ) %>% 
  mutate( len_o=ifelse(nchar(iso_o)<4, 'COUNTRY', 'STATE'), 
          len_d=ifelse(nchar(iso_d)<4, 'COUNTRY', 'STATE') );

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 2. NUMBER STATES AND COUNTRIES
# States
id.states <- data_gravity_agriculture %>% 
  filter( len_o=='STATE' ) %>% 
  select( iso_o ) %>% 
  distinct( iso_o ) %>% 
  arrange( iso_o ) %>% 
  mutate( id=row_number() ) %>% 
  dplyr::rename( region=iso_o ) %>% 
  select( id, region );
# Countries
id.countries <- data_gravity_agriculture %>% 
  filter( len_o=='COUNTRY' ) %>% 
  select( iso_o ) %>% 
  distinct( iso_o ) %>% 
  arrange( iso_o ) %>% 
  mutate( id=n.s+row_number() ) %>% 
  dplyr::rename( region=iso_o ) %>% 
  select( id, region );
# Total
id.total <- rbind( id.states, id.countries );
#t(id.total)

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 3. ELEMENTARY MATRICES FOR KRONECKER PRODUCTS

# 3.1. DISTANCE MATRIX
dist.matrix <- data_gravity_agriculture %>% 
  select( iso_o, iso_d, dist ) %>% 
  left_join( y=id.total, by=c('iso_o'='region') ) %>% 
  dplyr::rename( id_o=id ) %>% 
  left_join( y=id.total, by=c('iso_d'='region') ) %>% 
  dplyr::rename( id_d=id ) %>% 
  select( id_o, id_d, dist ) %>% 
  arrange( id_o, id_d ) %>% 
  spread( key=id_d, value=dist );
dist.matrix <- as.matrix( dist.matrix[,2:(n.c+n.s+1)] );

#we use the coefficients from 4-4-Country_Gravity_WIOD.
#own dummy=4.1, Distance elasticity=-1.8
phi<-diag(x = 4.1, n.c+n.s, n.c+n.s);
phi<-exp(phi);
phi<-phi/dist.matrix^1.8; 
dist.matrix<-phi

# 3.2. GDP VECTOR 
gdp.vector <- data_gravity_agriculture %>% 
  select( iso_o, Y_i ) %>% 
  distinct( iso_o, .keep_all=TRUE ) %>% 
  left_join( y=id.total, by=c('iso_o'='region') ) %>% 
  select( id, Y_i ) %>% 
  arrange( id );
gdp.vector <- as.vector( gdp.vector$Y_i );

# 3.3. EXPENDITURE VECTOR 
exp.vector <- data_gravity_agriculture %>% 
  select( iso_d, X_j ) %>% 
  distinct( iso_d, .keep_all=TRUE ) %>% 
  left_join( y=id.total, by=c('iso_d'='region') ) %>% 
  select( id, X_j ) %>% 
  arrange( id );
exp.vector <- as.vector( exp.vector$X_j );

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 4. BIG MATRICES

# 4.1 Matrices X and Y (repeat gdp and expenditure vectors in ns+nc rows)
mat.Y <- matrix( data=rep(gdp.vector, (n.s+n.c)), nrow=(n.s+n.c), byrow=TRUE );
mat.X <- matrix( data=rep(exp.vector, (n.s+n.c)), nrow=(n.s+n.c), byrow=TRUE );

# 4.2 Submatrices
##phi*Y submatrices
phi.Y.ss <- dist.matrix[(1:n.s), (1:n.s)] * mat.Y[(1:n.s), (1:n.s)];
phi.Y.sc <- dist.matrix[(1:n.s), ((n.s+1):(n.s+n.c))] * mat.Y[(1:n.s), ((n.s+1):(n.s+n.c))];
#phi.Y.cs <- dist.matrix[((n.s+1):(n.s+n.c)), (1:n.s)] * mat.Y[((n.s+1):(n.s+n.c)), (1:n.s)];
phi.Y.cc <- dist.matrix[((n.s+1):(n.s+n.c)), ((n.s+1):(n.s+n.c))] * 
  mat.Y[((n.s+1):(n.s+n.c)), ((n.s+1):(n.s+n.c))];
## phi*X submatrices
#phi.X.ss <- dist.matrix[(1:n.s), (1:n.s)] * mat.X[(1:n.s), (1:n.s)];
phi.X.sc <- dist.matrix[(1:n.s), ((n.s+1):(n.s+n.c))] * mat.X[(1:n.s), ((n.s+1):(n.s+n.c))];
#phi.X.cs <- dist.matrix[((n.s+1):(n.s+n.c)), (1:n.s)] * mat.X[((n.s+1):(n.s+n.c)), (1:n.s)];
phi.X.cc <- dist.matrix[((n.s+1):(n.s+n.c)), ((n.s+1):(n.s+n.c))] * 
  mat.X[((n.s+1):(n.s+n.c)), ((n.s+1):(n.s+n.c))];


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 5. WIOD MATRIX AND RELATED QUANTITIES

## 5.1 WIOD matrix (d,o)
wiod.matrix <- as.matrix( WIOD );

## 5.2 lambda vector
### imports and exports of countries to countries
exports.to.countries <- as.matrix( apply(X=wiod.matrix, MARGIN=2, FUN=sum) )

wiot.full.c <- wiot.full %>%
  filter(col_country!="USA", row_country!="USA", row_item==1) %>%
  group_by(year, col_country) %>%
  mutate(consumption= sum(value)) %>%
  ungroup() %>%
  distinct(year, col_country, .keep_all = TRUE) 
wiot.full.c <- wiot.full.c %>%
  filter(year==yr) %>%
  arrange(col_country)
imports.from.countries <- matrix(wiot.full.c$consumption);


### shares of imports and exports of countries
X_c <- as.matrix( exp.vector[(n.s+1):(n.s+n.c)] );
Y_s <- as.matrix( gdp.vector[(1):(n.s)] );
Y_c <- as.matrix( gdp.vector[(n.s+1):(n.s+n.c)] );

state.exports.to.countries <- CENSUS.2 %>%
  filter(year==yr) %>%
  group_by(origin) %>%
  mutate(exp= sum(value)) %>%
  ungroup() %>%
  distinct(origin, .keep_all = TRUE) %>%
  arrange(origin)
state.exports.to.countries <- matrix(state.exports.to.countries$exp)


### lambdas and chis
lambda.cj <- imports.from.countries/ X_c;
chi.si <- state.exports.to.countries/Y_s;
chi.ci <- exports.to.countries/Y_c;
### lambda vector
ones.ns <- matrix( data=rep(1, n.s), nrow=n.s, ncol=1 );
lambda_vector <- rbind( ones.ns, lambda.cj, chi.si, chi.ci );

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
## 6.1 Big zeros matrices
zeros.nc.ns <- matrix( data=rep(0, n.c*n.s), nrow=n.c, ncol=n.s );
zeros.ns.ns <- matrix( data=rep(0, n.s*n.s), nrow=n.s, ncol=n.s );
zeros.big <- matrix( data=rep(0, (n.s+n.c)*(n.s+n.c)), nrow=(n.s+n.c), ncol=(n.s+n.c) );

## 6.2 GIANT MATRIX 
### Block for system 10
block.10 <- rbind( cbind(phi.Y.ss, phi.Y.sc),
                   cbind(zeros.nc.ns, phi.Y.cc) );
### Block for system 11
block.11 <- rbind( cbind(zeros.ns.ns, phi.X.sc),
                   cbind(zeros.nc.ns, phi.X.cc) );
### Relevant matrix
BIG.MAT <- rbind( cbind(zeros.big, block.10),
                  cbind(block.11, zeros.big) );

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
###SOLUTION FROM MATLAB
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SOL <- read_xls(paste('1-Intermediate_Processed_Data//vec_agric_solution_',yr, '.xls', sep=""),col_names=FALSE)
SOL <- as.matrix(SOL)
#checking
value <-  lambda_vector*SOL - BIG.MAT %*% SOL^{-1};
if(norm(value, "2")>epsilon) 
  stop(paste("Solution from Matlab does not seem to work for year", yr))

x<- SOL;
##calculating Xij
  #x<-as.matrix( c(normalization,x) )
### Basic vector
P.s <- as.matrix( x[1:n.s] );
P.c <- as.matrix( x[(n.s+1):(n.s+n.c)] );
Pi.s <- as.matrix( x[(n.s+n.c+1):(2*n.s+n.c)] );
Pi.c <- as.matrix( x[(2*n.s+n.c+1):(2*(n.s+n.c))] );

### Inverted basic
P.s.inv <- P.s^(-1); 
P.c.inv <- P.c^(-1);
Pi.s.inv <- Pi.s^(-1);
Pi.c.inv <- Pi.c^(-1);

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 7. Proportionality with CENSUS imports/exports data

#modifying exp vector since states' expenditure was NA and this vec is needed for the bilat flow 
#X_j, j \in US

#calculating states' imports from countries
#WIOD
WIOD. <- subset(WIOD.base, year==yr)
WIOD. <- subset(WIOD., select = -year) 
##################################################
# SHARES
df.base=(Base.e)
m2=c()
sum_country=c()
sum_countrym=c()
sec_relevant=c(14)
for(k in sec_relevant) {
  df.base1 <- df.base %>%
    filter(sector==k)
  df.base1=df.base1[1:50, 3:dim(df.base1)[2]]
  colsum=(matrix(colSums(df.base1))) #as column
  m2=rbind(m2,df.base1)
  sum_country=matrix(replicate(50,colsum), nrow= length(colsum), ncol = num.states)
  sum_countrym=rbind(sum_countrym, t(sum_country))
}
eijkBase=m2/sum_countrym
#######################################Main Varibale
#PROPORTIONALITY
df.WIOD = data.frame(WIOD.)
df.WIOD <- df.WIOD %>%
  filter(sector==14) %>%
  filter(importer_country=='USA')
  
df.WIOD1 <- df.WIOD %>% select(-value_USA, -importer, -importer_country, -sector)

sum_country02=c()
relevant=c(1) #13 doesnt refer to sector 13 but sector 14 in position 13
for (i in relevant) {
  q1=t(df.WIOD1[i,])
  sum_country2=t(matrix(replicate(50,q1), nrow = length(q1), ncol = num.states))
  sum_country02=rbind(sum_country02, sum_country2)
}

imports.state.country.prop=eijkBase*sum_country02

#getting the names (that's the only purpose of the CFS file)
df.CFS = data.frame(CFS)
df.CFS <- df.CFS %>%
  filter(sector==1)
imports.state.country.prop$sector = df.CFS$sector[1:50]
imports.state.country.prop$importer = df.CFS$importer[1:50]
imports.state.country.prop = imports.state.country.prop %>% select(importer, sector, everything())

#Check that proportionality calculation adds up to WIOD
# X_i,US from wiod
df.WIOD = data.frame(WIOD.)
df.WIOD <- df.WIOD %>%
  filter(sector==14) %>%
  filter(importer_country=='USA')
df.WIOD1 <- df.WIOD %>% select(-value_USA, -importer, -importer_country, -sector)
check.WIOD.e <- df.WIOD1
# X_i,US from census + proportionality
  check.imports.state.country.prop = imports.state.country.prop[3:dim(imports.state.country.prop)[2]]
  check.imports.state.country.prop = colSums(check.imports.state.country.prop)
#checking X_i,US from wiod= X_i,US from census + proportionality
check=check.imports.state.country.prop-check.WIOD.e
if(abs(sum(check))>epsilon) 
  print(paste("Proportionality for imports does not square for all states. Applying correction for year", yr))


##############################
#Correcting if needed (in case CENSUS has zero imports to USA but WIOD has imports)
if( is.na(sum(check))== TRUE) {
  for (r in 1:(dim(check)[1])) {
    for (c in 1:dim(check)[2]) {
      if(is.na(check[r,c])== TRUE){
        correc.m=m2[(((r-1)*50)+1):((((r-1)*50)+1) + 49),] 
        correc.denom=sum(correc.m)
        correct.num=rowSums(correc.m)
        correc=correct.num/correc.denom
        eijkBase[(((r-1)*50)+1):((((r-1)*50)+1) + 49),c]=correc
      }
    }
  }
  
  imports.state.country.prop=eijkBase*sum_country02
  df.CFS = data.frame(CFS)
  df.CFS <- df.CFS %>%
    filter(sector==1)
  imports.state.country.prop$sector = df.CFS$sector[1:50]
  imports.state.country.prop$importer = df.CFS$importer[1:50]
  imports.state.country.prop = imports.state.country.prop %>% select(importer, sector, everything())
  imports.state.country.prop= imports.state.country.prop

    check.imports.state.country.prop = imports.state.country.prop[imports.state.country.prop$sector==1, 3:dim(imports.state.country.prop)[2]]
    vec1=check.imports.state.country.prop
    check.imports.state.country.prop = colSums(check.imports.state.country.prop)
    c=rbind(c, check.imports.state.country.prop)

  check=c-check.WIOD.e
  
  }
if(abs(sum(check))>epsilon) 
  stop(paste("Proportionality does not seem to work for year", yr))


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 8. CREATING X_J FOR STATES
# 
xj.us <- WIOD.base %>%
  filter(sector==14, year==yr, importer_country=="USA") %>%
  select(-importer, -importer_country, -sector, -year)
xj.us<-sum(xj.us)

imports.state.country.prop <- imports.state.country.prop %>%
  select(-sector, -importer)

tau.mod <- (dist.matrix[(1:n.s), ((n.s+1):(n.s+n.c))])^(-1)
tau.mod2 <- (t(dist.matrix[((n.s+1):(n.s+n.c)),(1:n.s)]))^(-1)
#checking that dist between i and j = dist between j and i
stopifnot(norm(tau.mod-tau.mod2)<epsilon)

p.mod <-matrix( data=rep(c(Pi.s), (n.c)),
                     nrow=(n.s), ncol=(n.c), byrow=FALSE );
denom <- matrix(colSums(tau.mod*p.mod*imports.state.country.prop));
denom <-matrix( data=rep(c(denom), (n.s)),
                     nrow=(n.s), ncol=(n.c), byrow=TRUE );
num<-tau.mod*p.mod*imports.state.country.prop;
s= as.data.frame(rowSums(num/denom));
# X_j for US
X_j.mod.s <- (n.c^(-1))*xj.us*s

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 8. CREATING X_J FOR STATES
### LHS %*% vector of X_j for USA 
#sum over states
Pi.vec.states <- matrix( data=rep(Pi.s.inv*gdp.vector[1:n.s], (n.s)),
                     nrow=(n.s), ncol=(n.s), byrow=FALSE );
taus <- ((dist.matrix[(1:(n.s)),((1):(n.s))]))
LHS.1 <- t(matrix(colSums(taus*Pi.vec.states)));
# imports from countries
Pi.vec.countries <- matrix( data=rep(Pi.c.inv*gdp.vector[(n.s+1):(n.s+n.c)], (n.s)),
                     nrow=(n.c), ncol=(n.s), byrow=FALSE );
taus <- ((dist.matrix[((n.s+1):(n.s+n.c)),(1:n.s)]))
LHS.2<-data.matrix(taus*Pi.vec.countries);
# total sum
LHS.3<-t(P.s)
LHS<-rbind(LHS.1,LHS.2,LHS.3);
### RHS (WIOD_US,US , imports by country to US, X^WIOD_US)
#WIOD_US,US
RHS.1 <- WIOD.base %>%
  filter(year==yr, sector==14, importer_country=="USA")
RHS.1 <- RHS.1$value_USA[1];
#imports from countries
RHS.2 <- WIOD.base %>%
  filter(year==yr, sector==14, importer_country=="USA") %>%
  select(-year, -importer, -importer_country, -sector, - value_USA)
RHS.2 <-data.matrix(t(RHS.2));
#total expenditure US
RHS.3 <- WIOD.base %>%
  filter(sector==14, year==yr, importer_country=="USA") %>%
  select(-importer, -importer_country, -sector, -year)
RHS.3<-sum(RHS.3);
RHS<-rbind(RHS.1,RHS.2,RHS.3);
##### system to minimize
fr <- function( x ) {   
  #consumption of US from US matches WIOD
    entry.1<-((LHS.1%*%x/RHS.1-1)*100)^2;
  #total imports
    entry.2<-((sum(LHS.2%*%x)/sum(RHS.2)-1)*100)^2;
  #total consumption of US  
    entry.3<-((LHS.3%*%x/RHS.3-1)*100)^2;
  sum(rbind(entry.1, entry.2, entry.3))
}

optimal.model <- optimx( par=as.vector(as.matrix(P.s.inv*X_j.mod.s)), fn=fr,
                         lower=rep(0.00001, n.s), upper=rep(1000000000000, n.s),
                         control=list(maxit=100000, eps=1.0E-20));
#checking
if(as.numeric( optimal.model$value )>epsilon) 
  stop(paste("Cannot find a solution for X_j states for year", yr))

solu<-t(as.matrix(optimal.model[1:50]));
X_j.mod.s<-P.s*solu;

#we compute the X_j of the states only. 
x_j.c.wiod<- matrix(exp.vector[(n.s+1):(n.s+n.c)]);
names(X_j.mod.s)<-"V1"
X_j.mod <- as.matrix(rbind(X_j.mod.s,x_j.c.wiod));
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 9. COMPUTING BILATERAL FLOWS

#Calculating flows 
Pi.sq.mat <- matrix( data=rep(c(Pi.s.inv, Pi.c.inv)*gdp.vector, (n.s+n.c)),
                     nrow=(n.s+n.c), ncol=(n.s+n.c), byrow=TRUE );
P.sq.mat <- matrix( data=rep(c(P.s.inv, P.c.inv)*X_j.mod, (n.s+n.c)),
                    nrow=(n.s+n.c), ncol=(n.s+n.c), byrow=FALSE );
#consistent with WIOD notation
Xij.matrix <- Pi.sq.mat * dist.matrix * P.sq.mat;
write.csv(Xij.matrix, file= paste('1-Intermediate_Processed_Data\\Xij_matrix_agric_', yr, '.csv', sep= ""), row.names=FALSE, na="" );

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 10. FINAL CHECKS

#CHECK: SUM OF X_j.mod.s FOR US STATES =US X_j from WIOD
xj.us <- WIOD.base %>%
  filter(sector==14, year==yr, importer_country=="USA") %>%
  select(-importer, -importer_country, -sector, -year)
#checking
if(sum(X_j.mod.s)/sum(xj.us)-1>epsilon) 
  stop(paste("SUM OF X_j.mod.s FOR US STATES !=US X_j from WIOD for", yr, " value=", sum(X_j.mod.s)/sum(xj.us)-1))

#Check: states' exports to countries add to WIOD US exports to countries (sector 14)
value1 <- sum(Xij.matrix[((n.s+1):(n.s+n.c)), (1:n.s)])
value2 <- WIOD.base %>%
  filter(year==yr, sector==14, importer_country!="USA")
value2 <- sum(value2$value_USA)
if(abs(value1/value2-1)>epsilon) 
  stop(paste("states' exports to countries != WIOD US exports to countries for", yr, " value=", abs(value1/value2-1)))

#Check: countries' exports to countries add to WIOD countries' exports to countries (sector 14)
value1 <- sum(Xij.matrix[((n.s+1):(n.s+n.c)), ((n.s+1):(n.s+n.c))])
value2 <- WIOD.base %>%
  filter(year==yr, sector==14, importer_country!="USA") %>%
  select(-year, -importer, -importer_country, -sector, - value_USA)
value2 <- sum(value2)
if(abs(value1/value2-1)>epsilon) 
  stop(paste("countries' exports to countries != WIOD countries' exports to countries for", yr, " value=", abs(value1/value2-1)))


#Check: states' imports from countries add to WIOD US imports from countries (sector 14)
value1 <- sum(Xij.matrix[(1:n.s), ((n.s+1):(n.s+n.c))])
value2 <- WIOD.base %>%
  filter(year==yr, sector==14, importer_country=="USA") %>%
  select(-year, -importer, -importer_country, -sector, - value_USA)
value2 <- sum(value2)
if(abs(value1/value2-1)>epsilon) 
  stop(paste("states' imports from countries != WIOD US imports from countries for", yr, " value=", abs(value1/value2-1)))


#Check: states' exports to states add to WIOD US exports to US (sector 14)
value1 <- sum(Xij.matrix[(1:n.s), (1:n.s)])
value2 <- WIOD.base %>%
  filter(year==yr, sector==14, importer_country=="USA")
value2 <- value2$value_USA[1]
if(abs(value1/value2-1)>epsilon) 
  stop(paste("states' exports to states != WIOD US exports to US for", yr, " value=", abs(value1/value2-1)))

}
```
