---
title: "Creating bilateral trade in services with Gravity solution"
author: "JP"
date: "September 9, 2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##General description

This file generates the inputs of the gravity system that we take to solve in matlab.

##Data and Libraries
```{r warning=FALSE, include=FALSE, message=FALSE, results='hide', cache=FALSE}
# libraries
remove(list = ls())
options( scipen=100, stringsAsFactors=FALSE );
# vector of libraries to be used
libs <- c( 'dplyr', 'readstata13', 'nleqslv', 'haven', 'tidyverse', 'optimx', 'optimization',
           'optimx', 'tidyr', 'readxl', 'Rcpp', 'DEoptim', 'parallel');
# Install libraries in case they are not installed
for( i in length(libs)){ 
  if( !(libs[i] %in% installed.packages()) ) install.packages( libs ) 
};
# Carga de bibliotecas
lapply( libs, require, character.only=TRUE );
```

```{r warning=FALSE, include=FALSE, message=FALSE, results='hide', cache=FALSE}
# OPTIONS AND LIBRARIES
options( scipen=100 );
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Data
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
## real
# number of countries (n.c) and number of states (n.s)
n.c <- 37; 
n.s <- 50; 
WIOD.base <- read.dta13( file="2-Final_Data\\WIOD_countries.dta" )
data_gravity_services.base <- read.csv( file="2-Final_Data\\data_services.csv", header=TRUE, sep="," )
 

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for (yr in 2000:2007) {
# 1. LOAD DATA
WIOD<-WIOD.base
## path
## WIOD US
us.us.wiod <- WIOD %>% 
  filter( year==yr, sector==13 ) %>% 
  filter( importer_country=='USA' ) %>% 
  select( value_USA );
us.us.wiod <- as.numeric(us.us.wiod[1]);
# US exports
us.exports.wiod <- WIOD %>% 
  filter( year==yr, sector==13 ) %>% 
  filter( importer_country!='USA' ) %>% 
  select( value_USA ); 
#us.exports.wiod <-sum(us.exports.wiod)
# US imports
us.imports.wiod <- WIOD %>% 
  filter( year==yr, sector==13 ) %>% 
  filter( importer_country=='USA' ) %>% 
  select( -year, -value_USA, -sector, -importer_country, -importer  ) ;
#us.imports.wiod <-sum(us.imports.wiod)
## WIOD
WIOD <- WIOD.base %>% 
  filter( year==yr, sector==13 ) %>% 
  filter( importer_country!='USA' ) %>% 
  select( -year, -value_USA, -sector, -importer_country, -importer  ) ;
## Gravity data csv format with comma as the separator
data_gravity_services <- data_gravity_services.base %>% 
  filter( year==yr ) %>% 
  select( -year ) %>% 
  mutate( iso_o=as.character(iso_o), iso_d=as.character(iso_d) ) %>% 
  mutate( len_o=ifelse(nchar(iso_o)<4, 'COUNTRY', 'STATE'), 
          len_d=ifelse(nchar(iso_d)<4, 'COUNTRY', 'STATE') );

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 2. NUMBER STATES AND COUNTRIES
# States
id.states <- data_gravity_services %>% 
  filter( len_o=='STATE' ) %>% 
  select( iso_o ) %>% 
  distinct( iso_o ) %>% 
  arrange( iso_o ) %>% 
  mutate( id=row_number() ) %>% 
  rename( region=iso_o ) %>% 
  select( id, region );
# Countries
id.countries <- data_gravity_services %>% 
  filter( len_o=='COUNTRY' ) %>% 
  select( iso_o ) %>% 
  distinct( iso_o ) %>% 
  arrange( iso_o ) %>% 
  mutate( id=n.s+row_number() ) %>% 
  rename( region=iso_o ) %>% 
  select( id, region );
# Total
id.total <- rbind( id.states, id.countries );
t(id.total)

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 3. ELEMENTARY MATRICES FOR KRONECKER PRODUCTS

# 3.1. DISTANCE MATRIX
dist.matrix <- data_gravity_services %>% 
  select( iso_o, iso_d, dist ) %>% 
  left_join( y=id.total, by=c('iso_o'='region') ) %>% 
  rename( id_o=id ) %>% 
  left_join( y=id.total, by=c('iso_d'='region') ) %>% 
  rename( id_d=id ) %>% 
  select( id_o, id_d, dist ) %>% 
  arrange( id_o, id_d ) %>% 
  spread( key=id_d, value=dist );
dist.matrix <- as.matrix( dist.matrix[,2:(n.c+n.s+1)] );

#Phis
#we use the coefficients from 4-4-Country_Gravity_Services_WIOD.
#own dummy=6.5, Distance elasticity=0.7
phi<-diag(x = 6.5, n.c+n.s, n.c+n.s);
phi<-exp(phi);
phi<-phi/dist.matrix^0.7;
dist.matrix<-phi

# 3.2. GDP VECTOR
gdp.vector <- data_gravity_services %>% 
  select( iso_o, Y_i ) %>% 
  distinct( iso_o, .keep_all=TRUE ) %>% 
  left_join( y=id.total, by=c('iso_o'='region') ) %>% 
  select( id, Y_i ) %>% 
  arrange( id );
gdp.vector <- as.vector( gdp.vector$Y_i );

# 3.3. EXPENDITURE VECTOR
exp.vector <- data_gravity_services %>% 
  select( iso_d, X_j ) %>% 
  distinct( iso_d, .keep_all=TRUE ) %>% 
  left_join( y=id.total, by=c('iso_d'='region') ) %>% 
  select( id, X_j ) %>% 
  arrange( id );
exp.vector <- as.vector( exp.vector$X_j );

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 4. BIG MATRICES

# 4.1 Matrices X and Y (repeat gdp and expenditure vectors in ns+nc rows)
mat.Y <- matrix( data=rep(gdp.vector, (n.s+n.c)), nrow=(n.s+n.c), byrow=TRUE );
mat.X <- matrix( data=rep(exp.vector, (n.s+n.c)), nrow=(n.s+n.c), byrow=TRUE );

# 4.2 Submatrices
##phi*Y submatrices
phi.Y.ss <- dist.matrix[(1:n.s), (1:n.s)] * mat.Y[(1:n.s), (1:n.s)];
phi.Y.sc <- dist.matrix[(1:n.s), ((n.s+1):(n.s+n.c))] * mat.Y[(1:n.s), ((n.s+1):(n.s+n.c))];
phi.Y.cs <- dist.matrix[((n.s+1):(n.s+n.c)), (1:n.s)] * mat.Y[((n.s+1):(n.s+n.c)), (1:n.s)];
phi.Y.cc <- dist.matrix[((n.s+1):(n.s+n.c)), ((n.s+1):(n.s+n.c))] * 
  mat.Y[((n.s+1):(n.s+n.c)), ((n.s+1):(n.s+n.c))];
## phi*X submatrices
phi.X.ss <- dist.matrix[(1:n.s), (1:n.s)] * mat.X[(1:n.s), (1:n.s)];
phi.X.sc <- dist.matrix[(1:n.s), ((n.s+1):(n.s+n.c))] * mat.X[(1:n.s), ((n.s+1):(n.s+n.c))];
phi.X.cs <- dist.matrix[((n.s+1):(n.s+n.c)), (1:n.s)] * mat.X[((n.s+1):(n.s+n.c)), (1:n.s)];
phi.X.cc <- dist.matrix[((n.s+1):(n.s+n.c)), ((n.s+1):(n.s+n.c))] * 
  mat.X[((n.s+1):(n.s+n.c)), ((n.s+1):(n.s+n.c))];


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 5. WIOD MATRIX AND RELATED QUANTITIES

## 5.1 WIOD matrix (d,o)
wiod.matrix <- as.matrix( WIOD );

## 5.2 lambda vector

### imports and exports
imports.from.countries <- as.matrix( apply(X=wiod.matrix, MARGIN=1, FUN=sum) );
exports.to.countries <- as.matrix( apply(X=wiod.matrix, MARGIN=2, FUN=sum) )
### shares of imports and exports of countries
X_c <- as.matrix( exp.vector[(n.s+1):(n.s+n.c)] );
Y_c <- as.matrix( gdp.vector[(n.s+1):(n.s+n.c)] );
### lambdas
lambda.p <- (X_c-imports.from.countries) / X_c;
lambda.pi <-(Y_c- exports.to.countries) / Y_c;
### lambda vector
ones.ns <- matrix( data=rep(1, n.s), nrow=n.s, ncol=1 );
lambda_vector <- rbind( ones.ns, lambda.p, ones.ns, lambda.pi );

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
## 6.1 Big zeros matrices
zeros.nc.nc <- matrix( data=rep(0, n.c*n.c), nrow=n.c, ncol=n.c );
zeros.big <- matrix( data=rep(0, (n.s+n.c)*(n.s+n.c)), nrow=(n.s+n.c), ncol=(n.s+n.c) );

## 6.2 GIANT MATRIX 
### Block for system 10
block.10 <- rbind( cbind(phi.Y.ss, phi.Y.sc),
                   cbind(phi.Y.cs, zeros.nc.nc) );
### Block for system 11
block.11 <- rbind( cbind(phi.X.ss, phi.X.sc),
                   cbind(phi.X.cs, zeros.nc.nc) );
### Relevant matrix
BIG.MAT <- rbind( cbind(zeros.big, block.10),
                  cbind(block.11, zeros.big) );

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
###SOLUTION FROM MATLAB
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SOL <- read_xls(paste('1-Intermediate_Processed_Data\\vector_solution_',yr, '.xls', sep=""),col_names=FALSE)
SOL <- as.matrix(SOL)
#checking
value <-  lambda_vector*SOL - BIG.MAT %*% SOL^{-1};
norm(value, "2")
x<- SOL;
##calculating Xij
  #x<-as.matrix( c(normalization,x) )
### Basic vector
P.s <- as.matrix( x[1:n.s] );
P.c <- as.matrix( x[(n.s+1):(n.s+n.c)] );
Pi.s <- as.matrix( x[(n.s+n.c+1):(2*n.s+n.c)] );
Pi.c <- as.matrix( x[(2*n.s+n.c+1):(2*(n.s+n.c))] );

### Inverted basic
P.s.inv <- P.s^(-1); 
P.c.inv <- P.c^(-1);
Pi.s.inv <- Pi.s^(-1);
Pi.c.inv <- Pi.c^(-1);

Pi.sq.mat <- matrix( data=rep(c(Pi.s.inv, Pi.c.inv)*gdp.vector, (n.s+n.c)),
                     nrow=(n.s+n.c), ncol=(n.s+n.c), byrow=TRUE );
P.sq.mat <- matrix( data=rep(c(P.s.inv, P.c.inv)*exp.vector, (n.s+n.c)),
                    nrow=(n.s+n.c), ncol=(n.s+n.c), byrow=FALSE );
#consistent with WIOD notation
Xij.matrix <- Pi.sq.mat * dist.matrix * P.sq.mat;
write.csv(Xij.matrix, file= paste('1-Intermediate_Processed_Data\\Xij_matrix_services_', yr, '.csv', sep= ""), row.names=FALSE, na="" );
}
```
