---
title: "Checks WIOD"
output:
  html_document:
    df_print: paged
  pdf_document:
    number_sections: yes
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{pifont}
- \usepackage{mathpazo}
- \newcommand{\xmark}{\ding{55}}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list = ls())
```

```{r warning=FALSE, include=FALSE, message=FALSE, results='hide', cache=FALSE}
# libraries
options( scipen=100, stringsAsFactors=FALSE );
# vector of libraries to be used
libs <- c( 'dplyr', 'tidyr', 'readstata13', 'haven', 'stringr', 'nleqslv', 'gdata', 'Statamarkdown', 'reshape2');
# Install libraries in case they are not installed
for( i in length(libs)){ 
  if( !(libs[i] %in% installed.packages()) ) install.packages( libs ) 
};
# Carga de bibliotecas
lapply( libs, require, character.only=TRUE );
```

# General Instructions

The final goal is to check that the final trade matrices are consistent with WIOD database.

## Importing datasets to R
```{r}
regions <- read_excel("0-Raw_Data/regions.xlsx")
c.names <- regions %>% filter(status=="country", region!="USA")
c.names <- c.names$region

s.names <- regions %>% filter(status=="state") 
s.names <- s.names$region

n.s <- length(s.names)
n.c <- length(c.names)

#Final WIOD
WIOD.base <- read.dta13( file="1-Intermediate_Processed_Data//WIOD_countries.dta" )
colnames(WIOD.base) <- c("year", "importer_country", "sector", "importer", "USA", c.names)


CDP.base <- c()
#Final matrices 
for (yr in 2000:2007) {
##Gravity step: services  
matrix <- read.csv(paste("1-Intermediate_Processed_Data//final_matrix_", yr, ".csv", sep=""), header = TRUE, sep = ",", dec = ".")
matrix$year <- yr
matrix <- matrix %>% select(year, everything())

CDP.base <- rbind(CDP.base, matrix)
}

#
epsilon <- 0.0001
```


#Checks
```{r}
for (yr in 2000:2007) {

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#country-country  
wiot <- melt(WIOD.base, id.vars=c("year", "importer_country", "sector", "importer"), variable.name="exporter", value.name = "value")
wiot.cc <- wiot %>%
  filter(year==yr, importer_country %in% c.names, exporter %in% c.names) %>%
  arrange(sector, exporter, importer)

CDP <- melt(CDP.base, id.vars=c("year", "importer", "sector"), variable.name="exporter", value.name = "value")
CDP.cc <- CDP %>%
  filter(year==yr, importer %in% c.names, exporter %in% c.names) %>%
  arrange(sector, exporter, importer)

if(abs(sum(CDP.cc$val)/sum(wiot.cc$value) -1)>epsilon) 
  stop(paste("countries' exports to countries != countries' WIOD exports for year", yr))
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#state-to-country

wiot.cs <- wiot %>%
  filter(year==yr, importer_country %in% c.names, exporter %in% c("USA")) %>%
  arrange(sector, exporter, importer)


CDP.cs <- CDP %>%
  filter(year==yr, importer %in% c.names, exporter %in% s.names) %>%
  group_by(sector, importer) %>%
  mutate(val=sum(value)) %>%
  ungroup() %>%
  distinct(year, sector, importer, .keep_all = TRUE) %>%
  arrange(sector, exporter, importer)

if(abs(sum(CDP.cs$val)/sum(wiot.cs$value) -1)>epsilon) 
  stop(paste("states' exports to countries != US WIOD exports to countries for year", yr))
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# country-to-state

wiot.sc <- wiot %>%
  filter(year==yr, importer_country %in% c("USA"), exporter %in% c.names) %>%
  arrange(sector, exporter, importer)


CDP.sc <- CDP %>%
  filter(year==yr, importer %in% s.names, exporter %in% c.names) %>%
  group_by(sector, exporter) %>%
  mutate(val=sum(value)) %>%
  ungroup() %>%
  distinct(year, sector, exporter, .keep_all = TRUE) %>%
  arrange(sector, exporter, importer)

if(abs(sum(CDP.sc$val)/sum(wiot.sc$value) -1)>epsilon) 
  stop(paste("countries' exports to states != countries' WIOD exports to US for year", yr))
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#state-state

wiot.ss <- wiot %>%
  filter(year==yr, importer_country %in% c("USA"), exporter %in% c("USA")) %>%
  arrange(sector, exporter, importer)


CDP.ss <- CDP %>%
  filter(year==yr, importer %in% s.names, exporter %in% s.names) %>%
  group_by(sector) %>%
  mutate(val=sum(value)) %>%
  ungroup() %>%
  distinct(year, sector, .keep_all = TRUE) %>%
  arrange(sector, exporter, importer)

if(abs(sum(CDP.ss$val)/sum(wiot.ss$value) -1)>epsilon) 
  stop(paste("states' exports to states != US WIOD exports to US for year", yr))

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


}
```


