---
title: "Workers' flows"
---

# General information

This code calculates the row "Raw data by census year" of Table 1 of D.Coen-Pirani (2010) using our employment data.

## Input files

  L_1999.xlsx
  MobilityMatrices.xlsx

## Output files
  Table 1
 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list = ls())
```

```{r packages, warning=FALSE, include=FALSE, message=FALSE, results='hide', cache=FALSE}
# libraries
options( scipen=100, stringsAsFactors=FALSE );
# vector of libraries to be used
libs <- c( 'dplyr', 'tidyr', 'readstata13', 'haven', 'stringr', 'readxl', 'readr', 'data.table', 'ggplot2', 'gridExtra', 'janitor', 'Hmisc');
# Install libraries in case they are not installed
for( i in length(libs)){ 
  if( !(libs[i] %in% installed.packages()) ) install.packages( libs ) 
};
# Carga de bibliotecas
lapply( libs, require, character.only=TRUE );
```


```{r new8nov}
#On november 8th we changed the MobilityMatrices.xlsx file
#Now sheets mu_SS, mu_KeepZeros and mu_KeepGrossFlows represent the transition between 2000 and 2001

# Setting the working directory in the same folder where the code is located.
setwd(getwd())
rm(list = ls())

#Loading raw data
L_1999_raw <- read_excel("L_1999.xlsx")
mu_1999_raw <- read_excel("MobilityMatrices.xlsx", sheet = "mu_1999")

mu_sheets <- c("mu_2020", "mu_SS", "mu_KeepZeros", "mu_KeepGrossFlows", "mu_2000CF", "mu_2001CF", "mu_2002CF", "mu_2003CF", "mu_2004CF", "mu_2005CF", "mu_2006CF", "mu_2007CF", "mu_2008CF", "mu_2009CF", "mu_2010CF")

excel_sheet <- tibble(mu_sheets) %>%
  rename(excel_sheet = mu_sheets)

mu_list <- vector("list", length = length(mu_sheets))

for(i in 1:length(mu_list)){
  mu_list[[i]] <- read_excel("MobilityMatrices.xlsx", sheet = mu_sheets[i])
  
}

#Preparing mu for each year
mu_1999_long <- mu_1999_raw %>%
    pivot_longer(-c(1:3), names_to = "destination", values_to = "share") %>%
    mutate(state_dest = str_sub(destination, 1, -4),
           sector_dest = as.numeric(str_sub(destination, -2, length(destination)))) %>%
    select(-destination)



mu_long_list <- vector("list", length = length(mu_sheets))

for(i in 1:length(mu_long_list)){
  mu_long_list[[i]] <- mu_list[[i]] %>%
    pivot_longer(-c(1:3), names_to = "destination", values_to = "share") %>%
    mutate(state_dest = str_sub(destination, 1, -4),
           sector_dest = as.numeric(str_sub(destination, -2, length(destination)))) %>%
    select(-destination)
  
}


#Preparing L vector for each year
L_1999_long <- L_1999_raw %>%
  pivot_longer(starts_with("sector"), names_to = "sector_ori", values_to = "workers") %>%
  mutate(sector_ori = as.numeric(str_sub(sector_ori, -2, length(sector_ori)))) %>%
  rename(state_ori = region) %>%
  mutate(year = 1999)

L_2000_long <- mu_1999_long %>%
  select(-year) %>%
  left_join(L_1999_long, by = c("state_ori", "sector_ori")) %>%
  mutate(new_workers = workers * share,
         year = year + 1) %>%
  select(-c(state_ori, sector_ori, share, workers)) %>%
  rename(state_ori = state_dest,
         sector_ori = sector_dest) %>%
  group_by(state_ori, sector_ori) %>%
  summarise(workers = sum(new_workers),
            year = max(year)) %>%
  ungroup()


L_long_list <- vector("list", length = length(mu_sheets))

for(i in 1:length(L_long_list)){
  if(i <= 5){
    L_long_list[[i]] <- L_2000_long
  }
  if(i == 6){
    L_long_list[[i]] <- mu_long_list[[1]] %>%
      select(-year) %>%
      left_join(L_long_list[[1]], by = c("state_ori", "sector_ori")) %>%
      mutate(new_workers = workers * share,
             year = year + 1) %>%
      select(-c(state_ori, sector_ori, share, workers)) %>%
      rename(state_ori = state_dest,
             sector_ori = sector_dest) %>%
      group_by(state_ori, sector_ori) %>%
      summarise(workers = sum(new_workers),
                year = max(year)) %>%
      ungroup()
    
  }
  if(i > 6){
    L_long_list[[i]] <- mu_long_list[[i-1]] %>%
      select(-year) %>%
      left_join(L_long_list[[i-1]], by = c("state_ori", "sector_ori")) %>%
      mutate(new_workers = workers * share,
             year = year + 1) %>%
      select(-c(state_ori, sector_ori, share, workers)) %>%
      rename(state_ori = state_dest,
             sector_ori = sector_dest) %>%
      group_by(state_ori, sector_ori) %>%
      summarise(workers = sum(new_workers),
                year = max(year)) %>%
      ungroup()
    
  }
}

###### Checking whether mu_SS, mu_KeepZeros and mu_KeepGrossFlows generate the same distribution for L_2001#####

#mu_SS
mu_SS_L2001 <- mu_long_list[[2]] %>%
      select(-year) %>%
      left_join(L_long_list[[2]], by = c("state_ori", "sector_ori")) %>%
      mutate(new_workers = workers * share,
             year = year + 1) %>%
      select(-c(state_ori, sector_ori, share, workers)) %>%
      rename(state_ori = state_dest,
             sector_ori = sector_dest) %>%
      group_by(state_ori, sector_ori) %>%
      summarise(workers = sum(new_workers),
                year = max(year)) %>%
      ungroup() %>%
  rename(workers_SS = workers)

#mu_KeepZeros
mu_KZ_L2001 <- mu_long_list[[3]] %>%
      select(-year) %>%
      left_join(L_long_list[[3]], by = c("state_ori", "sector_ori")) %>%
      mutate(new_workers = workers * share,
             year = year + 1) %>%
      select(-c(state_ori, sector_ori, share, workers)) %>%
      rename(state_ori = state_dest,
             sector_ori = sector_dest) %>%
      group_by(state_ori, sector_ori) %>%
      summarise(workers = sum(new_workers),
                year = max(year)) %>%
      ungroup() %>%
  rename(workers_KZ = workers) %>%
  select(-year)

#mu_KeepGrossFlows
mu_KGF_L2001 <- mu_long_list[[4]] %>%
      select(-year) %>%
      left_join(L_long_list[[4]], by = c("state_ori", "sector_ori")) %>%
      mutate(new_workers = workers * share,
             year = year + 1) %>%
      select(-c(state_ori, sector_ori, share, workers)) %>%
      rename(state_ori = state_dest,
             sector_ori = sector_dest) %>%
      group_by(state_ori, sector_ori) %>%
      summarise(workers = sum(new_workers),
                year = max(year)) %>%
      ungroup() %>%
  rename(workers_KGF = workers) %>%
  select(-year)

L_2001_allmat <- mu_SS_L2001 %>%
  left_join(mu_KZ_L2001, by = c("state_ori", "sector_ori")) %>%
  left_join(mu_KGF_L2001, by = c("state_ori", "sector_ori")) %>% 
  select(-year)

L_2001_all_state <- L_2001_allmat %>%
  group_by(state_ori) %>%
  summarise_at(c("workers_SS", "workers_KZ", "workers_KGF"), sum) %>%
  rename(state = state_ori)

rm(mu_SS_L2001, mu_KZ_L2001, mu_KGF_L2001)
# pdf("L_2001_state.pdf", height=15, width=10)
# grid.table(L_2001_all_state)
# dev.off()


############ STATE-SECTOR LEVEL ###############
# Calculating table 1 at the state-sector level
#State-sector  to state-sector flows of workers

pop_st_sec_list <- vector("list", length = length(mu_sheets))

for(i in 1:length(pop_st_sec_list)){
  pop_st_sec_list[[i]] <- L_long_list[[i]] %>%
    rename(population = workers,
           state = state_ori,
           sector = sector_ori) %>%
    select(-year)
  
}

flows_st_sec <- vector("list", length = length(mu_sheets))

for(i in 1:length(flows_st_sec)){
  flows_st_sec[[i]] <- mu_long_list[[i]] %>%
    select(-year) %>%
    left_join(L_long_list[[i]], by = c("state_ori", "sector_ori")) %>%
    mutate(flow = workers * share) %>%
    select(year, state_ori, sector_ori, state_dest, sector_dest, flow) %>%
    left_join(pop_st_sec_list[[i]], by = c("state_ori" = "state", "sector_ori" = "sector")) %>%
    mutate(outflow_rate = 100* flow/population) %>%
    select(-population) %>%
    left_join(pop_st_sec_list[[i]], by = c("state_dest" = "state", "sector_dest" = "sector")) %>%
    mutate(inflow_rate = 100 * flow/population) %>%
    select(-population)
}


#Flow rates at the state-sector level (sum across origin /destination)
table_st_sec_data <- vector("list", length = length(mu_sheets))

for(i in 1:length(table_st_sec_data)){
  outflows <- flows_st_sec[[i]] %>%
    filter(state_ori != state_dest | sector_ori != sector_dest) %>%
    group_by(state_ori, sector_ori) %>%
    summarise(outflow_rate = sum(outflow_rate),
              year = max(year)) %>%
    ungroup() %>%
    rename(state = state_ori,
           sector = sector_ori) 
  
  inflows <- flows_st_sec[[i]] %>%
    filter(state_ori != state_dest | sector_ori != sector_dest) %>%
    group_by(state_dest, sector_dest) %>%
    summarise(inflow_rate = sum(inflow_rate)) %>%
    ungroup() %>%
    rename(state = state_dest,
           sector = sector_dest)
  
  table_st_sec_data[[i]] <- outflows %>%
    left_join(inflows, by = c("state", "sector")) %>%
    mutate(gross_rate = inflow_rate + outflow_rate,
           net_alloc = abs(inflow_rate - outflow_rate)) %>%
    left_join(pop_st_sec_list[[i]], by = c("state", "sector"))
  
  rm(outflows, inflows)
  
}

#Calculating table 1 at the state-sector level, weighted by employment on state-sector
table_1_st_sec_w <- vector("list", length = length(mu_sheets))

for(i in 1:length(table_1_st_sec_w)){
  table_1_st_sec_w[[i]] <- table_st_sec_data[[i]] %>%
    summarise(gross_rate = weighted.mean(gross_rate, population),
              net_rate = weighted.mean(net_alloc, population),
              av_outflow_rate = weighted.mean(outflow_rate, population),
              av_inflow_rate = weighted.mean(inflow_rate, population),
              outflow_sd = sqrt(wtd.var(outflow_rate, population)),
              inflow_sd = sqrt(wtd.var(inflow_rate, population)),
              net_flow_sd = sqrt(wtd.var(net_alloc, population)),
              year = max(year))
  table_1_st_sec_w[[i]] <- table_1_st_sec_w[[i]] %>%
    mutate(excess = gross_rate - net_rate) %>%
    relocate(year, gross_rate, net_rate, excess, av_outflow_rate, av_inflow_rate, outflow_sd, inflow_sd, net_flow_sd)
  
  
}

table_1_st_sec_w <- rbindlist(table_1_st_sec_w)
table_1_st_sec_w <- cbind(table_1_st_sec_w, excel_sheet)
table_1_st_sec <- table_1_st_sec_w %>%
  select(excel_sheet, gross_rate, excess, outflow_sd, inflow_sd, net_flow_sd)  %>%
  mutate(excel_sheet = ifelse(excel_sheet == "mu_2020", "mu_2000", excel_sheet))




##################### STATE LEVEL ###############
## Calculating table 1 at the state level
population_list <- vector("list", length = length(mu_sheets))

for(i in 1:length(population_list)){
  population_list[[i]] <- L_long_list[[i]] %>%
    group_by(state_ori) %>%
    summarise(population = sum(workers)) %>%
    rename(state = state_ori) %>%
    ungroup()
  
}


#State-state flows of workers
flows <- vector("list", length = length(mu_sheets))

for(i in 1:length(flows)){
  flows[[i]] <- mu_long_list[[i]] %>%
    select(-year) %>%
    left_join(L_long_list[[i]], by = c("state_ori", "sector_ori")) %>%
    mutate(flow = workers * share) %>%
    group_by(state_ori, state_dest) %>%
    summarise(flow = sum(flow),
              year = max(year)) %>%
    ungroup() %>%
    left_join(population_list[[i]], by = c("state_ori" = "state")) %>%
    mutate(outflow_rate = 100* flow/population) %>%
    select(-population) %>%
    left_join(population_list[[i]], by = c("state_dest" = "state")) %>%
    mutate(inflow_rate = 100 * flow/population) %>%
    select(-population)
}


#Flow rates at the state level (sum across origin /destination)
table_data <- vector("list", length = length(mu_sheets))

for(i in 1:length(table_data)){
  outflows <- flows[[i]] %>%
    filter(state_ori != state_dest) %>%
    group_by(state_ori) %>%
    summarise(outflow_rate = sum(outflow_rate),
              year = max(year)) %>%
    ungroup() %>%
    rename(state = state_ori) 
  
  inflows <- flows[[i]] %>%
    filter(state_ori != state_dest) %>%
    group_by(state_dest) %>%
    summarise(inflow_rate = sum(inflow_rate)) %>%
    ungroup() %>%
    rename(state = state_dest)
  
  table_data[[i]] <- outflows %>%
    left_join(inflows, by = "state") %>%
    mutate(gross_rate = inflow_rate + outflow_rate,
           net_alloc = abs(inflow_rate - outflow_rate)) %>%
    left_join(population_list[[i]], by = "state")
  
  rm(outflows, inflows)
  
}


#weighted by states' population
table_1_state_w <- vector("list", length = length(mu_sheets))

for(i in 1:length(table_1_state_w)){
  table_1_state_w[[i]] <- table_data[[i]] %>%
    summarise(gross_rate = weighted.mean(gross_rate, population),
              net_rate = weighted.mean(net_alloc, population),
              av_outflow_rate = weighted.mean(outflow_rate, population),
              av_inflow_rate = weighted.mean(inflow_rate, population),
              outflow_sd = sqrt(wtd.var(outflow_rate, population)),
              inflow_sd = sqrt(wtd.var(inflow_rate, population)),
              net_flow_sd = sqrt(wtd.var(net_alloc, population)),
              year = max(year)) %>%
    mutate(excess = gross_rate - net_rate) %>%
    relocate(year, gross_rate, net_rate, excess, av_outflow_rate, av_inflow_rate, outflow_sd, inflow_sd, net_flow_sd)
  
  
}

table_1_state_w <- rbindlist(table_1_state_w)
table_1_state_w <- cbind(table_1_state_w, excel_sheet)

table_1_state <- table_1_state_w %>%
  select(excel_sheet, gross_rate, excess, outflow_sd, inflow_sd, net_flow_sd) %>%
  mutate(excel_sheet = ifelse(excel_sheet == "mu_2020", "mu_2000", excel_sheet))

```

