---
title: "Cleaning_panel"
---

# General information

This code creates a panel dataset with industries information.

## Input files

1.cps_panel.dta 2.states_fips_num.xlsx

## Output files

1.  clean_data.dta
2.  clean_data_new.dta

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list = ls())
```

```{r packages, warning=FALSE, include=FALSE, message=FALSE, results='hide', cache=FALSE}
# libraries
options( scipen=100, stringsAsFactors=FALSE );
# vector of libraries to be used
libs <- c( 'dplyr', 'tidyr', 'readstata13', 'haven', 'stringr', 'nleqslv', 'gdata', 'Statamarkdown', 'readxl', 'foreign', 'reshape2', 'RStata' , 'devtools');
# Install libraries in case they are not installed
#for( i in length(libs)){ 
#  if( !(libs[i] %in% installed.packages()) ) install.packages( libs ) 
#};
# Carga de bibliotecas
lapply( libs, require, character.only=TRUE );
```

#cleaning the original data_base

```{r data}
#Path
# this goes one step backwards from the root directory, so that it works the same in all computers
setwd(dirname(getwd()))


# Load the CPS data. 
cps_panel <-read_dta("C:/Users/Efraín/Downloads/cps_panel.dta")
# Create a unique identifier for each individual
cps_panel <- cps_panel %>%
  group_by(cpsidp) %>%
  mutate(id = cur_group_id()) %>%
  ungroup()
# Generating 'quarter' within each 'id'
cps_panel <- cps_panel%>%
  arrange(id, month, mish) %>%
  group_by(id) %>%
  mutate(quarter = row_number()) %>%
  ungroup()

#Usign a subset of observations to make a faster code:
cps_panel0<-cps_panel %>%
  select(id, month, year, mish, statefip, ind, wtfinl, quarter, sex, race, bpl, nativity, popstat, age, labforce)

#We want to keep people that we observe for at least 4 quarters. 
cps_panel0  <- cps_panel0%>%
  group_by(id) %>%
  mutate(num = n()) %>%
  filter(num >= 4) %>%
  ungroup() %>%
  select(-num)

# Generating 'quarter' column and dropping rows where 'quarter' > 8
# Filtering rows where 'quarter' is not greater than 8
cps_panel0  <- cps_panel0 %>%
  filter(quarter <= 8)
# Generating 'tag' variable based on 'id'
cps_panel0 <- cps_panel0 %>%
  group_by(id) %>%
  mutate(tag = as.integer(row_number() == 1)) %>%
  ungroup() %>%
  mutate(tag = ifelse(duplicated(id), 0, tag))
# First consistency: Counting the number of times that someone changes sex. 
# Finding the sex at the first and last observations for each person (id)
cps_panel0 <- cps_panel0 %>%
  arrange(id, sex) %>%
  group_by(id) %>%
  mutate(change = 1000 * sex[1] + 100 * sex[2] + 10 * sex[3] + sex[4]) %>%
  ungroup()

#Checking consistency
cps_panel0 <-cps_panel0 %>%
  filter(change == 2222 | change == 1111) %>% select(-change, -sex)



# Second consistency: Race
cps_panel0 <- cps_panel0 %>%
  group_by(id) %>%
   mutate(change2 = ifelse(n_distinct(race) == 1, 1, 0)) %>%
  ungroup() %>%  filter(change2 == 1 )  %>% select(-change2, -race)

# Third consistency: Nativity
cps_panel0 <- cps_panel0 %>%
  group_by(id) %>%
   mutate(change3 = ifelse(n_distinct(nativity) == 1, 1, 0)) %>%
  ungroup() %>%  filter(change3 == 1 ) %>% select(-change3, -nativity)
#Fourth consistency: Popstat
cps_panel0 <- cps_panel0 %>%
  group_by(id) %>%
   mutate(change4 = ifelse(n_distinct(popstat) == 1, 1, 0)) %>%
  ungroup() %>%  filter(change4 == 1 )  %>% select(-change4, -popstat)

#Fifth cosistency: Age
#first we check how many changed the age, nobody should change it more than one year.
cps_panel0<-cps_panel0[order(cps_panel0$id, cps_panel0$age), ]


cps_panel0 <-cps_panel0 %>%
  arrange(id, age) %>%
   group_by(id) %>%
  mutate(age_difference = max(age) - min(age)) %>%  ungroup() 


cps_panel0  <- cps_panel0 %>% 
    arrange(id, age) %>%
   filter(age_difference <= 3) 


#Sixth consistency: Birhtplace
cps_panel0 <- cps_panel0 %>%
  group_by(id) %>%
   mutate(change6 = ifelse(n_distinct(bpl) == 1, 1, 0))  %>%
  ungroup() %>%  filter(change6 == 1 )



#Creating sectors:
cps_panel0$sector <- NA
# Replacing 'sector' values with 0 where 'labforce' is equal to 1
cps_panel0$sector <- ifelse(cps_panel0$labforce == 1, 0, cps_panel0$sector)

 #Generating the clean data.
clean_data <- cps_panel0 %>%select(id, month, year, mish, statefip, ind, sector, wtfinl, age) 
#Recoding sectors:
clean_data$sector <- ifelse(clean_data$ind %in% c(10, 11, 12, 20, 30, 31, 32), 14, clean_data$sector)
clean_data <- clean_data %>%
  mutate(sector = case_when(
    ind %in% c(100, 101, 102, 110, 111, 112, 120, 121, 122, 130) ~ 1,
    ind %in% c(132, 140, 141, 142, 150, 151, 152) ~ 2,
    ind %in% c(160, 161, 162, 171, 172) ~ 3,
    ind %in% c(200, 201, 40, 41, 42, 50) ~ 4,
    ind %in% c(180, 181, 182, 190, 191, 192) ~ 5,
    ind %in% c(210, 211, 212) ~ 6,
    ind %in% c(250, 251, 252, 261, 262) ~ 7,
    ind %in% c(270, 271, 272, 280, 281, 282, 290, 291 ) ~ 8,
    ind %in% c(300, 301, 310, 311, 312, 320) ~ 9,
    ind %in% c(321, 322, 331, 332, 340, 341, 342, 350) ~ 10,
    ind %in% c(352, 360, 361, 362, 370) ~ 11,
    ind %in% c(372, 380, 381, 390, 391, 392) ~ 12,
    ind %in% c(60, 351, 242, 501, 502, 510, 511, 512, 521, 522, 530, 531, 532, 540, 541, 542, 550, 551, 552, 560, 561, 562, 571, 580, 581, 582 ) ~ 13,
    TRUE ~ sector  # Keep unchanged if not matching any condition
  ))

#Dropping militar and public services
clean_data<- clean_data %>%
  filter(ind <= 893)
#Other corrections
clean_data <- clean_data %>%
  mutate(sector = case_when(
    ind > 582 ~ 13,
    ind %in% c(400, 401, 402, 410, 411, 420, 421, 422, 432, 440, 441, 442, 450, 451, 452, 470, 471, 472) ~ 13,
    TRUE ~ sector
  )) %>%
  filter(!(ind == 412))
clean_data <- clean_data %>%
  mutate(sector = ifelse(ind == 0, 0, sector))

#Age filter 
clean_data  <- clean_data %>%
  filter(age < 66 & age > 24)

# Creating new columns based on conditions for 'mish'
sector_origin1<- clean_data  %>%
  filter(mish==1)  %>%
  group_by(id) %>%
  mutate(sector_origin1 = first(sector)) %>%
  select(id, sector_origin1) %>%
  ungroup()
#destination
sector_destination4 <- clean_data %>% 
  filter(mish==4)  %>%
  group_by(id) %>%
  mutate(sector_destination4 = first(sector)) %>%
  select(id, sector_destination4) %>%
  ungroup()
#second origin in 5th month in survey
sector_origin5 <- clean_data%>% 
  filter(mish==5)  %>%
  group_by(id) %>%
  mutate(sector_origin5 = first(sector)) %>%
  select(id, sector_origin5) %>%
  ungroup()
#second destination in 8th month in survey
sector_destination8 <- clean_data %>% 
  filter(mish==8)  %>%
  group_by(id) %>%
  mutate(sector_destination8 = first(sector)) %>%
  select(id, sector_destination8) %>%
  ungroup()

#Merge back to original data.
merged_data1<- left_join(clean_data, sector_origin1, by = "id")
merged_data2<-left_join(merged_data1, sector_destination4, by = "id")
merged_data3<-left_join(merged_data2, sector_origin5, by = "id")
merged_data4<-left_join(merged_data3, sector_destination8, by = "id")

#Saving clean data
clean_data<-merged_data4 %>%
  select(id, month, year, mish, statefip, ind, sector, 
         sector_origin1, sector_destination4, 
         sector_origin5, sector_destination8, wtfinl)

write_dta(clean_data, "C:/Users/Efraín/Downloads/clean_data.dta")


###Second part:
clean_data<-read_dta("C:/Users/Efraín/Downloads/clean_data.dta")
state_fip <- read_excel("C:/Users/Efraín/Downloads/states_fips_num.xlsx", range = "A1:D52")
state<- state_fip  %>% 
  select(st_num, st_fips, st_name) 

clean_data<-clean_data %>%
  filter(!is.na(sector))

clean_data<-clean_data %>%
    rename(P_ID = id) %>%
    mutate(monthname = month.name[month]) %>% 
    select(-month) %>%
   mutate(month = substr(monthname, 1, 3))
  
clean_data<-clean_data %>%
  select(-monthname) %>%
  rename(inter_num=mish) %>%
  select(-ind)  %>%
  rename(st_fips=statefip)

clean_data_new<- left_join(clean_data, state , by="st_fips")
clean_data_new <- clean_data_new %>%
  select(-st_num) %>%
  filter(st_fips != 11)
#saving.
write_dta(clean_data_new, "C:/Users/Efraín/Downloads/clean_data_new.dta")

```
