---
title: "US state-country trade database construction"
output:
  html_document:
    df_print: paged
  pdf_document:
    number_sections: yes
  word_document: default
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{pifont}
- \usepackage{mathpazo}
- \newcommand{\xmark}{\ding{55}}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list = ls())
```


#Libraries
```{r warning=FALSE, include=FALSE, message=FALSE, results='hide', cache=FALSE}

# libraries
#options( scipen=100, stringsAsFactors=FALSE );
# vector of libraries to be used
libs <- c( 'dplyr', 'tidyr', 'readstata13', 'haven', 'stringr', 'nleqslv', 'gdata', 'Statamarkdown', 'readxl', 'writexl', 'rjson', 'foreign');
# Install libraries in case they are not installed
#for( i in length(libs)){ 
  #if( !(libs[i] %in% installed.packages()) ) install.packages( libs ) 
#};
# Carga de bibliotecas
lapply( libs, require, character.only=TRUE );
```


# Uploading and unifying .csv files
```{r}

#Export data
base1.e <-read.csv("State Exports by NAICS Commodities-1.csv",skip=3, header = FALSE, sep = ",", dec = ".")
base2.e <-read.csv("State Exports by NAICS Commodities-2.csv",skip=3, header = FALSE, sep = ",", dec = ".")
base3.e <-read.csv("State Exports by NAICS Commodities-3.csv",skip=3, header = FALSE, sep = ",", dec = ".")
base4.e <-read.csv("State Exports by NAICS Commodities-4.csv",skip=3, header = FALSE, sep = ",", dec = ".")
base5.e <-read.csv("State Exports by NAICS Commodities-5.csv",skip=3, header = FALSE, sep = ",", dec = ".")

#Import data
base1.i <-read.csv("State Imports by NAICS Commodities-1.csv",skip=3, header = FALSE, sep = ",", dec = ".")
base2.i <-read.csv("State Imports by NAICS Commodities-2.csv",skip=3, header = FALSE, sep = ",", dec = ".")
base3.i <-read.csv("State Imports by NAICS Commodities-3.csv",skip=3, header = FALSE, sep = ",", dec = ".")
base4.i <-read.csv("State Imports by NAICS Commodities-4.csv",skip=3, header = FALSE, sep = ",", dec = ".")
base5.i <-read.csv("State Imports by NAICS Commodities-5.csv",skip=3, header = FALSE, sep = ",", dec = ".")


#Unifying data
Base.e <- rbind(base1.e, base2.e, base3.e, base4.e, base5.e)
Base.i <- rbind(base1.i, base2.i, base3.i, base4.i, base5.i)

colnames(Base.e) = c("state", "naics3", "country", "year", "exports")
colnames(Base.i) = c("state", "naics3", "country", "year", "imports")

Base.e <- Base.e %>%
  arrange(year, state) %>%
  select(year, state, naics3, country, everything())
Base.e$exports <- as.numeric(gsub(",","",Base.e$exports))
Base.i <- Base.i %>%
  arrange(year, state) %>%
  select(year, state, naics3, country, everything())
Base.i$imports <- as.numeric(gsub(",","",Base.i$imports))


#exporting to .dta
write.dta(Base.e, "census_exports.dta") 
write.dta(Base.i, "census_imports.dta") 



```






